# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
r"""Certified spectral gaps of finite lattice transfer matrices.

Builds a **fixed**, finite-dimensional transfer matrix with rigorously enclosed
entries (:mod:`.matrices`), certifies a lower bound on its lattice-unit mass gap
``m a = -ln(|lambda_1| / lambda_0)`` with the rigorous engines of
:mod:`omnibias.core.verified.eig` (:mod:`.gap`), and seals the result into a
tamper-evident certificate whose rational obligation the Mathlib-free Lean kernel
can discharge (:mod:`.certificates`).

The ingredients were already here and simply never connected: the gap engines name
these very matrices in their docstrings, ``quadratic_casimir`` returns an *exact*
``Fraction``, ``besseli_iv`` encloses the Wilson character coefficients, and the
Lean kernel's ``spectral_gap_pos`` lemma already discharges a
``subdominant_ratio_upper`` obligation.

Scope
-----
Every certificate is a statement about **one fixed matrix, at one fixed lattice
spacing, in finite dimension**.  ``continuum_claim`` is always ``False``,
:func:`heat_kernel_gap_scaling_report` is labelled evidence rather than proof, and
nothing here is a claim about the Yang-Mills mass gap.
"""

from __future__ import annotations

from omnibias.geometry.gauge.transfer.certificates import (
    FINITE_GAUGE_REPORT_KIND,
    FINITE_GAUGE_REPORT_SCHEMA_VERSION,
    HAMILTONIAN_GAP_KIND,
    HAMILTONIAN_GAP_SCHEMA_VERSION,
    POLYMER_DOMAIN_KIND,
    POLYMER_DOMAIN_SCHEMA_VERSION,
    STRIP_RP_KIND,
    STRIP_RP_SCHEMA_VERSION,
    STRONG_COUPLING_KIND,
    STRONG_COUPLING_SCHEMA_VERSION,
    THREE_PLAQUETTE_GAP_KIND,
    TORUS_RP_KIND,
    TORUS_RP_SCHEMA_VERSION,
    TRANSFER_GAP_KIND,
    TRANSFER_GAP_SCHEMA_VERSION,
    finite_gauge_report_schema_errors,
    hamiltonian_gap_schema_errors,
    polymer_domain_schema_errors,
    replay_finite_gauge_report,
    replay_hamiltonian_gap,
    replay_polymer_domain,
    replay_strip_rp,
    replay_strong_coupling_gap,
    replay_transfer_matrix_gap,
    seal_finite_gauge_report_certificate,
    seal_hamiltonian_gap_certificate,
    seal_polymer_domain_certificate,
    seal_strip_rp_certificate,
    seal_strong_coupling_certificate,
    seal_transfer_gap_certificate,
    strip_rp_schema_errors,
    strong_coupling_schema_errors,
    transfer_gap_schema_errors,
)
from omnibias.geometry.gauge.transfer.gap import (
    BIRKHOFF_METHOD,
    LEHMANN_METHOD,
    SYMMETRIC_METHOD,
    EffectiveMassCurve,
    EffectiveMassPoint,
    GapCandidate,
    MultistepGapResult,
    ScalingPoint,
    ScalingReport,
    TransferGapResult,
    certified_effective_mass_curve,
    certified_gap_scaling_table,
    certified_multistep_gap_refinement,
    certified_transfer_matrix_gap,
    heat_kernel_gap_scaling_report,
)
from omnibias.geometry.gauge.transfer.hamiltonian import (
    COUPLING_LOCK,
    GaugeHamiltonian,
    HamiltonianGapResult,
    certified_hamiltonian_gap,
    plaquette_holonomy_trial_space,
    standard_basis_trial_space,
    su2_three_plaquette_hamiltonian,
    su2_two_plaquette_hamiltonian,
)
from omnibias.geometry.gauge.transfer.matrices import (
    TransferMatrix,
    su2_class_angle_transfer,
    su2_heat_kernel_transfer,
    su2_wilson_transfer,
    su3_heat_kernel_transfer,
    su3_wilson_transfer,
    u1_heat_kernel_transfer,
)
from omnibias.geometry.gauge.transfer.montecarlo import (
    MonteCarloGapCheck,
    PathEnsemble,
    certified_gap_versus_monte_carlo,
    sample_transfer_path_ensemble,
)
from omnibias.geometry.gauge.transfer.report import (
    FiniteGaugeReport,
    FiniteGaugeSpec,
    HaarIdentityCheck,
    MeasuredG1,
    default_finite_gauge_spec,
    finite_gauge_report,
    finite_gauge_spec_from_mapping,
    finite_gauge_spec_to_mapping,
)
from omnibias.geometry.gauge.transfer.strip import (
    STRIP_COUPLING_LOCK,
    certified_strip_cluster_tail,
    certified_strip_reflection_positivity,
    su2_spatial_strip_transfer,
    su2_spatial_torus_transfer,
)
from omnibias.geometry.gauge.transfer.strong_coupling import (
    BACKTRACK_POLYMER_METHOD,
    BETA_LOCK,
    BETA_LOCK_CRUDE,
    CLUSTER_POLYMER_METHOD,
    CRUDE_POLYMER_METHOD,
    POLYMER_BETA_DOMAIN_METHOD,
    POLYMER_BETA_GRID,
    POLYMER_METHOD,
    WILSON_CHARACTER_METHOD,
    PolymerDomainResult,
    StrongCouplingGapResult,
    WilsonCharacterGapResult,
    certified_polymer_beta_domain,
    certified_strong_coupling_glueball_bound,
    certified_wilson_character_gap,
    polymer_coordination,
    polymer_coordination_backtrack,
    polymer_first_step,
    su2_wilson_activity,
)
from omnibias.geometry.gauge.transfer.trial import (
    GRAM_COND_THRESHOLD,
    Loop,
    TrialSpace,
    holonomy_trial_space,
    su2_holonomy_trace,
)

__all__ = [
    "BACKTRACK_POLYMER_METHOD",
    "BETA_LOCK",
    "BETA_LOCK_CRUDE",
    "BIRKHOFF_METHOD",
    "CLUSTER_POLYMER_METHOD",
    "COUPLING_LOCK",
    "CRUDE_POLYMER_METHOD",
    "FINITE_GAUGE_REPORT_KIND",
    "FINITE_GAUGE_REPORT_SCHEMA_VERSION",
    "GRAM_COND_THRESHOLD",
    "HAMILTONIAN_GAP_KIND",
    "HAMILTONIAN_GAP_SCHEMA_VERSION",
    "LEHMANN_METHOD",
    "POLYMER_BETA_DOMAIN_METHOD",
    "POLYMER_BETA_GRID",
    "POLYMER_DOMAIN_KIND",
    "POLYMER_DOMAIN_SCHEMA_VERSION",
    "POLYMER_METHOD",
    "STRIP_COUPLING_LOCK",
    "STRIP_RP_KIND",
    "STRIP_RP_SCHEMA_VERSION",
    "STRONG_COUPLING_KIND",
    "STRONG_COUPLING_SCHEMA_VERSION",
    "SYMMETRIC_METHOD",
    "THREE_PLAQUETTE_GAP_KIND",
    "TORUS_RP_KIND",
    "TORUS_RP_SCHEMA_VERSION",
    "TRANSFER_GAP_KIND",
    "TRANSFER_GAP_SCHEMA_VERSION",
    "WILSON_CHARACTER_METHOD",
    "EffectiveMassCurve",
    "EffectiveMassPoint",
    "FiniteGaugeReport",
    "FiniteGaugeSpec",
    "GapCandidate",
    "GaugeHamiltonian",
    "HaarIdentityCheck",
    "HamiltonianGapResult",
    "Loop",
    "MeasuredG1",
    "MonteCarloGapCheck",
    "MultistepGapResult",
    "PathEnsemble",
    "PolymerDomainResult",
    "ScalingPoint",
    "ScalingReport",
    "StrongCouplingGapResult",
    "TransferGapResult",
    "TransferMatrix",
    "TrialSpace",
    "WilsonCharacterGapResult",
    "certified_effective_mass_curve",
    "certified_gap_scaling_table",
    "certified_gap_versus_monte_carlo",
    "certified_hamiltonian_gap",
    "certified_multistep_gap_refinement",
    "certified_polymer_beta_domain",
    "certified_strong_coupling_glueball_bound",
    "certified_strip_cluster_tail",
    "certified_strip_reflection_positivity",
    "certified_transfer_matrix_gap",
    "certified_wilson_character_gap",
    "default_finite_gauge_spec",
    "finite_gauge_report",
    "finite_gauge_report_schema_errors",
    "finite_gauge_spec_from_mapping",
    "finite_gauge_spec_to_mapping",
    "hamiltonian_gap_schema_errors",
    "heat_kernel_gap_scaling_report",
    "holonomy_trial_space",
    "plaquette_holonomy_trial_space",
    "polymer_coordination",
    "polymer_coordination_backtrack",
    "polymer_domain_schema_errors",
    "polymer_first_step",
    "replay_finite_gauge_report",
    "replay_hamiltonian_gap",
    "replay_polymer_domain",
    "replay_strong_coupling_gap",
    "replay_strip_rp",
    "replay_transfer_matrix_gap",
    "sample_transfer_path_ensemble",
    "seal_finite_gauge_report_certificate",
    "seal_hamiltonian_gap_certificate",
    "seal_polymer_domain_certificate",
    "seal_strong_coupling_certificate",
    "seal_strip_rp_certificate",
    "seal_transfer_gap_certificate",
    "strip_rp_schema_errors",
    "standard_basis_trial_space",
    "strong_coupling_schema_errors",
    "su2_class_angle_transfer",
    "su2_heat_kernel_transfer",
    "su2_holonomy_trace",
    "su2_spatial_strip_transfer",
    "su2_spatial_torus_transfer",
    "su2_three_plaquette_hamiltonian",
    "su2_two_plaquette_hamiltonian",
    "su2_wilson_activity",
    "su2_wilson_transfer",
    "su3_heat_kernel_transfer",
    "su3_wilson_transfer",
    "transfer_gap_schema_errors",
    "u1_heat_kernel_transfer",
]
