# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Functional operator surface for the JAX backend."""

from __future__ import annotations

from omnibias.fields.jax.ops.basic import (
    derivative,
    divergence,
    gradient,
    laplacian,
    mixed_partial,
    stack_components,
    value,
    vector_derivative,
)
from omnibias.fields.jax.ops.complex import dz, dzbar
from omnibias.fields.jax.ops.conservation import (
    advection_diffusion_residual,
    conservation_residual,
    dalembertian,
    diffusive_flux,
    flux_divergence,
    grad_squared_norm,
    gradient_of_composition,
    laplacian_of_composition,
    variable_coefficient_diffusion,
    wave_operator,
)
from omnibias.fields.jax.ops.high_order import (
    biharmonic,
    gradient_of_derivative,
    hessian,
    jacobian,
    polylaplacian,
    spatial_hessian,
    vector_biharmonic,
    vector_hessian,
    vector_laplacian,
    vector_polylaplacian,
)
from omnibias.fields.jax.ops.integral import (
    integrate,
    line_integral,
    quadrature_nodes,
)
from omnibias.fields.jax.ops.nonlinear import (
    advection,
    directional_derivative,
    material_derivative,
    p_laplacian,
    skew_symmetric_advection,
)
from omnibias.fields.jax.ops.norms import inner_product, l2_norm, sobolev_norm
from omnibias.fields.jax.ops.registry import register
from omnibias.fields.jax.ops.tensor import (
    tensor_cofactor,
    tensor_determinant,
    tensor_divergence,
    tensor_double_dot,
    tensor_inverse,
    tensor_matmul,
    tensor_trace,
    tensor_transpose,
)
from omnibias.fields.jax.ops.vector import (
    curl,
    curl_of_curl,
    deformation_gradient,
    gradient_of_divergence,
    rate_of_rotation_tensor,
    spatial_jacobian,
    strain_rate,
    vorticity,
)

__all__ = [
    "advection",
    "advection_diffusion_residual",
    "biharmonic",
    "conservation_residual",
    "curl",
    "curl_of_curl",
    "dalembertian",
    "deformation_gradient",
    "derivative",
    "diffusive_flux",
    "directional_derivative",
    "divergence",
    "dz",
    "dzbar",
    "flux_divergence",
    "grad_squared_norm",
    "gradient",
    "gradient_of_composition",
    "gradient_of_derivative",
    "gradient_of_divergence",
    "hessian",
    "inner_product",
    "integrate",
    "jacobian",
    "l2_norm",
    "laplacian",
    "laplacian_of_composition",
    "line_integral",
    "material_derivative",
    "mixed_partial",
    "p_laplacian",
    "polylaplacian",
    "quadrature_nodes",
    "rate_of_rotation_tensor",
    "register",
    "skew_symmetric_advection",
    "sobolev_norm",
    "spatial_hessian",
    "spatial_jacobian",
    "stack_components",
    "strain_rate",
    "tensor_cofactor",
    "tensor_determinant",
    "tensor_divergence",
    "tensor_double_dot",
    "tensor_inverse",
    "tensor_matmul",
    "tensor_trace",
    "tensor_transpose",
    "value",
    "variable_coefficient_diffusion",
    "vector_biharmonic",
    "vector_derivative",
    "vector_hessian",
    "vector_laplacian",
    "vector_polylaplacian",
    "vorticity",
    "wave_operator",
]
