# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""omnibias-symbolic: neural-jet equation discovery and interpretable surrogates.

This package turns omnibias's closed-form activation derivative towers into a
scientific-discovery toolkit:

* :class:`NeuralJetDiscoverer` searches compact *implicit* relations among
  generic jet coordinates ``x, y, dy, d2y, ...`` (a library-free SINDy variant).
  Because every jet column is produced by an exact omnibias fastpath, it recovers
  identities such as ``dy = y`` (exp), ``d2y = -y`` (sin/cos), and the Riccati
  relation ``dy = 1 - y^2`` (tanh) without ever being given a named ``exp``,
  ``sin``, or ``tanh`` basis function.
* :func:`discover_interpretable_surrogate` performs AutoML over Taylor / Fourier
  / hybrid libraries with train/validation/test fairness splits.
* :class:`FieldLawDiscoverer` lifts the jet search to **many variables**: from a
  :class:`NeuralFieldND` it reads off *exact* closed-form mixed partials
  (:func:`extract_field_jet`) and the whole vector-calculus surface -- gradient,
  divergence, curl, Laplacian, Hessian, the Ito / Fokker--Planck generator and the
  constant-metric Laplace--Beltrami operator -- then recovers multivariate /
  space--time PDE laws (Laplace, heat, wave, Burgers, 2-D heat).
* :func:`discover_pde_operator_law` recovers PDE operator coefficients (e.g. the
  heat-equation diffusivity on ``u_xx``).
* :mod:`omnibias.symbolic.geometry_discovery` lifts the surface to **Riemannian
  geometry on a curved manifold**: the Laplace--Beltrami operator
  (:func:`laplace_beltrami`), Christoffel symbols, covariant Hessian, and the
  Riemann / Ricci / scalar curvature, plus the *pullback metric of a learned
  chart* ``g = J^T J`` (:func:`pullback_metric_field`). Injected as an exact
  operator atom it recovers genuinely geometric laws -- e.g. heat flow on the
  round sphere ``u_t = Delta_g u`` (:func:`discover_geometric_heat_law`), whose
  position-dependent ``cot(theta)`` drift is irreducible to any flat relation.
* :mod:`omnibias.symbolic.exterior_discovery` adds the **exterior calculus /
  de Rham--Hodge complex**: :class:`DifferentialForm` components are neural jets,
  and the exterior derivative :func:`exterior_derivative` (``d``), Hodge star,
  :func:`codifferential` and :func:`hodge_laplacian` satisfy the fundamental
  identity ``d . d = 0`` -- which *is* ``curl(grad) = 0`` on a 0-form and
  ``div(curl) = 0`` on a 1-form, and the homogeneous Maxwell law ``dF = 0`` for
  ``F = dA`` -- exactly, for any order.
* :mod:`omnibias.symbolic.blasius` solves the Blasius boundary layer and recovers
  its governing identity ``f''' = -0.5 f f''`` from numerical / neural jets, plus
  explicit rational and ODE-recurrence Pade surrogates.

See ``docs/roadmap.md`` for the place of this package in the wider stack.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError as _PkgNotFound
from importlib.metadata import version as _pkg_version

from omnibias.symbolic.blasius import (
    BlasiusSolution,
    discover_blasius_explicit_expression,
    discover_blasius_from_neural_surrogate,
    discover_blasius_identity,
    discover_blasius_taylor_pade_expression,
    evaluate_blasius,
    solve_blasius,
    write_blasius_artifacts,
)
from omnibias.symbolic.boussinesq import (
    boussinesq_selfsimilar_residual,
    verify_boussinesq_bundle,
)
from omnibias.symbolic.causal import (
    causal_discovery_report,
    mutual_information_matrix,
    notears_acyclicity,
    notears_lite,
    term_parent_ranking,
)
from omnibias.symbolic.ccf import (
    assess_ccf_candidate,
    ccf_self_similar_line_residual,
    ccf_self_similar_residual,
    hardy_even_numpy,
    hardy_odd_numpy,
    hardy_profile_numpy,
    line_even_profile_jet,
    periodic_hilbert,
    recover_ccf_scaling_law,
    truncated_line_hilbert,
    verify_cap_bundle,
    verify_ccf_linearized_operator_bound,
    verify_ccf_residual,
    verify_ccf_selfsimilar_blowup_attempt,
)
from omnibias.symbolic.diagnostics import (
    DIVERGENCE_OBJECTIVES,
    chi_squared_to_gaussian,
    design_conditioning_report,
    differential_entropy,
    divergence_objective_term,
    feature_residual_mutual_information,
    gaussian_entropy,
    hellinger_to_gaussian,
    js_to_gaussian,
    kl_to_gaussian,
    renyi_to_gaussian,
    residual_dependence_report,
    residual_distribution_report,
    surrogate_residual_diagnostics,
    total_variation_to_gaussian,
    wasserstein2_to_gaussian,
    wasserstein_to_gaussian,
)
from omnibias.symbolic.dimensional import (
    DimensionalSystem,
    PiGroup,
    buckingham_pi_groups,
    dimension_matrix,
    dimensionless_residual,
    filter_dimensionless_monomials,
    integer_null_space,
    is_dimensionless,
    n_dimensionless_groups,
)
from omnibias.symbolic.discovery import (
    FeatureLibraryPlan,
    FractionalOrderDiscoveryResult,
    JetBundle,
    JetDiscoveryResult,
    LibrarySpec,
    NeuralField1D,
    NeuralJetDiscoverer,
    SparseEquation,
    SplitData,
    build_cdf_band_library,
    build_fourier_library,
    build_hybrid_library,
    build_information_library,
    build_jet_activation_fractional_features,
    build_jet_cdf_features,
    build_jet_fractional_features,
    build_jet_fractional_features_closed_form,
    build_jet_info_features,
    build_jet_integral_features,
    build_jet_piecewise_fractional_features,
    build_jet_relation_library,
    build_jet_spectral_fractional_features,
    build_pde_operator_library,
    build_taylor_library,
    default_surrogate_specs,
    discover_activation_identity,
    discover_fractional_order_law,
    discover_from_noisy_observations,
    discover_interpretable_surrogate,
    discover_pde_operator_law,
    evaluate_high_dim_sparse_validation,
    evaluate_poc,
    evaluate_real_world_tabular_validation,
    exact_activation_field_1d,
    extract_neural_jets,
    fit_cdf_band_library_plan,
    fit_information_library_plan,
    fit_jet_cdf_plan,
    fit_jet_info_plan,
    fit_neural_field_1d,
    fit_screened_feature_library_plan,
    fit_sparse_equation,
    gl_fractional_derivative,
    jet_name,
    mae,
    make_heat_equation_operator_data,
    make_high_dim_sparse_dataset,
    make_symbolic_regression_dataset,
    rmse,
    split_x_grid,
    symbolic_hidden_law,
    write_artifacts,
)
from omnibias.symbolic.discrete import (
    DifferenceJets,
    RecurrenceRelation,
    build_difference_relation_library,
    discover_recurrence,
    discover_recurrence_least_squares,
    extract_difference_jets,
    polynomial_from_samples,
    verify_binomial_recurrence,
)
from omnibias.symbolic.euler2d import (
    euler2d_grid_residuals,
    euler2d_radial_fields,
    verify_euler2d_steady_vortex,
)
from omnibias.symbolic.expressions import (
    RationalExpression,
    RecognizedExpression,
    fit_rational_expression,
    recognize_known_expression,
    validate_rational_expression,
)
from omnibias.symbolic.exterior_discovery import (
    DifferentialForm,
    closedness_residual,
    coclosedness_residual,
    codifferential,
    curl_form,
    differential_form,
    electromagnetic_field_2form,
    evaluate_exterior_calculus,
    exterior_derivative,
    gradient_form,
    hodge_laplacian,
    hodge_star,
    one_form,
    scalar_form,
    wedge,
)
from omnibias.symbolic.field_discovery import (
    FieldJet,
    FieldLawDiscoverer,
    FieldLawResult,
    NeuralFieldND,
    analytic_field_jet,
    build_field_relation_library,
    discover_field_pde_law,
    evaluate_field_pde_discovery,
    extract_field_jet,
    field_anisotropic_laplacian,
    field_curl,
    field_derivative_jet,
    field_divergence,
    field_grad_norm_sq,
    field_gradient,
    field_hessian,
    field_ito_generator,
    field_laplacian,
    field_operator_columns,
    field_partial_name,
    field_value,
    field_wirtinger,
    fit_neural_field_nd,
    make_burgers_field_split,
    make_heat2d_field_split,
    make_heat_field_split,
    make_laplace_field_split,
    make_wave_field_split,
    measure_integral_columns,
)
from omnibias.symbolic.fluid import (
    finite_difference_residual_sups,
    periodic_flow_residual_sups,
    regenerate_periodic_flow,
    streamfunction_residual_sups,
    verify_periodic_flow_residual,
    verify_rollout_diagnostics,
    verify_streamfunction_residual,
)
from omnibias.symbolic.geometry_discovery import (
    MetricField,
    analytic_metric_field,
    christoffel_symbols,
    covariant_hessian,
    discover_geometric_heat_law,
    evaluate_geometric_discovery,
    flat_metric_field,
    gaussian_curvature_2d,
    laplace_beltrami,
    make_geometric_heat_split,
    metric_determinant,
    metric_grad_norm_sq,
    metric_inverse,
    pullback_metric_field,
    ricci_tensor,
    riemann_tensor,
    scalar_curvature,
    warped_product_metric_field,
)
from omnibias.symbolic.ipm import (
    ipm_selfsimilar_residual,
    verify_ipm_bundle,
)
from omnibias.symbolic.latent import (
    LatentODEResult,
    LinearAutoencoder,
    MLPAutoencoder,
    discover_latent_ode,
    finite_difference_derivative,
    takens_embedding,
)
from omnibias.symbolic.navier_stokes import (
    CANDIDATE_SCHEMA_VERSION,
    assess_blowup_candidate,
    assess_navier_stokes_candidate,
    build_axisymmetric_candidate_bridge_artifacts,
    build_blowup_candidate_artifact,
    build_regularity_candidate_artifact,
    fit_regularity_growth_bound,
    fit_self_similar_blowup_rate,
    pressure_poisson_residual_periodic,
    primitive_residual_periodic,
    regularity_feature_vector,
    replay_candidate_artifact,
    run_regularity_search,
    verify_active_projector_error_certificate,
    verify_active_subspace_absorption_frontier_report,
    verify_active_subspace_closure_report,
    verify_active_subspace_completeness_theorem_attempt,
    verify_active_subspace_invariance_report,
    verify_active_subspace_tail_contraction_attempt,
    verify_active_tail_contraction_lift_certificate,
    verify_active_tail_lift_error_budget,
    verify_analytic_tail_error_certificate,
    verify_axisymmetric_interval_report,
    verify_axisymmetric_swirl_candidate_artifact,
    verify_blowup_closure_report,
    verify_clm_multizero_first_blowup,
    verify_finite_active_tail_contraction_diagnostic,
    verify_interval_jacobian_error_certificate,
    verify_nonlinear_tail_remainder_certificate,
    verify_ns_cap_bundle,
    verify_ns_proof_program_report,
    verify_ns_solve_or_falsify_report,
    verify_ns_theorem_ladder_report,
    verify_proof_obligation_bundle,
    verify_refined_axisymmetric_swirl_candidate_artifact,
    verify_regularity_inequality_report,
    verify_theorem_grade_closure_attempt,
    verify_theorem_verifier_bundle,
    verify_weighted_analytic_tail_norm_contract,
)
from omnibias.symbolic.piecewise import (
    HybridAutomaton,
    PiecewiseLaw,
    fit_learned_piecewise_ode,
    fit_piecewise_law,
    fit_piecewise_ode_law,
    global_sparse_law,
    polynomial_value_library,
    polynomial_vector_library,
)
from omnibias.symbolic.selection import (
    CRITERIA,
    KFoldSelection,
    aic,
    aicc,
    bic,
    equation_information_criterion,
    gaussian_log_likelihood,
    information_criterion,
    kfold_select,
    mdl,
    stability_selection,
)
from omnibias.symbolic.sqg import (
    sqg_grad_theta_sup_sample,
    sqg_grid_residuals,
    sqg_radial_fields,
    sqg_selfsimilar_l2_quantities,
    verify_sqg_linearized_coercivity_attempt,
    verify_sqg_selfsimilar_blowup_attempt,
    verify_sqg_steady_vortex,
)
from omnibias.symbolic.uncertainty import (
    attach_uncertainty,
    bootstrap_coefficients,
    certified_coefficient_intervals,
    ridge_coefficient_covariance,
)

try:
    __version__ = _pkg_version("omnibias-symbolic")
except _PkgNotFound:  # pragma: no cover - bare source checkout
    __version__ = "0.0.0+unknown"

# Founding-idea lineage (see docs/theory.md "Two senses of collapse").
__lineage__ = "bias collapse"

__all__ = [
    "BlasiusSolution",
    "CANDIDATE_SCHEMA_VERSION",
    "CRITERIA",
    "DIVERGENCE_OBJECTIVES",
    "DifferenceJets",
    "DifferentialForm",
    "DimensionalSystem",
    "FeatureLibraryPlan",
    "FieldJet",
    "FieldLawDiscoverer",
    "FieldLawResult",
    "FractionalOrderDiscoveryResult",
    "GaugeLawDiscoverer",
    "GaugeLawResult",
    "HybridAutomaton",
    "JetBundle",
    "JetDiscoveryResult",
    "KFoldSelection",
    "LatentODEResult",
    "LibrarySpec",
    "LinearAutoencoder",
    "MLPAutoencoder",
    "MetricField",
    "NeuralField1D",
    "NeuralFieldND",
    "NeuralJetDiscoverer",
    "PiGroup",
    "PiecewiseLaw",
    "RationalExpression",
    "RecognizedExpression",
    "RecurrenceRelation",
    "SparseEquation",
    "SplitData",
    "__lineage__",
    "__version__",
    "aic",
    "aicc",
    "analytic_field_jet",
    "analytic_metric_field",
    "assess_blowup_candidate",
    "assess_ccf_candidate",
    "assess_navier_stokes_candidate",
    "attach_uncertainty",
    "bic",
    "bootstrap_coefficients",
    "boussinesq_selfsimilar_residual",
    "buckingham_pi_groups",
    "build_axisymmetric_candidate_bridge_artifacts",
    "build_blowup_candidate_artifact",
    "build_cdf_band_library",
    "build_difference_relation_library",
    "build_field_relation_library",
    "build_fourier_library",
    "build_hybrid_library",
    "build_information_library",
    "build_jet_activation_fractional_features",
    "build_jet_cdf_features",
    "build_jet_fractional_features",
    "build_jet_fractional_features_closed_form",
    "build_jet_info_features",
    "build_jet_integral_features",
    "build_jet_piecewise_fractional_features",
    "build_jet_relation_library",
    "build_jet_spectral_fractional_features",
    "build_pde_operator_library",
    "build_regularity_candidate_artifact",
    "build_taylor_library",
    "causal_discovery_report",
    "ccf_self_similar_line_residual",
    "ccf_self_similar_residual",
    "certified_coefficient_intervals",
    "chi_squared_to_gaussian",
    "christoffel_symbols",
    "closedness_residual",
    "coclosedness_residual",
    "codifferential",
    "covariant_hessian",
    "curl_form",
    "default_surrogate_specs",
    "design_conditioning_report",
    "differential_entropy",
    "differential_form",
    "dimension_matrix",
    "dimensionless_residual",
    "discover_activation_identity",
    "discover_blasius_explicit_expression",
    "discover_blasius_from_neural_surrogate",
    "discover_blasius_identity",
    "discover_blasius_taylor_pade_expression",
    "discover_field_pde_law",
    "discover_fractional_order_law",
    "discover_from_noisy_observations",
    "discover_geometric_heat_law",
    "discover_interpretable_surrogate",
    "discover_latent_ode",
    "discover_pde_operator_law",
    "discover_recurrence",
    "discover_recurrence_least_squares",
    "discover_yang_mills_singlet_law",
    "divergence_objective_term",
    "electromagnetic_field_2form",
    "equation_information_criterion",
    "euler2d_grid_residuals",
    "euler2d_radial_fields",
    "evaluate_blasius",
    "evaluate_exterior_calculus",
    "evaluate_field_pde_discovery",
    "evaluate_geometric_discovery",
    "evaluate_high_dim_sparse_validation",
    "evaluate_poc",
    "evaluate_real_world_tabular_validation",
    "exact_activation_field_1d",
    "exterior_derivative",
    "extract_difference_jets",
    "extract_field_jet",
    "extract_neural_jets",
    "feature_residual_mutual_information",
    "field_anisotropic_laplacian",
    "field_curl",
    "field_derivative_jet",
    "field_divergence",
    "field_grad_norm_sq",
    "field_gradient",
    "field_hessian",
    "field_ito_generator",
    "field_laplacian",
    "field_operator_columns",
    "field_partial_name",
    "field_value",
    "field_wirtinger",
    "filter_dimensionless_monomials",
    "finite_difference_derivative",
    "finite_difference_residual_sups",
    "fit_cdf_band_library_plan",
    "fit_information_library_plan",
    "fit_jet_cdf_plan",
    "fit_jet_info_plan",
    "fit_learned_piecewise_ode",
    "fit_neural_field_1d",
    "fit_neural_field_nd",
    "fit_piecewise_law",
    "fit_piecewise_ode_law",
    "fit_rational_expression",
    "fit_regularity_growth_bound",
    "fit_screened_feature_library_plan",
    "fit_self_similar_blowup_rate",
    "fit_sparse_equation",
    "flat_metric_field",
    "gaussian_curvature_2d",
    "gaussian_entropy",
    "gaussian_log_likelihood",
    "gl_fractional_derivative",
    "global_sparse_law",
    "gradient_form",
    "hardy_even_numpy",
    "hardy_odd_numpy",
    "hardy_profile_numpy",
    "hellinger_to_gaussian",
    "hodge_laplacian",
    "hodge_star",
    "information_criterion",
    "integer_null_space",
    "ipm_selfsimilar_residual",
    "is_dimensionless",
    "jet_name",
    "js_to_gaussian",
    "kfold_select",
    "kl_to_gaussian",
    "laplace_beltrami",
    "line_even_profile_jet",
    "mae",
    "make_burgers_field_split",
    "make_geometric_heat_split",
    "make_heat2d_field_split",
    "make_heat_equation_operator_data",
    "make_heat_field_split",
    "make_high_dim_sparse_dataset",
    "make_laplace_field_split",
    "make_symbolic_regression_dataset",
    "make_wave_field_split",
    "make_yang_mills_bpst_split",
    "make_yang_mills_polynomial_split",
    "mdl",
    "measure_integral_columns",
    "metric_determinant",
    "metric_grad_norm_sq",
    "metric_inverse",
    "mutual_information_matrix",
    "n_dimensionless_groups",
    "notears_acyclicity",
    "notears_lite",
    "one_form",
    "periodic_flow_residual_sups",
    "periodic_hilbert",
    "polynomial_from_samples",
    "polynomial_value_library",
    "polynomial_vector_library",
    "pressure_poisson_residual_periodic",
    "primitive_residual_periodic",
    "pullback_metric_field",
    "recognize_known_expression",
    "recover_ccf_scaling_law",
    "regenerate_periodic_flow",
    "regularity_feature_vector",
    "renyi_to_gaussian",
    "replay_candidate_artifact",
    "residual_dependence_report",
    "residual_distribution_report",
    "ricci_tensor",
    "ridge_coefficient_covariance",
    "riemann_tensor",
    "rmse",
    "run_regularity_search",
    "scalar_curvature",
    "scalar_form",
    "solve_blasius",
    "split_x_grid",
    "sqg_grad_theta_sup_sample",
    "sqg_grid_residuals",
    "sqg_radial_fields",
    "sqg_selfsimilar_l2_quantities",
    "stability_selection",
    "streamfunction_residual_sups",
    "surrogate_residual_diagnostics",
    "symbolic_hidden_law",
    "takens_embedding",
    "term_parent_ranking",
    "total_variation_to_gaussian",
    "truncated_line_hilbert",
    "validate_rational_expression",
    "verify_active_projector_error_certificate",
    "verify_active_subspace_absorption_frontier_report",
    "verify_active_subspace_closure_report",
    "verify_active_subspace_completeness_theorem_attempt",
    "verify_active_subspace_invariance_report",
    "verify_active_subspace_tail_contraction_attempt",
    "verify_active_tail_contraction_lift_certificate",
    "verify_active_tail_lift_error_budget",
    "verify_analytic_tail_error_certificate",
    "verify_axisymmetric_interval_report",
    "verify_axisymmetric_swirl_candidate_artifact",
    "verify_binomial_recurrence",
    "verify_blowup_closure_report",
    "verify_boussinesq_bundle",
    "verify_cap_bundle",
    "verify_ccf_linearized_operator_bound",
    "verify_ccf_residual",
    "verify_ccf_selfsimilar_blowup_attempt",
    "verify_clm_multizero_first_blowup",
    "verify_euler2d_steady_vortex",
    "verify_finite_active_tail_contraction_diagnostic",
    "verify_interval_jacobian_error_certificate",
    "verify_ipm_bundle",
    "verify_nonlinear_tail_remainder_certificate",
    "verify_ns_cap_bundle",
    "verify_ns_proof_program_report",
    "verify_ns_solve_or_falsify_report",
    "verify_ns_theorem_ladder_report",
    "verify_periodic_flow_residual",
    "verify_proof_obligation_bundle",
    "verify_refined_axisymmetric_swirl_candidate_artifact",
    "verify_regularity_inequality_report",
    "verify_rollout_diagnostics",
    "verify_sqg_linearized_coercivity_attempt",
    "verify_sqg_selfsimilar_blowup_attempt",
    "verify_sqg_steady_vortex",
    "verify_streamfunction_residual",
    "verify_theorem_grade_closure_attempt",
    "verify_theorem_verifier_bundle",
    "verify_weighted_analytic_tail_norm_contract",
    "warped_product_metric_field",
    "wasserstein2_to_gaussian",
    "wasserstein_to_gaussian",
    "wedge",
    "write_artifacts",
    "write_blasius_artifacts",
]

_GAUGE_EXPORTS = frozenset(
    {
        "GaugeLawDiscoverer",
        "GaugeLawResult",
        "discover_yang_mills_singlet_law",
        "make_yang_mills_bpst_split",
        "make_yang_mills_polynomial_split",
    }
)


def __getattr__(name: str) -> object:
    if name in _GAUGE_EXPORTS:
        from omnibias.symbolic import gauge_discovery as _gauge_discovery

        return getattr(_gauge_discovery, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

