# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Pack-parameter Fisher metric (theory 04-01).

Public leftover surface. Distinct from
:func:`omnibias.curvature.glm_fisher.fisher_information_metric`.
"""

from __future__ import annotations

from omnibias.curvature.information._core import (
    DEGENERACY_ABS_FLOOR,
    PATH_CLOSED,
    PATH_MC,
    PINV_RCOND_RULE,
    DegeneracyReport,
    FisherEvaluation,
    NotADensityError,
    PackFamily,
    as_manifold_spec,
    collapse_degeneracy,
    damped_natural_step,
    distinguishability_samples,
    empirical_distinguishability_n,
    evaluate_fisher,
    finite_difference_family,
    fisher_delta_delta,
    fisher_distance,
    fisher_metric,
    fisher_metric_mc,
    fisher_pinv,
    honesty_payload,
    log_density,
    logistic_location_family,
    logistic_mixture_family,
    mean_nll,
    nll_gradient,
    pinv_rcond,
    randomized_mixture_suite,
    sample_family,
    two_bias_A,
    two_bias_ddelta_u,
    two_bias_density_naive,
    two_bias_density_u,
    two_bias_dx_u,
    two_bias_family,
    two_bias_located_family,
    undamped_natural_step,
    worked_example,
)

__all__ = [
    "DEGENERACY_ABS_FLOOR",
    "DegeneracyReport",
    "FisherEvaluation",
    "NotADensityError",
    "PATH_CLOSED",
    "PATH_MC",
    "PINV_RCOND_RULE",
    "PackFamily",
    "as_manifold_spec",
    "collapse_degeneracy",
    "damped_natural_step",
    "distinguishability_samples",
    "empirical_distinguishability_n",
    "evaluate_fisher",
    "finite_difference_family",
    "fisher_delta_delta",
    "fisher_distance",
    "fisher_metric",
    "fisher_metric_mc",
    "fisher_pinv",
    "honesty_payload",
    "log_density",
    "logistic_location_family",
    "logistic_mixture_family",
    "mean_nll",
    "nll_gradient",
    "pinv_rcond",
    "randomized_mixture_suite",
    "sample_family",
    "two_bias_A",
    "two_bias_ddelta_u",
    "two_bias_density_naive",
    "two_bias_density_u",
    "two_bias_dx_u",
    "two_bias_family",
    "two_bias_located_family",
    "undamped_natural_step",
    "worked_example",
]
