# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Exact, backend-agnostic Boolean math (pure Python: no torch / jax / numpy).

This is the ground-truth layer for :mod:`omnibias.boolean`: truth tables, the
ANF/Reed-Muller transform, Walsh/Fourier analysis, Boolean differential calculus,
reproductive Boolean equation solving, and the multilinear extension that bridges
to the differentiable backends.
"""

from __future__ import annotations

from omnibias.boolean._core.anf import (
    algebraic_degree,
    anf_from_truth_table,
    anf_monomials,
    anf_to_string,
    truth_table_from_anf,
)
from omnibias.boolean._core.derivative import (
    BooleanAntiderivative,
    boolean_derivative,
    boolean_derivative_reduced,
    boolean_derivative_set,
    boolean_integral,
    is_independent_of,
    reduced_index,
    restrict,
)
from omnibias.boolean._core.equations import (
    BooleanSolution,
    GeneralSolution,
    constraint_from_predicate,
    eliminant,
    equation_from_callables,
    is_satisfiable,
    solution_set,
    solve_for,
    solve_system,
    system_constraint,
)
from omnibias.boolean._core.multilinear import (
    anf_from_multilinear_coeffs,
    mixed_partial,
    multilinear_coeffs,
    multilinear_eval,
    multilinear_eval_from_coeffs,
    values_from_multilinear_coeffs,
)
from omnibias.boolean._core.systems import (
    GF2Solution,
    constraints_are_linear,
    gf2_solve,
    linear_system_rows,
    verify_assignment,
)
from omnibias.boolean._core.truth_table import (
    TruthTable,
    all_assignments,
    assignment,
    bit_to_spin,
    check_truth_table,
    index_of,
    num_vars,
    pm1_values,
    spin_to_bit,
    truth_table_from_callable,
    truth_table_to_callable,
)
from omnibias.boolean._core.verified import (
    absolute_indicator_iv,
    autocorrelation_iv,
    differential_bias_iv,
    fourier_coeffs_iv,
    linear_bias_iv,
    linearity_iv,
    max_linear_bias_iv,
    mobius_iv,
    nonlinearity_iv,
    parseval_defect_iv,
    walsh_at_iv,
    walsh_hadamard_iv,
    walsh_spectrum_iv,
)
from omnibias.boolean._core.walsh import (
    fourier_coeffs,
    fourier_influences,
    influences,
    parseval_defect,
    total_influence,
    walsh_hadamard,
    walsh_spectrum,
)

__all__ = [
    "BooleanAntiderivative",
    "BooleanSolution",
    "GF2Solution",
    "GeneralSolution",
    "TruthTable",
    "absolute_indicator_iv",
    "algebraic_degree",
    "all_assignments",
    "anf_from_multilinear_coeffs",
    "anf_from_truth_table",
    "anf_monomials",
    "anf_to_string",
    "assignment",
    "autocorrelation_iv",
    "bit_to_spin",
    "boolean_derivative",
    "boolean_derivative_reduced",
    "boolean_derivative_set",
    "boolean_integral",
    "check_truth_table",
    "constraint_from_predicate",
    "constraints_are_linear",
    "differential_bias_iv",
    "eliminant",
    "equation_from_callables",
    "fourier_coeffs",
    "fourier_coeffs_iv",
    "fourier_influences",
    "gf2_solve",
    "index_of",
    "influences",
    "is_independent_of",
    "is_satisfiable",
    "linear_bias_iv",
    "linear_system_rows",
    "linearity_iv",
    "max_linear_bias_iv",
    "mixed_partial",
    "mobius_iv",
    "multilinear_coeffs",
    "multilinear_eval",
    "multilinear_eval_from_coeffs",
    "nonlinearity_iv",
    "num_vars",
    "parseval_defect",
    "parseval_defect_iv",
    "pm1_values",
    "reduced_index",
    "restrict",
    "solution_set",
    "solve_for",
    "solve_system",
    "spin_to_bit",
    "system_constraint",
    "total_influence",
    "truth_table_from_anf",
    "truth_table_from_callable",
    "truth_table_to_callable",
    "values_from_multilinear_coeffs",
    "verify_assignment",
    "walsh_at_iv",
    "walsh_hadamard",
    "walsh_hadamard_iv",
    "walsh_spectrum",
    "walsh_spectrum_iv",
]
