# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-omnibias-Commercial
"""Regression tests for the Bautin (focal-value ideal) engine.

Includes a literature-replay cross-check: Bautin's normalized quadratic
weak-focus family is classically known to have its focal-value ideal
generated by exactly three quantities (Bautin, 1954; see also the survey by
Artes, Llibre & Vulpe). This module never asserts that closed-form result
from memory -- :func:`~omnibias.dynamics.focal.lyapunov_quantities` computes
``V_1, V_2, V_3`` fresh from the declared normal form, and an independent
``sympy`` Groebner-basis computation of those same three polynomials is used
as a cross-oracle for the basis length.
"""

from __future__ import annotations

import sympy as sp
from omnibias.dynamics.bautin import (
    BautinBasis,
    bautin_basis,
    bautin_quadratic_family,
    center_membership,
    certify_bautin_membership,
    nonzero_focus_example,
    verify_bautin_membership,
    verify_bautin_stabilization,
)
from omnibias.dynamics.focal import LyapunovQuantities, lyapunov_quantities
from omnibias.holonomic._core.groebner import verify_ideal_membership
from omnibias.holonomic._core.poly_n import PolyN


def _polyn_to_sympy(poly: PolyN, symbols: tuple[sp.Symbol, ...]) -> sp.Expr:
    expr = sp.Integer(0)
    for mon, c in poly.terms.items():
        term = sp.Rational(c.numerator, c.denominator)
        for exponent, sym in zip(mon, symbols, strict=True):
            term *= sym**exponent
        expr += term
    return sp.expand(expr)


def test_bautin_quadratic_family_has_basis_length_three_via_sympy_cross_oracle() -> None:
    p, q = bautin_quadratic_family()
    quantities = lyapunov_quantities(p, q, order=8)
    assert [degree for degree, _ in quantities.quantities] == [4, 6, 8]
    basis = bautin_basis(quantities)
    assert basis.basis_length == 3
    assert basis.cyclicity_bound == 2
    assert basis.bautin_ideal_stabilization_proved is False

    a2, a3, a4, a5, a6 = sp.symbols("a2 a3 a4 a5 a6")
    generators = [_polyn_to_sympy(value, (a2, a3, a4, a5, a6)) for _, value in quantities.quantities]
    sympy_basis = sp.groebner(generators, a2, a3, a4, a5, a6, order="grevlex")
    assert len(sympy_basis.polys) == 3


def test_verify_bautin_stabilization_checks_higher_orders() -> None:
    p, q = bautin_quadratic_family()
    quantities = lyapunov_quantities(p, q, order=10)
    basis = verify_bautin_stabilization(quantities, reference_count=3)
    assert basis.finite_order_stabilization_verified is True
    assert basis.bautin_ideal_stabilization_proved is False
    assert basis.bautin_stabilization_verified_to_order == 10


def test_verify_bautin_stabilization_refuses_without_higher_values() -> None:
    p, q = bautin_quadratic_family()
    quantities = lyapunov_quantities(p, q, order=8)
    basis = verify_bautin_stabilization(quantities, reference_count=3)
    assert basis.finite_order_stabilization_verified is False
    assert basis.bautin_ideal_stabilization_proved is False
    assert basis.bautin_stabilization_verified_to_order == 8


def test_verify_bautin_stabilization_stops_on_non_member() -> None:
    p, q = bautin_quadratic_family()
    quantities = lyapunov_quantities(p, q, order=10)
    junk = PolyN.var(5, 0)
    polluted = LyapunovQuantities(
        quantities.param_nvars,
        quantities.order,
        quantities.quantities + ((12, junk),),
        quantities.normal_form,
    )
    basis = verify_bautin_stabilization(polluted, reference_count=3)
    assert basis.finite_order_stabilization_verified is False
    assert basis.bautin_ideal_stabilization_proved is False
    assert basis.bautin_stabilization_verified_to_order == 10


def test_bautin_basis_requires_a_symbolic_parameter() -> None:
    p, q = nonzero_focus_example()
    numeric_quantities = lyapunov_quantities(p, q, order=4)
    assert numeric_quantities.param_nvars == 0
    try:
        bautin_basis(numeric_quantities)
    except ValueError as exc:
        assert "symbolic parameter" in str(exc)
    else:
        raise AssertionError("bautin_basis must refuse a purely numeric field")


def test_bautin_basis_is_a_frozen_dataclass_with_expected_shape() -> None:
    p, q = bautin_quadratic_family()
    quantities = lyapunov_quantities(p, q, order=6)
    basis = bautin_basis(quantities)
    assert isinstance(basis, BautinBasis)
    assert len(basis.generators) == 2
    assert basis.monomial_order == "degrevlex"
    assert basis.basis_length == len(basis.basis)
    assert basis.cyclicity_bound == basis.basis_length - 1


def test_center_membership_ideal_and_radical_witnesses_replay() -> None:
    nvars = 2
    a, b = PolyN.var(nvars, 0), PolyN.var(nvars, 1)
    generators = [a - b]
    candidate = a * a - b * b
    membership = center_membership(candidate, generators, radical=False)
    assert membership.is_member
    assert verify_ideal_membership(candidate, generators, membership)

    squared_generators = [(a - b) * (a - b)]
    not_in_ideal = center_membership(a - b, squared_generators, radical=False)
    assert not not_in_ideal.is_member
    in_radical = center_membership(a - b, squared_generators, radical=True)
    assert in_radical.is_member


def test_bautin_membership_certificate_replays() -> None:
    nvars = 2
    a, b = PolyN.var(nvars, 0), PolyN.var(nvars, 1)
    generators = [a - b]
    candidate = a * a - b * b
    certificate = certify_bautin_membership(candidate, generators, radical=False)
    assert verify_bautin_membership(certificate)


def test_lyapunov_quantities_dataclass_carries_param_nvars() -> None:
    p, q = bautin_quadratic_family()
    quantities = lyapunov_quantities(p, q, order=4)
    assert isinstance(quantities, LyapunovQuantities)
    assert quantities.param_nvars == 5
    assert quantities.order == 4
