[mypy]
python_version = 3.10
strict = true
namespace_packages = true
explicit_package_bases = true
mypy_path = packages/omnibias-core/src,packages/omnibias-torch/src,packages/omnibias-jax/src
exclude = (?x)(^tests/|/tests/|^build/|^dist/)

[mypy-torch.*,jax.*,jaxlib.*,folx.*]
ignore_missing_imports = True
