# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Torch gauge-theory operator surface."""

from __future__ import annotations

from omnibias.geometry.gauge.torch.ops.action import (
    action_density,
    anti_self_dual_projector,
    anti_self_duality_defect,
    self_dual_projector,
    self_duality_defect,
    yang_mills_action,
)
from omnibias.geometry.gauge.torch.ops.algebra import (
    bracket,
    from_matrix,
    generators,
    structure_constants,
    symmetric_constants,
    to_matrix,
    trace_product,
)
from omnibias.geometry.gauge.torch.ops.connection import (
    bianchi,
    bianchi_from_arrays,
    connection_partials,
    connection_second_partials,
    connection_value,
    covariant_derivative_field_strength,
    covariant_derivative_field_strength_from_arrays,
    covariant_divergence,
    covariant_divergence_from_arrays,
    field_strength,
    field_strength_from_arrays,
    gauge_covariant_derivative,
    gauge_flow_rhs,
    gauge_flow_rhs_from_arrays,
    langevin_step,
)
from omnibias.geometry.gauge.torch.ops.gauge import (
    gauge_invariance_defect,
    gauge_variation_field_strength,
    global_gauge_transform,
    infinitesimal_gauge_variation,
)
from omnibias.geometry.gauge.torch.ops.hodge import (
    dual_field_strength,
    hodge_star_flat,
    levi_civita,
    signature_diagonal,
)
from omnibias.geometry.gauge.torch.ops.nonintegrable import (
    covariant_derivative_commutator,
    covariant_derivative_commutator_from_arrays,
    curvature_commutator_defect,
    curvature_commutator_defect_from_arrays,
    parallel_transport,
    parallel_transport_from_arrays,
    transport_nodes,
    wilson_loop,
)
from omnibias.geometry.gauge.torch.ops.representation import (
    adjoint_generators,
    antisymmetric_power_generators,
    casimir_eigenvalue,
    casimir_operator,
    dynkin_index_value,
    spin_matrices,
    symmetric_power_generators,
)
from omnibias.geometry.gauge.torch.ops.topology import (
    euler_number_so2,
    first_chern_class,
    first_chern_number,
    is_quantized,
    pontryagin_density,
    pontryagin_number,
    second_chern_number,
    topological_charge,
    topological_charge_density,
)

__all__ = [
    "action_density",
    "adjoint_generators",
    "anti_self_dual_projector",
    "anti_self_duality_defect",
    "antisymmetric_power_generators",
    "bianchi",
    "bianchi_from_arrays",
    "bracket",
    "casimir_eigenvalue",
    "casimir_operator",
    "connection_partials",
    "connection_second_partials",
    "connection_value",
    "covariant_derivative_commutator",
    "covariant_derivative_commutator_from_arrays",
    "covariant_derivative_field_strength",
    "covariant_derivative_field_strength_from_arrays",
    "covariant_divergence",
    "covariant_divergence_from_arrays",
    "curvature_commutator_defect",
    "curvature_commutator_defect_from_arrays",
    "dual_field_strength",
    "dynkin_index_value",
    "euler_number_so2",
    "field_strength",
    "field_strength_from_arrays",
    "first_chern_class",
    "first_chern_number",
    "from_matrix",
    "gauge_covariant_derivative",
    "gauge_flow_rhs",
    "gauge_flow_rhs_from_arrays",
    "gauge_invariance_defect",
    "gauge_variation_field_strength",
    "generators",
    "global_gauge_transform",
    "hodge_star_flat",
    "infinitesimal_gauge_variation",
    "is_quantized",
    "langevin_step",
    "levi_civita",
    "parallel_transport",
    "parallel_transport_from_arrays",
    "pontryagin_density",
    "pontryagin_number",
    "second_chern_number",
    "self_dual_projector",
    "self_duality_defect",
    "signature_diagonal",
    "spin_matrices",
    "structure_constants",
    "symmetric_constants",
    "symmetric_power_generators",
    "to_matrix",
    "topological_charge",
    "topological_charge_density",
    "trace_product",
    "transport_nodes",
    "wilson_loop",
]
