# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
r"""Verified (interval / Taylor-model) arithmetic backend for omnibias.

This subpackage lifts omnibias's *bit-stable* closed-form derivative tower into a
*rigorous* one: every quantity is returned as a guaranteed
:class:`~omnibias.core.verified.interval.Interval` enclosure produced by outward
directed rounding.  It is the dependency-free substrate the certified-evidence stack
needs to replace float64 padding with theorem-grade bounds.

Layers
------
* :mod:`~omnibias.core.verified.interval` -- rigorous interval arithmetic.
* :mod:`~omnibias.core.verified.transcend` -- guaranteed ``exp``/``tanh``/``sigmoid``
  enclosures (``mpmath`` when present, else ulp-inflated libm).
* :mod:`~omnibias.core.verified.coeffs` -- exact-integer tower coefficients +
  interval Horner.
* :mod:`~omnibias.core.verified.sigma` -- rigorous ``sigma^(k)`` tower enclosure.
* :mod:`~omnibias.core.verified.jet` -- verified directional jets.
* :mod:`~omnibias.core.verified.taylor_model` -- Taylor models (interval
  polynomial + rigorous remainder) for enclosing functions over a whole cell.
* :mod:`~omnibias.core.verified.taylor_model_mv` -- the multivariate
  generalisation: total-degree Taylor models over a box in ``R^n``.

``mpmath`` is an optional accelerator (``pip install omnibias-core[verified]``);
the package imports and runs without it.
"""

from __future__ import annotations

from omnibias.core.verified.affine import (
    AffineForm,
    from_intervals,
    new_noise_symbol,
)
from omnibias.core.verified.coeffs import (
    bernoulli_number_exact,
    bernoulli_polynomial_exact,
    euler_number_exact,
    generalized_bernoulli_exact,
    hermite_coeffs_exact,
    horner_interval,
    sech_poly_coeffs_exact,
    sigmoid_poly_coeffs_exact,
    tanh_poly_coeffs_exact,
)
from omnibias.core.verified.complex_interval import ComplexInterval, ComplexLike
from omnibias.core.verified.conditioning import (
    certified_condition_number,
    certified_damping,
    certified_max_eigenvalue,
    certified_min_eigenvalue,
    certified_regularization_error,
    conditioning_certificate,
    positive_definite_pivots_certificate,
)
from omnibias.core.verified.dirichlet import (
    certified_dirichlet_series,
    complex_exp,
    dirichlet_beta_odd,
    dirichlet_l_negative_integer,
    l_function_enclosure,
    n_power_neg_s,
    p_series_tail_bound,
    theta_enclosure,
    zeta_enclosure,
    zeta_euler_maclaurin,
    zeta_even,
    zeta_negative_odd,
)
from omnibias.core.verified.eig import (
    BlockOperatorGapCertificate,
    PerronGapCertificate,
    SymmetricGapCertificate,
    birkhoff_contraction_ratio,
    birkhoff_projective_diameter,
    certified_block_operator_gap,
    certified_perron_spectral_gap,
    certified_symmetric_spectral_gap,
    collatz_wielandt_perron_bounds,
    rayleigh_quotient,
    symmetric_eigenvalue_residual_enclosure,
)
from omnibias.core.verified.eig_operator import (
    EigenvalueLowerBound,
    Inertia,
    LehmannCertificate,
    SpectralGapCertificate,
    certified_spectral_gap,
    count_eigenvalues_below,
    generalized_eigenvalue_enclosure,
    interval_ldlt_inertia,
    interval_ldlt_pivots,
    is_positive_definite,
    lehmann_maehly_lower_bounds,
    operator_comparison_bounds,
    ritz_upper_bound,
    temple_lower_bound,
    temple_lower_bound_vector,
)
from omnibias.core.verified.euler_maclaurin import (
    digamma_iv,
    euler_maclaurin_sum,
    log_gamma_iv,
)
from omnibias.core.verified.fourier import (
    Symbol,
    ValidatedFourierSeries,
    Wavevector,
    leray_symbol,
    riesz_symbol,
)
from omnibias.core.verified.ftc import (
    certified_ftc_residual,
    ftc_certificate,
)
from omnibias.core.verified.hurwitz import (
    hurwitz_zeta,
    hurwitz_zeta_negative_integer,
)
from omnibias.core.verified.information import (
    binned_distribution_enclosure,
    chi_squared_enclosure,
    cross_entropy_enclosure,
    entropy_enclosure,
    hellinger_enclosure,
    js_divergence_enclosure,
    kl_divergence_enclosure,
    mutual_information_enclosure,
    total_variation_enclosure,
)
from omnibias.core.verified.interval import Interval, IntervalLike, hull, sum_intervals
from omnibias.core.verified.jet import (
    affine_jet,
    antiderivative_jet,
    compose_jet,
    derivative_jet,
    jet_to_tower,
    layer_jet,
    lhopital_ratio_iv,
    mlp_jet,
    path_jet,
    series_mul,
    tower_to_jet,
)
from omnibias.core.verified.jet_mv import (
    MVJet,
    certified_partials,
    certified_partials_subdivided,
    certified_residual_bound,
    compose_jet_mv,
    identity_jet,
    jet_gradient,
    jet_hessian,
    jet_laplacian,
    jet_multiply,
    jet_partials,
    layer_jet_mv,
    mlp_jet_mv,
)
from omnibias.core.verified.kantorovich import (
    KrawczykCertificate,
    NKBounds,
    RadiiCertificate,
    certify_zero_radii,
    krawczyk_certificate,
    krawczyk_search,
    newton_kantorovich_bounds,
    radii_polynomial_certificate,
)
from omnibias.core.verified.linalg import (
    inf_norm_matrix,
    inf_norm_vector,
    matvec,
    neumann_inverse_norm_bound,
)
from omnibias.core.verified.line import (
    conjugate_poisson,
    conjugate_poisson_deriv,
    conjugate_poisson_deriv_matrix,
    conjugate_poisson_matrix,
    even_profile,
    even_profile_deriv,
    even_profile_tail_constant,
    hilbert_even_profile,
    hilbert_even_profile_deriv,
    hilbert_of_conjugate,
    hilbert_of_poisson,
    hilbert_tail_bound,
    poisson_kernel,
    poisson_kernel_deriv,
    poisson_matrix,
    poisson_primitive,
    poisson_primitive_matrix,
)
from omnibias.core.verified.hardy_line import (
    hardy_angle,
    hardy_even,
    hardy_even_dalpha,
    hardy_even_deriv,
    hardy_even_deriv_matrix,
    hardy_even_matrix,
    hardy_even_profile,
    hardy_even_profile_deriv,
    hardy_odd,
    hardy_odd_dalpha,
    hardy_odd_deriv,
    hardy_odd_deriv_matrix,
    hardy_odd_matrix,
    hardy_pair,
    hardy_radius,
    hardy_tail_constant,
    hilbert_hardy_even_profile,
    hilbert_hardy_even_profile_deriv,
    hilbert_of_hardy_even,
    hilbert_of_hardy_odd,
)
from omnibias.core.verified.lohner import (
    JacobianEnclosure,
    LohnerSet,
    constant_jacobian,
    interval_matrix_exp,
    linear_field,
    lohner_flow,
    lohner_step,
    naive_interval_flow,
    qr_gram_schmidt,
)
from omnibias.core.verified.ode import TaylorSeries, VectorField, integrate_ivp
from omnibias.core.verified.pde_certificate import (
    BoundaryFace,
    Coeff,
    LinearPDE,
    PINNErrorCertificate,
    advection_diffusion,
    aposteriori_error_certificate,
    certified_boundary_residual,
    certified_interior_residual,
    helmholtz,
    laplace,
    poisson,
    radii_polynomial_residual_certificate,
    screened_poisson,
    spectral_residual_norm,
)
from omnibias.core.verified.polylog import (
    lerch_transcendent,
    polylog_enclosure,
)
from omnibias.core.verified.probability import (
    SUPPORTED_CDFS,
    CertifiedGoFResult,
    band_mass_enclosure,
    cdf_enclosure,
    certified_gof,
    empirical_cdf,
)
from omnibias.core.verified.quadrature import (
    GAUSS_LEGENDRE_MAX_N,
    DerivOracle,
    IntervalFn,
    QuadEstimate,
    clenshaw_curtis_integral,
    euler_maclaurin_quadrature,
    gauss_legendre_integral,
    gauss_legendre_nodes,
    midpoint_integral,
    romberg_integral,
    simpson_integral,
    tanh_sinh_estimate,
    trapezoid_integral,
    trapezoid_sum,
)
from omnibias.core.verified.radii_spectral import (
    Bilinear,
    SpectralProblem,
    SpectralRadiiResult,
    evaluate_residual,
    laplacian_symbol,
    laplacian_tail_inverse_bound,
    quadratic_radii_certificate,
)
from omnibias.core.verified.riesz import (
    blob,
    blob_gradient,
    leray_blob_field,
    leray_divergence_residual,
    newtonian_potential,
    potential_gradient,
    riesz_double_blob,
    riesz_tail_bound,
)
from omnibias.core.verified.rootfind import (
    bisection_bracket,
    certified_sign_change,
    interval_newton,
)
from omnibias.core.verified.sequence_space import (
    ValidatedSeries,
    convolve,
    ell1_nu_norm,
    fourier_nu_norm,
    geometric_tail_bound,
)
from omnibias.core.verified.series import (
    certified_geometric_series_sum,
    certified_ratio_series_sum,
    geometric_series_closed_form,
    geometric_tail_enclosure,
)
from omnibias.core.verified.sigma import sigma_tower_interval, sigma_value_interval
from omnibias.core.verified.spectral import (
    cos_matrix,
    hilbert_circulant,
    sin_matrix,
    uniform_nodes,
)
from omnibias.core.verified.sqg import (
    sqg_blob,
    sqg_blob_gradient,
    sqg_blob_l2_inner,
    sqg_riesz,
    sqg_stream,
    sqg_stream_gradient,
    sqg_velocity,
    sqg_velocity_divergence_residual,
)
from omnibias.core.verified.taylor_model import TaylorModel
from omnibias.core.verified.taylor_model_mv import TaylorModelMV
from omnibias.core.verified.transcend import (
    E_IV,
    PI_IV,
    atan_iv,
    atan_point,
    backend_name,
    besseli_iv,
    besseli_point,
    certificate_mode,
    clear_libm_fallback_used,
    cos_iv,
    cos_point,
    cosh_iv,
    erf_iv,
    erf_point,
    exp_iv,
    gauss_cdf_iv,
    gauss_cdf_point,
    libm_fallback_used,
    ln_iv,
    ln_point,
    require_rigorous_backend,
    sech_iv,
    set_strict_backend,
    sigmoid_iv,
    sin_iv,
    sin_point,
    softplus_iv,
    strict_backend,
    tanh_iv,
)
from omnibias.core.verified.transport import (
    SUPPORTED_W1_CDFS,
    certified_wasserstein1,
    certified_wasserstein1_samples,
    certified_wasserstein2_gaussian,
    certified_wasserstein2_samples,
)

__all__ = [
    "AffineForm",
    "Bilinear",
    "BlockOperatorGapCertificate",
    "BoundaryFace",
    "CertifiedGoFResult",
    "Coeff",
    "ComplexInterval",
    "ComplexLike",
    "DerivOracle",
    "E_IV",
    "EigenvalueLowerBound",
    "GAUSS_LEGENDRE_MAX_N",
    "Inertia",
    "Interval",
    "IntervalFn",
    "IntervalLike",
    "JacobianEnclosure",
    "KrawczykCertificate",
    "LehmannCertificate",
    "LinearPDE",
    "LohnerSet",
    "MVJet",
    "NKBounds",
    "PINNErrorCertificate",
    "PI_IV",
    "PerronGapCertificate",
    "QuadEstimate",
    "RadiiCertificate",
    "SUPPORTED_CDFS",
    "SUPPORTED_W1_CDFS",
    "SpectralGapCertificate",
    "SpectralProblem",
    "SpectralRadiiResult",
    "Symbol",
    "SymmetricGapCertificate",
    "TaylorModel",
    "TaylorModelMV",
    "TaylorSeries",
    "ValidatedFourierSeries",
    "ValidatedSeries",
    "VectorField",
    "Wavevector",
    "advection_diffusion",
    "affine_jet",
    "antiderivative_jet",
    "aposteriori_error_certificate",
    "atan_iv",
    "atan_point",
    "backend_name",
    "band_mass_enclosure",
    "bernoulli_number_exact",
    "bernoulli_polynomial_exact",
    "besseli_iv",
    "besseli_point",
    "binned_distribution_enclosure",
    "birkhoff_contraction_ratio",
    "birkhoff_projective_diameter",
    "bisection_bracket",
    "blob",
    "blob_gradient",
    "cdf_enclosure",
    "certificate_mode",
    "certified_block_operator_gap",
    "certified_boundary_residual",
    "certified_condition_number",
    "certified_damping",
    "certified_dirichlet_series",
    "certified_ftc_residual",
    "certified_geometric_series_sum",
    "certified_gof",
    "certified_interior_residual",
    "certified_max_eigenvalue",
    "certified_min_eigenvalue",
    "certified_partials",
    "certified_partials_subdivided",
    "certified_perron_spectral_gap",
    "certified_ratio_series_sum",
    "certified_regularization_error",
    "certified_residual_bound",
    "certified_sign_change",
    "certified_spectral_gap",
    "certified_symmetric_spectral_gap",
    "certified_wasserstein1",
    "certified_wasserstein1_samples",
    "certified_wasserstein2_gaussian",
    "certified_wasserstein2_samples",
    "certify_zero_radii",
    "chi_squared_enclosure",
    "clear_libm_fallback_used",
    "clenshaw_curtis_integral",
    "collatz_wielandt_perron_bounds",
    "complex_exp",
    "compose_jet",
    "compose_jet_mv",
    "conditioning_certificate",
    "conjugate_poisson",
    "conjugate_poisson_deriv",
    "conjugate_poisson_deriv_matrix",
    "conjugate_poisson_matrix",
    "constant_jacobian",
    "convolve",
    "cos_iv",
    "cos_matrix",
    "cos_point",
    "cosh_iv",
    "count_eigenvalues_below",
    "cross_entropy_enclosure",
    "derivative_jet",
    "digamma_iv",
    "dirichlet_beta_odd",
    "dirichlet_l_negative_integer",
    "ell1_nu_norm",
    "empirical_cdf",
    "entropy_enclosure",
    "erf_iv",
    "erf_point",
    "euler_maclaurin_quadrature",
    "euler_maclaurin_sum",
    "euler_number_exact",
    "evaluate_residual",
    "even_profile",
    "even_profile_deriv",
    "even_profile_tail_constant",
    "exp_iv",
    "fourier_nu_norm",
    "from_intervals",
    "ftc_certificate",
    "gauss_cdf_iv",
    "gauss_cdf_point",
    "gauss_legendre_integral",
    "gauss_legendre_nodes",
    "generalized_bernoulli_exact",
    "generalized_eigenvalue_enclosure",
    "geometric_series_closed_form",
    "geometric_tail_bound",
    "geometric_tail_enclosure",
    "hardy_angle",
    "hardy_even",
    "hardy_even_dalpha",
    "hardy_even_deriv",
    "hardy_even_deriv_matrix",
    "hardy_even_matrix",
    "hardy_even_profile",
    "hardy_even_profile_deriv",
    "hardy_odd",
    "hardy_odd_dalpha",
    "hardy_odd_deriv",
    "hardy_odd_deriv_matrix",
    "hardy_odd_matrix",
    "hardy_pair",
    "hardy_radius",
    "hardy_tail_constant",
    "hellinger_enclosure",
    "helmholtz",
    "hermite_coeffs_exact",
    "hilbert_circulant",
    "hilbert_even_profile",
    "hilbert_even_profile_deriv",
    "hilbert_hardy_even_profile",
    "hilbert_hardy_even_profile_deriv",
    "hilbert_of_conjugate",
    "hilbert_of_hardy_even",
    "hilbert_of_hardy_odd",
    "hilbert_of_poisson",
    "hilbert_tail_bound",
    "horner_interval",
    "hull",
    "hurwitz_zeta",
    "hurwitz_zeta_negative_integer",
    "identity_jet",
    "inf_norm_matrix",
    "inf_norm_vector",
    "integrate_ivp",
    "interval_ldlt_inertia",
    "interval_ldlt_pivots",
    "interval_matrix_exp",
    "interval_newton",
    "is_positive_definite",
    "jet_gradient",
    "jet_hessian",
    "jet_laplacian",
    "jet_multiply",
    "jet_partials",
    "jet_to_tower",
    "js_divergence_enclosure",
    "kl_divergence_enclosure",
    "krawczyk_certificate",
    "krawczyk_search",
    "l_function_enclosure",
    "laplace",
    "laplacian_symbol",
    "laplacian_tail_inverse_bound",
    "layer_jet",
    "layer_jet_mv",
    "lehmann_maehly_lower_bounds",
    "leray_blob_field",
    "leray_divergence_residual",
    "leray_symbol",
    "lerch_transcendent",
    "lhopital_ratio_iv",
    "libm_fallback_used",
    "linear_field",
    "ln_iv",
    "ln_point",
    "log_gamma_iv",
    "lohner_flow",
    "lohner_step",
    "matvec",
    "midpoint_integral",
    "mlp_jet",
    "mlp_jet_mv",
    "mutual_information_enclosure",
    "n_power_neg_s",
    "naive_interval_flow",
    "neumann_inverse_norm_bound",
    "new_noise_symbol",
    "newton_kantorovich_bounds",
    "newtonian_potential",
    "operator_comparison_bounds",
    "p_series_tail_bound",
    "path_jet",
    "poisson",
    "poisson_kernel",
    "poisson_kernel_deriv",
    "poisson_matrix",
    "poisson_primitive",
    "poisson_primitive_matrix",
    "polylog_enclosure",
    "positive_definite_pivots_certificate",
    "potential_gradient",
    "qr_gram_schmidt",
    "quadratic_radii_certificate",
    "radii_polynomial_certificate",
    "radii_polynomial_residual_certificate",
    "rayleigh_quotient",
    "require_rigorous_backend",
    "riesz_double_blob",
    "riesz_symbol",
    "riesz_tail_bound",
    "ritz_upper_bound",
    "romberg_integral",
    "screened_poisson",
    "sech_iv",
    "sech_poly_coeffs_exact",
    "series_mul",
    "set_strict_backend",
    "sigma_tower_interval",
    "sigma_value_interval",
    "sigmoid_iv",
    "sigmoid_poly_coeffs_exact",
    "simpson_integral",
    "sin_iv",
    "sin_matrix",
    "sin_point",
    "softplus_iv",
    "spectral_residual_norm",
    "sqg_blob",
    "sqg_blob_gradient",
    "sqg_blob_l2_inner",
    "sqg_riesz",
    "sqg_stream",
    "sqg_stream_gradient",
    "sqg_velocity",
    "sqg_velocity_divergence_residual",
    "strict_backend",
    "sum_intervals",
    "symmetric_eigenvalue_residual_enclosure",
    "tanh_iv",
    "tanh_poly_coeffs_exact",
    "tanh_sinh_estimate",
    "temple_lower_bound",
    "temple_lower_bound_vector",
    "theta_enclosure",
    "total_variation_enclosure",
    "tower_to_jet",
    "trapezoid_integral",
    "trapezoid_sum",
    "uniform_nodes",
    "zeta_enclosure",
    "zeta_euler_maclaurin",
    "zeta_even",
    "zeta_negative_odd",
]
