# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-omnibias-Commercial
# Copyright (C) 2026 Derivon
"""omnibias-verify: certified neural-network verification.

The pure-Python :mod:`omnibias.verify._core` propagates rigorous enclosures
(intervals / multivariate Taylor models from :mod:`omnibias.core.verified`)
through a trained network -- smooth activations reuse the closed-form
``tanh_iv`` / ``sigmoid_iv`` enclosures, nonsmooth ones (ReLU / GELU / max-pool)
get their own sound enclosures -- with branch-and-bound over the input box. The
result is a *theorem-grade* certificate: robustness, a Lipschitz bound,
monotonicity, or a reachable-set enclosure.

Weight ingestion from the differentiable backends lives under
``omnibias.verify.torch`` and ``omnibias.verify.jax``; import them explicitly so
the core stays dependency-free.

Everything here is **sound by construction** (an enclosure always contains the
true output set); it is *not* complete -- branch-and-bound may return
``UNKNOWN`` rather than over-claim.

.. important::

    **Bit-parity with the PyTorch twin requires 64-bit JAX** --
    ``jax.config.update("jax_enable_x64", True)`` before the first JAX array is
    created (or ``JAX_ENABLE_X64=1``). JAX otherwise truncates to ``float32``
    while PyTorch uses ``float64``, so the twins stay internally consistent but
    agree only to ``float32`` tolerance. Where a value feeds a threshold, a
    rounding step or an ``argmax``, that is enough to change the decision rather
    than just the last digits. See :mod:`omnibias.jax.precision`.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError as _PkgNotFound
from importlib.metadata import version as _pkg_version

from omnibias.verify._core import (
    KERNELS,
    SUPPORTED_ACTIVATIONS,
    BoundResult,
    Box,
    CertifiedBound,
    CertifiedPDEPipelineResult,
    CriticalPoint,
    DomainIntegralCertificate,
    FlatnessResult,
    GELULayer,
    GlobalMinResult,
    GlobalTrainingCertificate,
    GradientCheckCertificate,
    IntegralCertificate,
    IntegrandModel,
    IntervalMatrix,
    LaplacianTruncationCertificate,
    Layer,
    LinearLayer,
    LpNormCertificate,
    MaxPoolLayer,
    MLPArchitecture,
    MonotonicityCertificate,
    Network,
    NetworkCertificate,
    NormMethod,
    ParamJet,
    ParamSpaceLoss,
    QuadMethod,
    RangeResult,
    ReLULayer,
    RobustnessCertificate,
    SigmoidLayer,
    SobolevNormCertificate,
    StencilTruncationCertificate,
    StochasticResidualCertificate,
    SubspaceModel,
    SubspaceStepCertificate,
    TanhLayer,
    TrainingCertificate,
    VerifiedLayer,
    VerifiedLayerBundle,
    affine_layer,
    agreement_margin_iv,
    cauchy_step,
    certified_critical_points,
    certified_domain_integral,
    certified_flatness,
    certified_fokker_planck_residual,
    certified_gradient_check,
    certified_integral,
    certified_ito_generator_residual,
    certified_laplacian_truncation,
    certified_layer_cake_integral,
    certified_lp_norm,
    certified_minimize,
    certified_network_critical_points,
    certified_network_flatness,
    certified_network_integral,
    certified_network_minimize,
    certified_sobolev_norm,
    certified_stencil_truncation,
    certify_agreement_margin,
    certify_fokker_planck_residual,
    certify_ito_generator_residual,
    certify_network_strict_local_min,
    certify_no_dead_unit,
    certify_pinn_aposteriori,
    certify_robustness,
    certify_strict_local_min,
    certify_subspace_step,
    certify_trained_global_min,
    certify_trained_min,
    certify_trained_network,
    certify_trajectory,
    compose_gelu,
    compose_sigma,
    enclose_subspace_model,
    flat_params_from_layers,
    gauss_cdf_iv,
    gelu_enclosure,
    gradient_residual_certificate,
    input_models,
    interval_jacobian,
    interval_propagate,
    jet_remainder_iv,
    krylov_basis,
    linear_image,
    lipschitz_bound,
    max_enclosure,
    measured_consistency_order,
    mlp_axis_oracles,
    mollification_bias_iv,
    mollified_lipschitz_iv,
    monotonicity,
    network_axis_oracles,
    network_integrand_model,
    output_range,
    param_jet,
    reachable_box,
    relu_enclosure,
    relu_taylor,
    replay_stochastic_residual_certificate,
    scalar_readout_range,
    stochastic_residual_schema_errors,
    surrogate_kernel_iv,
    tail_gradient_iv,
    taylor_output_bounds,
    taylor_propagate,
    verified_layer_bundle,
    verified_layers,
)

try:
    __version__ = _pkg_version("omnibias-verify")
except _PkgNotFound:  # pragma: no cover - bare source checkout
    __version__ = "0.0.0+unknown"

# Founding-idea lineage (see docs/theory.md "Two senses of collapse").
__lineage__ = "bias collapse"

__all__ = [
    "BoundResult",
    "Box",
    "CertifiedBound",
    "CertifiedPDEPipelineResult",
    "CriticalPoint",
    "DomainIntegralCertificate",
    "FlatnessResult",
    "GELULayer",
    "GlobalMinResult",
    "GlobalTrainingCertificate",
    "GradientCheckCertificate",
    "IntegralCertificate",
    "IntegrandModel",
    "IntervalMatrix",
    "KERNELS",
    "LaplacianTruncationCertificate",
    "Layer",
    "LinearLayer",
    "LpNormCertificate",
    "MLPArchitecture",
    "MaxPoolLayer",
    "MonotonicityCertificate",
    "Network",
    "NetworkCertificate",
    "NormMethod",
    "ParamJet",
    "ParamSpaceLoss",
    "QuadMethod",
    "RangeResult",
    "ReLULayer",
    "RobustnessCertificate",
    "SUPPORTED_ACTIVATIONS",
    "SigmoidLayer",
    "SobolevNormCertificate",
    "StencilTruncationCertificate",
    "StochasticResidualCertificate",
    "SubspaceModel",
    "SubspaceStepCertificate",
    "TanhLayer",
    "TrainingCertificate",
    "VerifiedLayer",
    "VerifiedLayerBundle",
    "__lineage__",
    "__version__",
    "affine_layer",
    "agreement_margin_iv",
    "cauchy_step",
    "certified_critical_points",
    "certified_domain_integral",
    "certified_flatness",
    "certified_fokker_planck_residual",
    "certified_gradient_check",
    "certified_integral",
    "certified_ito_generator_residual",
    "certified_laplacian_truncation",
    "certified_layer_cake_integral",
    "certified_lp_norm",
    "certified_minimize",
    "certified_network_critical_points",
    "certified_network_flatness",
    "certified_network_integral",
    "certified_network_minimize",
    "certified_sobolev_norm",
    "certified_stencil_truncation",
    "certify_agreement_margin",
    "certify_fokker_planck_residual",
    "certify_ito_generator_residual",
    "certify_network_strict_local_min",
    "certify_no_dead_unit",
    "certify_pinn_aposteriori",
    "certify_robustness",
    "certify_strict_local_min",
    "certify_subspace_step",
    "certify_trained_global_min",
    "certify_trained_min",
    "certify_trained_network",
    "certify_trajectory",
    "compose_gelu",
    "compose_sigma",
    "enclose_subspace_model",
    "flat_params_from_layers",
    "gauss_cdf_iv",
    "gelu_enclosure",
    "gradient_residual_certificate",
    "input_models",
    "interval_jacobian",
    "interval_propagate",
    "jet_remainder_iv",
    "krylov_basis",
    "linear_image",
    "lipschitz_bound",
    "max_enclosure",
    "measured_consistency_order",
    "mlp_axis_oracles",
    "mollification_bias_iv",
    "mollified_lipschitz_iv",
    "monotonicity",
    "network_axis_oracles",
    "network_integrand_model",
    "output_range",
    "param_jet",
    "reachable_box",
    "relu_enclosure",
    "relu_taylor",
    "replay_stochastic_residual_certificate",
    "scalar_readout_range",
    "stochastic_residual_schema_errors",
    "surrogate_kernel_iv",
    "tail_gradient_iv",
    "taylor_output_bounds",
    "taylor_propagate",
    "verified_layer_bundle",
    "verified_layers",
]
