# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""omnibias.geometry.gauge: non-abelian gauge theory on the omnibias substrate.

Lie algebras ``su(N)`` / ``u(1)`` (generators, structure constants ``f^{abc}``,
symmetric ``d^{abc}``), Lie-algebra-valued differential forms, gauge connections
``A_mu^a``, the field strength ``F = dA + g[A, A]``, the gauge-covariant
derivative and divergence (the Yang-Mills operator), the flat signature-aware
Hodge star on ``R^4``, the Yang-Mills action, topological charge, and gauge
transformations -- with closed-form connection derivatives from the
``omnibias-fields`` substrate and cross-backend (torch + jax) parity.

The pure-Python schemas (:class:`LieAlgebra`, :class:`LieAlgebraValuedForm`,
:class:`GaugeConnectionSpec`) live in :mod:`omnibias.geometry.gauge._core`; the backend
ops live in ``omnibias.geometry.gauge.torch`` and ``omnibias.geometry.gauge.jax``.

Two further submodules are imported by path rather than re-exported here:
``omnibias.geometry.gauge.lattice`` (the SU(2) lattice Monte-Carlo engine and its
statistical mass-gap estimators) and ``omnibias.geometry.gauge.transfer``
(rigorously enclosed transfer matrices and their **certified** spectral gaps, with
sealed certificates registered through ``omnibias.geometry.gauge.proofmachine``).

Maturity: this is an **alpha** submodule (folded in from the former standalone
``omnibias-gauge`` package) shipped inside the Beta ``omnibias-geometry``
distribution. It is the non-abelian extension of ``omnibias-geometry``'s
Riemannian / abelian exterior calculus, on the same ``omnibias-fields`` substrate;
its gauge-bundle API may still change while the rest of ``omnibias-geometry`` is Beta.
"""

from __future__ import annotations

from omnibias.geometry.gauge._core import (
    ADJOINT_BIANCHI,
    ADJOINT_YM,
    DEFAULT_LANDAU_OMEGA,
    DEFAULT_LANDAU_STEPS,
    DEFAULT_TIKHONOV_LAM,
    ENSEMBLE_ABS_P,
    ENSEMBLE_C_P,
    ENSEMBLE_CHI_P,
    ENSEMBLE_G_P2,
    ENSEMBLE_LOG_ABS_P,
    ENSEMBLE_LOG_ABS_T,
    ENSEMBLE_LOG_C_P,
    ENSEMBLE_OMEGA,
    ENSEMBLE_P2,
    ENSEMBLE_R,
    ENSEMBLE_RHO,
    EUCLIDEAN_4D,
    IMPLEMENTED_INVARIANT_NAMES,
    LANDAU_ORBIT_ATOL,
    LANDAU_RESIDUAL_ATOL,
    LANDAU_TRANSVERSE_ATOL,
    LEGAL_ADJOINT_1FORM_ATOMS,
    LEGAL_ENSEMBLE_ATOMS,
    LEGAL_LOOP_ATOMS,
    LEGAL_SINGLET_ATOMS,
    LOOP_INVARIANCE_ATOL,
    LOOP_PLAQUETTE,
    LOOP_POLYAKOV,
    LOOP_W11,
    LOOP_W12,
    LOOP_W21,
    LOOP_W22,
    MAX_SEARCHABLE_DIM6_SU3,
    MINKOWSKI_4D,
    SELF_DUAL_ACTION_OVER_TOPOLOGICAL,
    SINGLET_BIANCHI_SQ,
    SINGLET_DF_SQ,
    SINGLET_SELF_DUAL_SQ,
    SINGLET_TR_F2,
    SINGLET_TR_F3,
    SINGLET_TR_F_FTILDE,
    SINGLET_YM_SQ,
    SPECTRAL_RECOVERY_ATOL,
    SU3_4D_COORDINATE_2JET,
    SU3_4D_DF_BIANCHI_REDUCED,
    SU3_4D_DF_RAW,
    SU3_4D_F,
    WEAK_YM_FLOOR,
    WILSON_EXTENTS,
    AdjointTestBank,
    AdjointTestOneForm,
    ConnectionSource,
    EnsembleObservableTable,
    GaugeConnectionSpec,
    GaugeCovariantJet,
    GaugeInvariantDictionary,
    InvariantAtom,
    Irrep,
    LatticeLinkField,
    LieAlgebra,
    LieAlgebraValuedForm,
    LoopObservableTable,
    adjoint,
    adjoint_rep_matrices,
    antisymmetric_power,
    antisymmetric_power_rep_matrices,
    as_lie_algebra,
    assert_library_ensemble_legal,
    assert_library_gauge_legal,
    assert_library_loop_legal,
    bianchi_reduced_df_dimension,
    bpst_instanton_arrays,
    branching_to_subalgebra,
    character,
    connection_component_names,
    covariant_singlet_columns,
    creutz_ratio_from_wilson,
    dimension,
    dual_coxeter_number,
    dynkin_index,
    ensemble_table_from_link_ensemble,
    ensemble_table_from_mc_dict,
    enumerate_gauge_invariants,
    evaluate_gauge_law_gate,
    evaluate_loop_atoms,
    evaluate_loop_gauge_invariance,
    evaluate_named_invariants,
    evaluate_weak_ym_identity,
    fundamental,
    gauge_connection_spec,
    gauge_equivariance_defect,
    gaussian_adjoint_test_bank,
    global_gauge_transform_connection,
    gluon_propagator_p2,
    hodge_star_flat,
    identity_numpy_links,
    irrep,
    is_ensemble_atom_name,
    is_ensemble_cert_name,
    is_green_column_name,
    is_loop_atom_name,
    is_scalar_integral_column_name,
    kallen_lehmann_kernel,
    landau_gauge_fix,
    landau_residual,
    levi_civita_symbol,
    permutation_sign,
    planted_spectral_vectors,
    quadratic_casimir,
    random_numpy_links,
    random_special_unitary,
    raw_connection_jet_dimension,
    raw_covariant_fiber_dimension,
    reconstruct_spectral_density,
    refuse_cert_as_ensemble_atom,
    refuse_component_fiber_library,
    refuse_connection_jet_from_links,
    refuse_coordinate_jet_library,
    refuse_ensemble_as_covariant_jet,
    refuse_ensemble_as_loop_source,
    refuse_flattened_adjoint_library,
    refuse_green_as_ensemble_atom,
    refuse_green_as_jet_atom,
    refuse_jet_as_ensemble_source,
    refuse_jet_as_loop_source,
    refuse_lattice_random_feature_jet,
    refuse_loop_as_covariant_jet,
    refuse_loop_table_as_ensemble,
    refuse_scalar_integral_as_ym_weak_form,
    refuse_single_config_as_ensemble,
    refuse_spectral_as_mass_gap,
    refuse_unregularized_spectral_inverse,
    representation_complexity,
    sorted_index_sets,
    su,
    su2_spin_matrices,
    symmetric_power,
    symmetric_power_rep_matrices,
    tensor_product_decomposition,
    thooft_eta,
    trivial,
    u1,
    weak_yang_mills_residuals,
    wedge,
    weight_multiplicities,
    wilson_plaquette_pairs,
)

__all__ = [
    "ADJOINT_BIANCHI",
    "ADJOINT_YM",
    "AdjointTestBank",
    "AdjointTestOneForm",
    "ConnectionSource",
    "DEFAULT_LANDAU_OMEGA",
    "DEFAULT_LANDAU_STEPS",
    "DEFAULT_TIKHONOV_LAM",
    "ENSEMBLE_ABS_P",
    "ENSEMBLE_CHI_P",
    "ENSEMBLE_C_P",
    "ENSEMBLE_G_P2",
    "ENSEMBLE_LOG_ABS_P",
    "ENSEMBLE_LOG_ABS_T",
    "ENSEMBLE_LOG_C_P",
    "ENSEMBLE_OMEGA",
    "ENSEMBLE_P2",
    "ENSEMBLE_R",
    "ENSEMBLE_RHO",
    "EUCLIDEAN_4D",
    "EnsembleObservableTable",
    "GaugeConnectionSpec",
    "GaugeCovariantJet",
    "GaugeInvariantDictionary",
    "IMPLEMENTED_INVARIANT_NAMES",
    "InvariantAtom",
    "Irrep",
    "LANDAU_ORBIT_ATOL",
    "LANDAU_RESIDUAL_ATOL",
    "LANDAU_TRANSVERSE_ATOL",
    "LEGAL_ADJOINT_1FORM_ATOMS",
    "LEGAL_ENSEMBLE_ATOMS",
    "LEGAL_LOOP_ATOMS",
    "LEGAL_SINGLET_ATOMS",
    "LOOP_INVARIANCE_ATOL",
    "LOOP_PLAQUETTE",
    "LOOP_POLYAKOV",
    "LOOP_W11",
    "LOOP_W12",
    "LOOP_W21",
    "LOOP_W22",
    "LatticeLinkField",
    "LieAlgebra",
    "LieAlgebraValuedForm",
    "LoopObservableTable",
    "MAX_SEARCHABLE_DIM6_SU3",
    "MINKOWSKI_4D",
    "SELF_DUAL_ACTION_OVER_TOPOLOGICAL",
    "SINGLET_BIANCHI_SQ",
    "SINGLET_DF_SQ",
    "SINGLET_SELF_DUAL_SQ",
    "SINGLET_TR_F2",
    "SINGLET_TR_F3",
    "SINGLET_TR_F_FTILDE",
    "SINGLET_YM_SQ",
    "SPECTRAL_RECOVERY_ATOL",
    "SU3_4D_COORDINATE_2JET",
    "SU3_4D_DF_BIANCHI_REDUCED",
    "SU3_4D_DF_RAW",
    "SU3_4D_F",
    "WEAK_YM_FLOOR",
    "WILSON_EXTENTS",
    "adjoint",
    "adjoint_rep_matrices",
    "antisymmetric_power",
    "antisymmetric_power_rep_matrices",
    "as_lie_algebra",
    "assert_library_ensemble_legal",
    "assert_library_gauge_legal",
    "assert_library_loop_legal",
    "bianchi_reduced_df_dimension",
    "bpst_instanton_arrays",
    "branching_to_subalgebra",
    "character",
    "connection_component_names",
    "covariant_singlet_columns",
    "creutz_ratio_from_wilson",
    "dimension",
    "dual_coxeter_number",
    "dynkin_index",
    "ensemble_table_from_link_ensemble",
    "ensemble_table_from_mc_dict",
    "enumerate_gauge_invariants",
    "evaluate_gauge_law_gate",
    "evaluate_loop_atoms",
    "evaluate_loop_gauge_invariance",
    "evaluate_named_invariants",
    "evaluate_weak_ym_identity",
    "fundamental",
    "gaussian_adjoint_test_bank",
    "gauge_connection_spec",
    "gauge_equivariance_defect",
    "gluon_propagator_p2",
    "global_gauge_transform_connection",
    "hodge_star_flat",
    "identity_numpy_links",
    "irrep",
    "is_ensemble_atom_name",
    "is_ensemble_cert_name",
    "is_green_column_name",
    "is_loop_atom_name",
    "is_scalar_integral_column_name",
    "kallen_lehmann_kernel",
    "landau_gauge_fix",
    "landau_residual",
    "levi_civita_symbol",
    "permutation_sign",
    "planted_spectral_vectors",
    "quadratic_casimir",
    "random_numpy_links",
    "random_special_unitary",
    "raw_connection_jet_dimension",
    "raw_covariant_fiber_dimension",
    "reconstruct_spectral_density",
    "refuse_cert_as_ensemble_atom",
    "refuse_component_fiber_library",
    "refuse_connection_jet_from_links",
    "refuse_coordinate_jet_library",
    "refuse_ensemble_as_covariant_jet",
    "refuse_ensemble_as_loop_source",
    "refuse_flattened_adjoint_library",
    "refuse_green_as_ensemble_atom",
    "refuse_green_as_jet_atom",
    "refuse_jet_as_ensemble_source",
    "refuse_jet_as_loop_source",
    "refuse_lattice_random_feature_jet",
    "refuse_loop_as_covariant_jet",
    "refuse_loop_table_as_ensemble",
    "refuse_scalar_integral_as_ym_weak_form",
    "refuse_single_config_as_ensemble",
    "refuse_spectral_as_mass_gap",
    "refuse_unregularized_spectral_inverse",
    "representation_complexity",
    "sorted_index_sets",
    "su",
    "su2_spin_matrices",
    "symmetric_power",
    "symmetric_power_rep_matrices",
    "tensor_product_decomposition",
    "thooft_eta",
    "trivial",
    "u1",
    "weak_yang_mills_residuals",
    "wedge",
    "weight_multiplicities",
    "wilson_plaquette_pairs",
]
