# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Operator-learning datasets from the existing spectral MOL reference (torch).

No new solver: pairs ``(u_0, u(., t))`` are generated by
:func:`~omnibias.pinn.solver.torch.evolution.method_of_lines` on a
:class:`~omnibias.pinn.solver.torch.spectral.SpectralGrid1D`.
"""

from __future__ import annotations

from dataclasses import dataclass

import torch
from omnibias.pinn.operator._core.sensors import SensorGrid, sample_fourier_ics
from omnibias.pinn.solver.torch.evolution import (
    burgers_semidiscrete,
    heat_semidiscrete,
    kuramoto_sivashinsky_semidiscrete,
    method_of_lines,
)
from omnibias.pinn.solver.torch.spectral import SpectralGrid1D
from torch import Tensor


@dataclass(frozen=True)
class OperatorSlab:
    """A batch of space-time solution slabs for operator learning.

    Attributes
    ----------
    sensors
        Input-function observations of shape ``(F, m)``.
    coords
        Query coordinates of shape ``(Q, D)`` with axes ``(x, t)`` (or the
        problem's coordinate order). Shared across the batch.
    values
        Target field values of shape ``(F, Q, C)``.
    grid
        The spectral grid the reference was marched on.
    """

    sensors: Tensor
    coords: Tensor
    values: Tensor
    grid: SpectralGrid1D


def _space_time_coords(grid: SpectralGrid1D, times: Tensor) -> Tensor:
    """Build the shared ``(Q, 2)`` query grid with columns ``(x, t)``."""
    x = grid.points()  # (n,)
    # Full product: for each time, every x.
    xs = x.repeat(times.numel())
    ts = times.repeat_interleave(x.numel())
    return torch.stack([xs, ts], dim=-1)


def make_heat_slab(
    *,
    n_samples: int = 32,
    n_grid: int = 64,
    n_sensors: int = 32,
    n_modes: int = 4,
    amplitude: float = 1.0,
    diffusivity: float = 0.1,
    t_final: float = 0.5,
    n_times: int = 11,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> OperatorSlab:
    """Periodic heat equation slabs from spectral MOL + analytic-mode ICs."""
    length = 2.0 * torch.pi
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    # Sample ICs on the fine grid, then restrict to sensors.
    fine = SensorGrid(points=grid.points().detach().cpu().numpy(), length=float(length))
    u0_np = sample_fourier_ics(
        n_samples, fine, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    u0 = torch.tensor(u0_np, dtype=dtype)
    # Sensor observations by nearest-neighbour on the fine grid (equispaced, so
    # exact subsample when n_sensors divides n_grid).
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    times_seq = [float(t) for t in times]
    semi = heat_semidiscrete(grid, diffusivity)
    snaps_list = []
    for i in range(n_samples):
        snaps, _ = method_of_lines(semi, u0[i], times_seq, integrator="rk4")
        snaps_list.append(snaps)  # (T, n)
    snaps_b = torch.stack(snaps_list, dim=0)  # (F, T, n)
    if not torch.isfinite(snaps_b).all():
        raise RuntimeError(
            "heat MOL reference produced non-finite values; reduce amplitude "
            "or n_modes, or increase n_grid"
        )
    coords = _space_time_coords(grid, times)
    # values (F, T*n, 1)
    values = snaps_b.reshape(n_samples, -1, 1)
    return OperatorSlab(sensors=sensors, coords=coords, values=values, grid=grid)


def make_burgers_slab(
    *,
    n_samples: int = 16,
    n_grid: int = 64,
    n_sensors: int = 32,
    n_modes: int = 2,
    amplitude: float = 0.5,
    viscosity: float = 0.05,
    t_final: float = 0.5,
    n_times: int = 11,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> OperatorSlab:
    """Periodic viscous Burgers slabs from spectral MOL (ETDRK4).

    Defaults keep the reference stable on a 64-point grid: ``n_modes=2`` and
    ``amplitude=0.5``. Larger amplitudes or more modes on a coarse grid can
    under-resolve shocks and yield non-finite snapshots.
    """
    length = 2.0 * torch.pi
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    fine = SensorGrid(points=grid.points().detach().cpu().numpy(), length=float(length))
    u0_np = sample_fourier_ics(
        n_samples, fine, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    u0 = torch.tensor(u0_np, dtype=dtype)
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    times_seq = [float(t) for t in times]
    semi = burgers_semidiscrete(grid, viscosity)
    snaps_list = []
    for i in range(n_samples):
        snaps, _ = method_of_lines(semi, u0[i], times_seq, integrator="etdrk4")
        snaps_list.append(snaps)
    snaps_b = torch.stack(snaps_list, dim=0)
    if not torch.isfinite(snaps_b).all():
        raise RuntimeError(
            "Burgers MOL reference produced non-finite values; reduce amplitude "
            "or n_modes, or increase n_grid / viscosity"
        )
    coords = _space_time_coords(grid, times)
    values = snaps_b.reshape(n_samples, -1, 1)
    return OperatorSlab(sensors=sensors, coords=coords, values=values, grid=grid)


def make_ks_slab(
    *,
    n_samples: int = 8,
    n_grid: int = 128,
    n_sensors: int = 32,
    n_modes: int = 2,
    amplitude: float = 0.5,
    t_final: float = 1.0,
    n_times: int = 11,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> OperatorSlab:
    """Periodic Kuramoto-Sivashinsky slabs from spectral MOL (ETDRK4).

    Uses the house stiff-test domain ``length = 32 pi`` and grid size 128.
    RK4 is unstable at the step sizes this horizon implies; ETDRK4 is required.
    """
    import math

    length = 32.0 * math.pi
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    fine = SensorGrid(points=grid.points().detach().cpu().numpy(), length=float(length))
    u0_np = sample_fourier_ics(
        n_samples, fine, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    u0 = torch.tensor(u0_np, dtype=dtype)
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    times_seq = [float(t) for t in times]
    semi = kuramoto_sivashinsky_semidiscrete(grid)
    snaps_list = []
    for i in range(n_samples):
        snaps, _ = method_of_lines(semi, u0[i], times_seq, integrator="etdrk4")
        snaps_list.append(snaps)
    snaps_b = torch.stack(snaps_list, dim=0)
    if not torch.isfinite(snaps_b).all():
        raise RuntimeError(
            "KS MOL reference produced non-finite values; reduce amplitude "
            "or n_modes, or shorten t_final"
        )
    coords = _space_time_coords(grid, times)
    values = snaps_b.reshape(n_samples, -1, 1)
    return OperatorSlab(sensors=sensors, coords=coords, values=values, grid=grid)


__all__ = [
    "OperatorSlab",
    "make_burgers_slab",
    "make_heat_slab",
    "make_ks_slab",
]
