# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Operator-learning datasets from the existing spectral MOL reference (torch).

No new solver: pairs ``(u_0, u(., t))`` are generated by
:func:`~omnibias.pinn.solver.torch.evolution.method_of_lines` on a
:class:`~omnibias.pinn.solver.torch.spectral.SpectralGrid1D`.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

import numpy as np
import torch
from omnibias.pinn.operator._core.sensors import SensorGrid, sample_fourier_ics
from omnibias.pinn.solver.torch.evolution import (
    burgers_semidiscrete,
    heat_semidiscrete,
    kuramoto_sivashinsky_semidiscrete,
    method_of_lines,
)
from omnibias.pinn.solver.torch.spectral import SpectralGrid1D
from torch import Tensor


@dataclass(frozen=True)
class OperatorSlab:
    """A batch of space-time solution slabs for operator learning.

    Attributes
    ----------
    sensors
        Input-function observations of shape ``(F, m)``.
    coords
        Query coordinates of shape ``(Q, D)`` with axes ``(x, t)`` (or the
        problem's coordinate order). Shared across the batch.
    values
        Target field values of shape ``(F, Q, C)``.
    grid
        The spectral grid the reference was marched on.
    """

    sensors: Tensor
    coords: Tensor
    values: Tensor
    grid: SpectralGrid1D


def _space_time_coords(grid: SpectralGrid1D, times: Tensor) -> Tensor:
    """Build the shared ``(Q, 2)`` query grid with columns ``(x, t)``."""
    x = grid.points()  # (n,)
    # Full product: for each time, every x.
    xs = x.repeat(times.numel())
    ts = times.repeat_interleave(x.numel())
    return torch.stack([xs, ts], dim=-1)


def _assert_heat_maximum_principle(
    snaps: Tensor,
    u0: Tensor,
    *,
    name: str,
) -> None:
    """Enforce the heat maximum principle ``max|u(t)| <= max|u0|``.

    Explicit RK4 on a stiff Fourier heat operator can produce finite-but-
    exploding snapshots that pass an ``isfinite`` check while encoding a
    divergence (measured: ``max|u| ~ 1e9`` at diffusivity 0.24). The
    physical invariant catches that class of failure.
    """
    if not torch.isfinite(snaps).all():
        raise RuntimeError(
            f"{name}: non-finite values; reduce amplitude / n_modes "
            "or use an unconditionally stable integrator"
        )
    u0_max = float(u0.detach().abs().amax())
    snaps_max = float(snaps.detach().abs().amax())
    if snaps_max > u0_max * (1.0 + 1e-6) + 1e-12:
        raise RuntimeError(
            f"{name}: maximum principle violated "
            f"(max|u|={snaps_max:.3e} > max|u0|={u0_max:.3e}); "
            "the reference integrator is unstable -- use etdrk4 for heat"
        )


def make_heat_slab(
    *,
    n_samples: int = 32,
    n_grid: int = 64,
    n_sensors: int = 32,
    n_modes: int = 4,
    amplitude: float = 1.0,
    diffusivity: float = 0.1,
    t_final: float = 0.5,
    n_times: int = 11,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> OperatorSlab:
    """Periodic heat equation slabs from spectral MOL + analytic-mode ICs."""
    length = 2.0 * torch.pi
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    # Sample ICs on the fine grid, then restrict to sensors.
    fine = SensorGrid(points=grid.points().detach().cpu().numpy(), length=float(length))
    u0_np = sample_fourier_ics(
        n_samples, fine, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    u0 = torch.tensor(u0_np, dtype=dtype)
    # Sensor observations by nearest-neighbour on the fine grid (equispaced, so
    # exact subsample when n_sensors divides n_grid).
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    times_seq = [float(t) for t in times]
    # Heat is linear with a diagonal Fourier symbol; ETDRK4 advances it by
    # exp(dt L) exactly and is unconditionally stable. Explicit RK4 crosses
    # its stability boundary around diffusivity ~0.14 on a 64-point grid.
    semi = heat_semidiscrete(grid, diffusivity)
    snaps_list = []
    for i in range(n_samples):
        snaps, _ = method_of_lines(semi, u0[i], times_seq, integrator="etdrk4")
        snaps_list.append(snaps)  # (T, n)
    snaps_b = torch.stack(snaps_list, dim=0)  # (F, T, n)
    _assert_heat_maximum_principle(snaps_b, u0, name="heat MOL reference")
    coords = _space_time_coords(grid, times)
    # values (F, T*n, 1)
    values = snaps_b.reshape(n_samples, -1, 1)
    return OperatorSlab(sensors=sensors, coords=coords, values=values, grid=grid)


def make_burgers_slab(
    *,
    n_samples: int = 16,
    n_grid: int = 64,
    n_sensors: int = 32,
    n_modes: int = 2,
    amplitude: float = 0.5,
    viscosity: float = 0.05,
    t_final: float = 0.5,
    n_times: int = 11,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> OperatorSlab:
    """Periodic viscous Burgers slabs from spectral MOL (ETDRK4).

    Defaults keep the reference stable on a 64-point grid: ``n_modes=2`` and
    ``amplitude=0.5``. Larger amplitudes or more modes on a coarse grid can
    under-resolve shocks and yield non-finite snapshots.
    """
    length = 2.0 * torch.pi
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    fine = SensorGrid(points=grid.points().detach().cpu().numpy(), length=float(length))
    u0_np = sample_fourier_ics(
        n_samples, fine, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    u0 = torch.tensor(u0_np, dtype=dtype)
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    times_seq = [float(t) for t in times]
    semi = burgers_semidiscrete(grid, viscosity)
    snaps_list = []
    for i in range(n_samples):
        snaps, _ = method_of_lines(semi, u0[i], times_seq, integrator="etdrk4")
        snaps_list.append(snaps)
    snaps_b = torch.stack(snaps_list, dim=0)
    if not torch.isfinite(snaps_b).all():
        raise RuntimeError(
            "Burgers MOL reference produced non-finite values; reduce amplitude "
            "or n_modes, or increase n_grid / viscosity"
        )
    coords = _space_time_coords(grid, times)
    values = snaps_b.reshape(n_samples, -1, 1)
    return OperatorSlab(sensors=sensors, coords=coords, values=values, grid=grid)


def make_ks_slab(
    *,
    n_samples: int = 8,
    n_grid: int = 128,
    n_sensors: int = 32,
    n_modes: int = 2,
    amplitude: float = 0.5,
    t_final: float = 1.0,
    n_times: int = 11,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> OperatorSlab:
    """Periodic Kuramoto-Sivashinsky slabs from spectral MOL (ETDRK4).

    Uses the house stiff-test domain ``length = 32 pi`` and grid size 128.
    RK4 is unstable at the step sizes this horizon implies; ETDRK4 is required.
    """
    import math

    length = 32.0 * math.pi
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    fine = SensorGrid(points=grid.points().detach().cpu().numpy(), length=float(length))
    u0_np = sample_fourier_ics(
        n_samples, fine, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    u0 = torch.tensor(u0_np, dtype=dtype)
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    times_seq = [float(t) for t in times]
    semi = kuramoto_sivashinsky_semidiscrete(grid)
    snaps_list = []
    for i in range(n_samples):
        snaps, _ = method_of_lines(semi, u0[i], times_seq, integrator="etdrk4")
        snaps_list.append(snaps)
    snaps_b = torch.stack(snaps_list, dim=0)
    if not torch.isfinite(snaps_b).all():
        raise RuntimeError(
            "KS MOL reference produced non-finite values; reduce amplitude "
            "or n_modes, or shorten t_final"
        )
    coords = _space_time_coords(grid, times)
    values = snaps_b.reshape(n_samples, -1, 1)
    return OperatorSlab(sensors=sensors, coords=coords, values=values, grid=grid)


@dataclass(frozen=True)
class ParametricOperatorSlab:
    """Operator slab with a per-sample PDE-parameter vector.

    Attributes
    ----------
    sensors, coords, values, grid
        As in :class:`OperatorSlab`.
    parameters
        Parameter vectors of shape ``(F, n_parameters)``.
    """

    sensors: Tensor
    coords: Tensor
    values: Tensor
    grid: SpectralGrid1D
    parameters: Tensor

    def as_slab(self) -> OperatorSlab:
        return OperatorSlab(
            sensors=self.sensors,
            coords=self.coords,
            values=self.values,
            grid=self.grid,
        )


def make_parametric_heat_slab(
    *,
    n_samples: int = 16,
    n_grid: int = 64,
    n_sensors: int = 32,
    n_modes: int = 4,
    amplitude: float = 1.0,
    diffusivities: tuple[float, ...] | None = None,
    diffusivity_range: tuple[float, float] = (0.05, 0.2),
    t_final: float = 0.5,
    n_times: int = 11,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> ParametricOperatorSlab:
    """Heat slabs with a swept diffusivity parameter per sample."""
    rng = np.random.default_rng(seed)
    if diffusivities is None:
        lo, hi = diffusivity_range
        diffs = rng.uniform(lo, hi, size=n_samples)
    else:
        diffs = np.asarray(diffusivities, dtype=float)
        if diffs.shape[0] != n_samples:
            raise ValueError(
                f"diffusivities length {diffs.shape[0]} != n_samples={n_samples}"
            )
    length = 2.0 * torch.pi
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    fine = SensorGrid(points=grid.points().detach().cpu().numpy(), length=float(length))
    u0_np = sample_fourier_ics(
        n_samples, fine, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    u0 = torch.tensor(u0_np, dtype=dtype)
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    times_seq = [float(t) for t in times]
    snaps_list = []
    for i in range(n_samples):
        semi = heat_semidiscrete(grid, float(diffs[i]))
        # ETDRK4: exact linear advance; RK4 is unstable for large diffusivity.
        snaps, _ = method_of_lines(semi, u0[i], times_seq, integrator="etdrk4")
        snaps_list.append(snaps)
    snaps_b = torch.stack(snaps_list, dim=0)
    _assert_heat_maximum_principle(
        snaps_b, u0, name="parametric heat MOL reference"
    )
    coords = _space_time_coords(grid, times)
    values = snaps_b.reshape(n_samples, -1, 1)
    parameters = torch.tensor(diffs.reshape(n_samples, 1), dtype=dtype)
    return ParametricOperatorSlab(
        sensors=sensors,
        coords=coords,
        values=values,
        grid=grid,
        parameters=parameters,
    )


def make_parametric_burgers_slab(
    *,
    n_samples: int = 8,
    n_grid: int = 64,
    n_sensors: int = 32,
    n_modes: int = 2,
    amplitude: float = 0.5,
    viscosities: tuple[float, ...] | None = None,
    viscosity_range: tuple[float, float] = (0.03, 0.1),
    t_final: float = 0.5,
    n_times: int = 11,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> ParametricOperatorSlab:
    """Burgers slabs with a swept viscosity parameter per sample."""
    rng = np.random.default_rng(seed)
    if viscosities is None:
        lo, hi = viscosity_range
        nus = rng.uniform(lo, hi, size=n_samples)
    else:
        nus = np.asarray(viscosities, dtype=float)
        if nus.shape[0] != n_samples:
            raise ValueError(
                f"viscosities length {nus.shape[0]} != n_samples={n_samples}"
            )
    length = 2.0 * torch.pi
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    fine = SensorGrid(points=grid.points().detach().cpu().numpy(), length=float(length))
    u0_np = sample_fourier_ics(
        n_samples, fine, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    u0 = torch.tensor(u0_np, dtype=dtype)
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    times_seq = [float(t) for t in times]
    snaps_list = []
    for i in range(n_samples):
        semi = burgers_semidiscrete(grid, float(nus[i]))
        snaps, _ = method_of_lines(semi, u0[i], times_seq, integrator="etdrk4")
        snaps_list.append(snaps)
    snaps_b = torch.stack(snaps_list, dim=0)
    if not torch.isfinite(snaps_b).all():
        raise RuntimeError("parametric Burgers MOL produced non-finite values")
    coords = _space_time_coords(grid, times)
    values = snaps_b.reshape(n_samples, -1, 1)
    parameters = torch.tensor(nus.reshape(n_samples, 1), dtype=dtype)
    return ParametricOperatorSlab(
        sensors=sensors,
        coords=coords,
        values=values,
        grid=grid,
        parameters=parameters,
    )


def _sample_sine_ics(
    n_samples: int,
    x: np.ndarray,
    *,
    n_modes: int,
    amplitude: float,
    seed: int,
) -> np.ndarray:
    """Dirichlet-compatible sine modes on ``[0, L]`` (``u(0)=u(L)=0``)."""
    rng = np.random.default_rng(seed)
    L = float(x[-1])
    out = np.zeros((n_samples, x.size), dtype=float)
    for f in range(n_samples):
        for k in range(1, n_modes + 1):
            out[f] += rng.uniform(-amplitude, amplitude) * np.sin(k * np.pi * x / L)
    return out


def _dirichlet_heat_rhs(u: Tensor, diffusivity: float, dx: float) -> Tensor:
    du = torch.zeros_like(u)
    du[1:-1] = float(diffusivity) * (u[2:] - 2.0 * u[1:-1] + u[:-2]) / (dx * dx)
    return du


def _dirichlet_burgers_rhs(u: Tensor, viscosity: float, dx: float) -> Tensor:
    du = torch.zeros_like(u)
    ux = (u[2:] - u[:-2]) / (2.0 * dx)
    uxx = (u[2:] - 2.0 * u[1:-1] + u[:-2]) / (dx * dx)
    du[1:-1] = -u[1:-1] * ux + float(viscosity) * uxx
    return du


def _march_dirichlet(
    u0: Tensor,
    rhs_fn: Callable[[Tensor], Tensor],
    times: Tensor,
    *,
    dx: float,
) -> Tensor:
    """Explicit RK4 march with pinned endpoints."""
    snaps = [u0.clone()]
    u = u0.clone()
    u[0] = 0.0
    u[-1] = 0.0
    for ti in range(1, times.numel()):
        dt = float(times[ti] - times[ti - 1])
        k1 = rhs_fn(u)
        k2 = rhs_fn(u + 0.5 * dt * k1)
        k3 = rhs_fn(u + 0.5 * dt * k2)
        k4 = rhs_fn(u + dt * k3)
        u = u + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)
        u[0] = 0.0
        u[-1] = 0.0
        snaps.append(u.clone())
    return torch.stack(snaps, dim=0)


def _nonperiodic_space_time_coords(x: Tensor, times: Tensor) -> Tensor:
    xs = x.repeat(times.numel())
    ts = times.repeat_interleave(x.numel())
    return torch.stack([xs, ts], dim=-1)


def make_nonperiodic_parametric_heat_slab(
    *,
    n_samples: int = 8,
    n_grid: int = 64,
    n_sensors: int = 16,
    n_modes: int = 3,
    amplitude: float = 0.5,
    length: float = 1.0,
    diffusivities: tuple[float, ...] | None = None,
    diffusivity_range: tuple[float, float] = (0.05, 0.2),
    t_final: float = 0.2,
    n_times: int = 6,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> ParametricOperatorSlab:
    """Non-periodic heat on ``[0, L]`` with homogeneous Dirichlet BC."""
    rng = np.random.default_rng(seed)
    if diffusivities is None:
        lo, hi = diffusivity_range
        diffs = rng.uniform(lo, hi, size=n_samples)
    else:
        diffs = np.asarray(diffusivities, dtype=float)
    x_np = np.linspace(0.0, float(length), n_grid, endpoint=False)
    u0_np = _sample_sine_ics(
        n_samples, x_np, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    x = torch.tensor(x_np, dtype=dtype)
    u0 = torch.tensor(u0_np, dtype=dtype)
    dx = float(length / n_grid)
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    snaps_list = []
    for i in range(n_samples):
        D = float(diffs[i])

        def rhs(u: Tensor, *, _D: float = D) -> Tensor:
            return _dirichlet_heat_rhs(u, _D, dx)

        snaps_list.append(_march_dirichlet(u0[i], rhs, times, dx=dx))
    snaps_b = torch.stack(snaps_list, dim=0)
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    coords = _nonperiodic_space_time_coords(x, times)
    values = snaps_b.reshape(n_samples, -1, 1)
    parameters = torch.tensor(diffs.reshape(n_samples, 1), dtype=dtype)
    return ParametricOperatorSlab(
        sensors=sensors,
        coords=coords,
        values=values,
        grid=grid,
        parameters=parameters,
    )


def make_nonperiodic_parametric_burgers_slab(
    *,
    n_samples: int = 4,
    n_grid: int = 64,
    n_sensors: int = 16,
    n_modes: int = 2,
    amplitude: float = 0.25,
    length: float = 1.0,
    viscosities: tuple[float, ...] | None = None,
    viscosity_range: tuple[float, float] = (0.05, 0.15),
    t_final: float = 0.1,
    n_times: int = 5,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> ParametricOperatorSlab:
    """Non-periodic viscous Burgers on ``[0, L]`` with homogeneous Dirichlet BC."""
    rng = np.random.default_rng(seed)
    if viscosities is None:
        lo, hi = viscosity_range
        nus = rng.uniform(lo, hi, size=n_samples)
    else:
        nus = np.asarray(viscosities, dtype=float)
    x_np = np.linspace(0.0, float(length), n_grid, endpoint=False)
    u0_np = _sample_sine_ics(
        n_samples, x_np, n_modes=n_modes, amplitude=amplitude, seed=seed
    )
    x = torch.tensor(x_np, dtype=dtype)
    u0 = torch.tensor(u0_np, dtype=dtype)
    dx = float(length / n_grid)
    idx = torch.linspace(0, n_grid, steps=n_sensors + 1, dtype=torch.long)[:-1]
    sensors = u0[:, idx]
    times = torch.linspace(0.0, t_final, n_times, dtype=dtype)
    snaps_list = []
    for i in range(n_samples):
        nu = float(nus[i])

        def rhs(u: Tensor, *, _nu: float = nu) -> Tensor:
            return _dirichlet_burgers_rhs(u, _nu, dx)

        snaps_list.append(_march_dirichlet(u0[i], rhs, times, dx=dx))
    snaps_b = torch.stack(snaps_list, dim=0)
    grid = SpectralGrid1D(n_grid, float(length), dtype=dtype)
    coords = _nonperiodic_space_time_coords(x, times)
    values = snaps_b.reshape(n_samples, -1, 1)
    parameters = torch.tensor(nus.reshape(n_samples, 1), dtype=dtype)
    return ParametricOperatorSlab(
        sensors=sensors,
        coords=coords,
        values=values,
        grid=grid,
        parameters=parameters,
    )


@dataclass(frozen=True)
class ManufacturedPoissonSlab:
    """Manufactured Poisson slab with variable diffusivity / disk radius.

    The reference solution is ``u = 1 - r^2 / R^2`` on a disk of radius ``R``
  with ``D(x,y) = D0 + D1 r^2``. Residual accuracy is optimised, not proven.
    """

    sensors: Tensor
    coords: Tensor
    values: Tensor
    source: Tensor
    parameters: Tensor
    radii: Tensor


def _manufactured_disk_poisson_fields(
    coords: Tensor,
    *,
    radius: float,
    d0: float,
    d1: float,
) -> tuple[Tensor, Tensor]:
    x = coords[:, 0]
    y = coords[:, 1]
    r2 = x * x + y * y
    R2 = float(radius) ** 2
    u = 1.0 - r2 / R2
    f = 4.0 * float(d0) / R2 + 8.0 * float(d1) * r2 / R2
    return u, f


def make_variable_diffusivity_disk_poisson(
    *,
    n_samples: int = 8,
    n_grid: int = 32,
    n_sensors: int = 8,
    radii: tuple[float, ...] | None = None,
    radius_range: tuple[float, float] = (0.6, 1.0),
    d0: float = 0.5,
    d1: float = 0.2,
    seed: int = 0,
    dtype: torch.dtype = torch.float64,
) -> ManufacturedPoissonSlab:
    """Variable-radius disk Poisson family with a closed-form manufactured solution."""
    rng = np.random.default_rng(seed)
    if radii is None:
        lo, hi = radius_range
        Rs = rng.uniform(lo, hi, size=n_samples)
    else:
        Rs = np.asarray(radii, dtype=float)
    xs = np.linspace(-1.0, 1.0, n_grid)
    ys = np.linspace(-1.0, 1.0, n_grid)
    xx, yy = np.meshgrid(xs, ys, indexing="ij")
    coords_np = np.stack([xx.ravel(), yy.ravel()], axis=-1)
    coords = torch.tensor(coords_np, dtype=dtype)
    mask = coords_np[:, 0] ** 2 + coords_np[:, 1] ** 2
    values_list: list[Tensor] = []
    source_list: list[Tensor] = []
    sensor_rows: list[Tensor] = []
    params = []
    for R in Rs:
        inside = mask <= R * R
        u, f = _manufactured_disk_poisson_fields(
            coords, radius=float(R), d0=d0, d1=d1
        )
        u = torch.where(torch.tensor(inside, device=u.device), u, torch.zeros_like(u))
        values_list.append(u.unsqueeze(-1))
        source_list.append(f.unsqueeze(-1))
        sensor_idx = np.linspace(0, coords_np.shape[0], num=n_sensors + 1, dtype=int)[:-1]
        sensor_rows.append(u[sensor_idx])
        params.append([d0, d1])
    return ManufacturedPoissonSlab(
        sensors=torch.stack(sensor_rows, dim=0),
        coords=coords,
        values=torch.stack(values_list, dim=0),
        source=torch.stack(source_list, dim=0),
        parameters=torch.tensor(params, dtype=dtype),
        radii=torch.tensor(Rs.reshape(n_samples, 1), dtype=dtype),
    )


__all__ = [
    "ManufacturedPoissonSlab",
    "OperatorSlab",
    "ParametricOperatorSlab",
    "make_burgers_slab",
    "make_heat_slab",
    "make_ks_slab",
    "make_nonperiodic_parametric_burgers_slab",
    "make_nonperiodic_parametric_heat_slab",
    "make_parametric_burgers_slab",
    "make_parametric_heat_slab",
    "make_variable_diffusivity_disk_poisson",
]
