# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Backend-agnostic gauge-theory schemas and numeric kernels (pure Python)."""

from __future__ import annotations

from omnibias.geometry.gauge._core.connection import (
    EUCLIDEAN_4D,
    MINKOWSKI_4D,
    GaugeConnectionSpec,
    connection_component_names,
    gauge_connection_spec,
)
from omnibias.geometry.gauge._core.covariant_jet import (
    ADJOINT_BIANCHI,
    ADJOINT_YM,
    LEGAL_ADJOINT_1FORM_ATOMS,
    LEGAL_SINGLET_ATOMS,
    SELF_DUAL_ACTION_OVER_TOPOLOGICAL,
    SINGLET_BIANCHI_SQ,
    SINGLET_SELF_DUAL_SQ,
    SINGLET_TR_F2,
    SINGLET_TR_F_FTILDE,
    SINGLET_YM_SQ,
    GaugeCovariantJet,
    assert_library_gauge_legal,
    covariant_singlet_columns,
    evaluate_gauge_law_gate,
    gauge_equivariance_defect,
    global_gauge_transform_connection,
    random_special_unitary,
)
from omnibias.geometry.gauge._core.forms import (
    LieAlgebraValuedForm,
    hodge_star_flat,
    levi_civita_symbol,
    permutation_sign,
    sorted_index_sets,
    wedge,
)
from omnibias.geometry.gauge._core.instanton import bpst_instanton_arrays, thooft_eta
from omnibias.geometry.gauge._core.invariants import (
    IMPLEMENTED_INVARIANT_NAMES,
    MAX_SEARCHABLE_DIM6_SU3,
    SINGLET_DF_SQ,
    SINGLET_TR_F3,
    GaugeInvariantDictionary,
    InvariantAtom,
    enumerate_gauge_invariants,
    evaluate_named_invariants,
    representation_complexity,
)
from omnibias.geometry.gauge._core.jet_dimension import (
    SU3_4D_COORDINATE_2JET,
    SU3_4D_DF_BIANCHI_REDUCED,
    SU3_4D_DF_RAW,
    SU3_4D_F,
    bianchi_reduced_df_dimension,
    raw_connection_jet_dimension,
    raw_covariant_fiber_dimension,
    refuse_component_fiber_library,
    refuse_coordinate_jet_library,
    refuse_flattened_adjoint_library,
)
from omnibias.geometry.gauge._core.lie_algebra import (
    LieAlgebra,
    as_lie_algebra,
    su,
    u1,
)
from omnibias.geometry.gauge._core.representation import (
    Irrep,
    adjoint,
    adjoint_rep_matrices,
    antisymmetric_power,
    antisymmetric_power_rep_matrices,
    branching_to_subalgebra,
    character,
    dimension,
    dual_coxeter_number,
    dynkin_index,
    fundamental,
    irrep,
    quadratic_casimir,
    su2_spin_matrices,
    symmetric_power,
    symmetric_power_rep_matrices,
    tensor_product_decomposition,
    trivial,
    weight_multiplicities,
)

__all__ = [
    "ADJOINT_BIANCHI",
    "ADJOINT_YM",
    "EUCLIDEAN_4D",
    "GaugeConnectionSpec",
    "GaugeCovariantJet",
    "GaugeInvariantDictionary",
    "IMPLEMENTED_INVARIANT_NAMES",
    "InvariantAtom",
    "Irrep",
    "LEGAL_ADJOINT_1FORM_ATOMS",
    "LEGAL_SINGLET_ATOMS",
    "LieAlgebra",
    "LieAlgebraValuedForm",
    "MAX_SEARCHABLE_DIM6_SU3",
    "MINKOWSKI_4D",
    "SELF_DUAL_ACTION_OVER_TOPOLOGICAL",
    "SINGLET_BIANCHI_SQ",
    "SINGLET_DF_SQ",
    "SINGLET_SELF_DUAL_SQ",
    "SINGLET_TR_F2",
    "SINGLET_TR_F3",
    "SINGLET_TR_F_FTILDE",
    "SINGLET_YM_SQ",
    "SU3_4D_COORDINATE_2JET",
    "SU3_4D_DF_BIANCHI_REDUCED",
    "SU3_4D_DF_RAW",
    "SU3_4D_F",
    "adjoint",
    "adjoint_rep_matrices",
    "antisymmetric_power",
    "antisymmetric_power_rep_matrices",
    "as_lie_algebra",
    "assert_library_gauge_legal",
    "bianchi_reduced_df_dimension",
    "bpst_instanton_arrays",
    "branching_to_subalgebra",
    "character",
    "connection_component_names",
    "covariant_singlet_columns",
    "dimension",
    "dual_coxeter_number",
    "dynkin_index",
    "enumerate_gauge_invariants",
    "evaluate_gauge_law_gate",
    "evaluate_named_invariants",
    "fundamental",
    "gauge_connection_spec",
    "gauge_equivariance_defect",
    "global_gauge_transform_connection",
    "hodge_star_flat",
    "irrep",
    "levi_civita_symbol",
    "permutation_sign",
    "quadratic_casimir",
    "random_special_unitary",
    "raw_connection_jet_dimension",
    "raw_covariant_fiber_dimension",
    "refuse_component_fiber_library",
    "refuse_coordinate_jet_library",
    "refuse_flattened_adjoint_library",
    "representation_complexity",
    "sorted_index_sets",
    "su",
    "su2_spin_matrices",
    "symmetric_power",
    "symmetric_power_rep_matrices",
    "tensor_product_decomposition",
    "thooft_eta",
    "trivial",
    "u1",
    "wedge",
    "weight_multiplicities",
]
