# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-omnibias-Commercial
# Copyright (C) 2026 Derivon
"""omnibias-dynamics: computer-assisted dynamics on the validated tower.

Rigorous (interval / Taylor-model) tools for nonlinear dynamical systems, built
on the QR-Lohner validated flow, the Newton-Kantorovich / radii-polynomial
existence machinery, and the closed-form variational tower in
:mod:`omnibias.core.verified`:

* **variational / monodromy flow** -- propagate a state *and* its fundamental
  (variational) matrix rigorously, the basis for Floquet / stability analysis;
* **Poincare-section enclosures** -- validated crossing locations on a hyperplane;
* **certified Lyapunov-exponent bounds** -- two-sided enclosures of the leading
  exponent from the validated variational flow;
* **periodic-orbit existence** -- a radii-polynomial proof that a true periodic
  orbit lives in an explicit ball around a numerical guess.

Each enclosure has its stated input and scope contract. The legacy crossing
API does not certify a first transversal return; the stronger source-bound
event API lives in :mod:`omnibias.dynamics.return_maps`.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError as _PkgNotFound
from importlib.metadata import version as _pkg_version

from omnibias.dynamics._core import (
    ConeHyperbolicityCertificate,
    DiscretePeriodicOrbit,
    LyapunovBounds,
    PeriodicOrbitCertificate,
    PoincareCrossing,
    PoincareJetCrossing,
    PoincareSection,
    VariationalJetRun,
    VariationalState,
    cat_map_jacobian,
    cat_map_unstable_generator,
    certified_cone_hyperbolicity,
    certified_lyapunov_exponent,
    discrete_periodic_point,
    doubling_map_jacobian,
    harmonic_oscillator,
    hopf_normal_form,
    linear_system,
    monodromy_determinant,
    monodromy_matrix,
    monodromy_trace,
    poincare_map,
    poincare_map_jet,
    prove_periodic_orbit,
    radial_logistic,
    rotation_jacobian,
    sigma_oscillator_field,
    spectral_radius_bound,
    step_transition_matrix,
    variational_flow,
    variational_flow_jet,
    variational_step,
    vector_field_from_sigma_tower,
)
from omnibias.dynamics._core.jet_world import JetWorldConfig, predict_next_jet
from omnibias.dynamics.abelian import (
    AbelianCoefficientBox,
    AbelianEvaluator,
    AbelianFormalVerification,
    AbelianInitialData,
    AbelianPeriodEvaluator,
    AbelianProblem,
    AbelianUniformCoverCertificate,
    AbelianUniformCoverNode,
    AbelianUniformFormalVerification,
    AbelianZeroCountCertificate,
    ActionZeroFreeRectangleCertificate,
    IntervalCoefficientAbelianEvaluator,
    RationalCoefficientInterval,
    build_abelian_evaluator,
    build_abelian_period_evaluator,
    certify_abelian_uniform_cover,
    certify_abelian_zero_count,
    certify_action_zero_free_rectangle,
    certify_cubic_initial_data,
    certify_simple_abelian_zero,
    certify_simple_mixed_abelian_zero,
    named_cubic_abelian_problem,
    named_genuine_cubic_abelian_problem,
    verify_abelian_uniform_cover,
    verify_abelian_uniform_cover_formally,
    verify_abelian_zero_count,
    verify_abelian_zero_count_formally,
)
from omnibias.dynamics.bautin import (
    BautinBasis,
    bautin_basis,
    bautin_quadratic_family,
    center_membership,
    hamiltonian_center_example,
    nonzero_focus_example,
)
from omnibias.dynamics.compactify import (
    InfiniteSingularity,
    PlanarPolynomialField,
    PoincareChart,
    PoincareCompactificationCertificate,
    PoincareCompactificationFormalVerification,
    certify_poincare_compactification,
    infinite_singular_points,
    poincare_chart,
    verify_poincare_compactification,
    verify_poincare_compactification_formally,
)
from omnibias.dynamics.dulac import (
    DulacCyclicityCertificate,
    DulacExpansion,
    DulacFormalVerification,
    DulacTerm,
    DulacUniformCoverCertificate,
    DulacUniformCoverNode,
    DulacUniformFormalVerification,
    RationalInterval,
    certify_dulac_cyclicity,
    certify_dulac_uniform_cover,
    displacement_expansion,
    dulac_to_confluent,
    enclose_dulac_term,
    verify_dulac_cyclicity,
    verify_dulac_cyclicity_formally,
    verify_dulac_uniform_cover,
    verify_dulac_uniform_cover_formally,
)
from omnibias.dynamics.focal import (
    FocalCertificate,
    FocalFormalVerification,
    LyapunovQuantities,
    NormalizedMonodromicField,
    certify_focal_values,
    focal_order,
    lyapunov_quantities,
    normalize_monodromic,
    verify_focal_values,
    verify_focal_values_formally,
)
from omnibias.dynamics.graphic import (
    GraphicCyclicityCertificate,
    GraphicTarget,
    HyperbolicSaddle,
    certify_graphic_cyclicity,
    named_irrational_hyperbolic_graphic,
    named_open_saddle_node_infinity_graphic,
    named_rational_hyperbolic_graphic,
    named_resonant_homoclinic_graphic,
    verify_graphic_cyclicity,
)
from omnibias.dynamics.hilbert16_ledger import (
    DRR_CASES,
    GATE_NAMES,
    H16Ledger,
    H16LedgerCertificate,
    H16Obligation,
    H16Status,
    LedgerCheckResult,
    certify_h16_ledger,
    check_ledger,
    default_h16_ledger,
    derived_parent_flags,
    payload_earns_parent_claim,
    verify_h16_ledger,
)
from omnibias.dynamics.membership import (
    CollarGridNode,
    CollarMembershipCertificate,
    MembershipStatus,
    UniqueCycleResult,
    certify_collar_membership,
    verify_collar_membership,
)
from omnibias.dynamics.saddle_normal_form import (
    DerivedDulacExpansion,
    DiagonalSaddleField,
    ResonantNormalForm,
    ResonantNormalFormCertificate,
    ResonantNormalFormFormalVerification,
    certify_resonant_normal_form,
    derive_return_map,
    diagonalize_saddle,
    dulac_corner_expansion,
    resonant_normal_form,
    verify_resonant_normal_form,
    verify_resonant_normal_form_formally,
)

try:
    __version__ = _pkg_version("omnibias-dynamics")
except _PkgNotFound:  # pragma: no cover - bare source checkout
    __version__ = "0.0.0+unknown"

# Founding-idea lineage (see docs/theory.md "Two senses of collapse").
__lineage__ = "bias collapse"

__all__ = [
    "AbelianCoefficientBox",
    "AbelianEvaluator",
    "AbelianFormalVerification",
    "AbelianInitialData",
    "AbelianPeriodEvaluator",
    "AbelianProblem",
    "AbelianUniformCoverCertificate",
    "AbelianUniformCoverNode",
    "AbelianUniformFormalVerification",
    "AbelianZeroCountCertificate",
    "ActionZeroFreeRectangleCertificate",
    "BautinBasis",
    "CollarGridNode",
    "CollarMembershipCertificate",
    "ConeHyperbolicityCertificate",
    "DRR_CASES",
    "DerivedDulacExpansion",
    "DiagonalSaddleField",
    "DiscretePeriodicOrbit",
    "DulacCyclicityCertificate",
    "DulacExpansion",
    "DulacFormalVerification",
    "DulacTerm",
    "DulacUniformCoverCertificate",
    "DulacUniformCoverNode",
    "DulacUniformFormalVerification",
    "FocalCertificate",
    "FocalFormalVerification",
    "GATE_NAMES",
    "GraphicCyclicityCertificate",
    "GraphicTarget",
    "H16Ledger",
    "H16LedgerCertificate",
    "H16Obligation",
    "H16Status",
    "HyperbolicSaddle",
    "InfiniteSingularity",
    "IntervalCoefficientAbelianEvaluator",
    "JetWorldConfig",
    "LedgerCheckResult",
    "LyapunovBounds",
    "LyapunovQuantities",
    "MembershipStatus",
    "NormalizedMonodromicField",
    "PeriodicOrbitCertificate",
    "PlanarPolynomialField",
    "PoincareChart",
    "PoincareCompactificationCertificate",
    "PoincareCompactificationFormalVerification",
    "PoincareCrossing",
    "PoincareJetCrossing",
    "PoincareSection",
    "RationalCoefficientInterval",
    "RationalInterval",
    "ResonantNormalForm",
    "ResonantNormalFormCertificate",
    "ResonantNormalFormFormalVerification",
    "UniqueCycleResult",
    "VariationalJetRun",
    "VariationalState",
    "__lineage__",
    "__version__",
    "bautin_basis",
    "bautin_quadratic_family",
    "build_abelian_evaluator",
    "build_abelian_period_evaluator",
    "cat_map_jacobian",
    "cat_map_unstable_generator",
    "center_membership",
    "certified_cone_hyperbolicity",
    "certified_lyapunov_exponent",
    "certify_abelian_uniform_cover",
    "certify_abelian_zero_count",
    "certify_action_zero_free_rectangle",
    "certify_collar_membership",
    "certify_cubic_initial_data",
    "certify_dulac_cyclicity",
    "certify_dulac_uniform_cover",
    "certify_focal_values",
    "certify_graphic_cyclicity",
    "certify_h16_ledger",
    "certify_poincare_compactification",
    "certify_resonant_normal_form",
    "certify_simple_abelian_zero",
    "certify_simple_mixed_abelian_zero",
    "check_ledger",
    "default_h16_ledger",
    "derive_return_map",
    "derived_parent_flags",
    "diagonalize_saddle",
    "discrete_periodic_point",
    "displacement_expansion",
    "doubling_map_jacobian",
    "dulac_corner_expansion",
    "dulac_to_confluent",
    "enclose_dulac_term",
    "focal_order",
    "hamiltonian_center_example",
    "harmonic_oscillator",
    "hopf_normal_form",
    "infinite_singular_points",
    "linear_system",
    "lyapunov_quantities",
    "monodromy_determinant",
    "monodromy_matrix",
    "monodromy_trace",
    "named_cubic_abelian_problem",
    "named_genuine_cubic_abelian_problem",
    "named_irrational_hyperbolic_graphic",
    "named_open_saddle_node_infinity_graphic",
    "named_rational_hyperbolic_graphic",
    "named_resonant_homoclinic_graphic",
    "nonzero_focus_example",
    "normalize_monodromic",
    "payload_earns_parent_claim",
    "poincare_chart",
    "poincare_map",
    "poincare_map_jet",
    "predict_next_jet",
    "prove_periodic_orbit",
    "radial_logistic",
    "resonant_normal_form",
    "rotation_jacobian",
    "sigma_oscillator_field",
    "spectral_radius_bound",
    "step_transition_matrix",
    "variational_flow",
    "variational_flow_jet",
    "variational_step",
    "vector_field_from_sigma_tower",
    "verify_abelian_uniform_cover",
    "verify_abelian_uniform_cover_formally",
    "verify_abelian_zero_count",
    "verify_abelian_zero_count_formally",
    "verify_collar_membership",
    "verify_dulac_cyclicity",
    "verify_dulac_cyclicity_formally",
    "verify_dulac_uniform_cover",
    "verify_dulac_uniform_cover_formally",
    "verify_focal_values",
    "verify_focal_values_formally",
    "verify_graphic_cyclicity",
    "verify_h16_ledger",
    "verify_poincare_compactification",
    "verify_poincare_compactification_formally",
    "verify_resonant_normal_form",
    "verify_resonant_normal_form_formally",
]
