# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-omnibias-Commercial
# Copyright (C) 2026 Derivon
r"""The Bautin (focal-value) ideal, its Groebner basis, and center membership.

:mod:`omnibias.dynamics.focal` computes each Poincare-Lyapunov focal value
``V_k`` as a :class:`~omnibias.holonomic._core.poly_n.PolyN` in the field's
symbolic parameters. The **ideal** ``(V_1, ..., V_N)`` those quantities
generate is gauge-invariant (unlike any single ``V_k`` beyond the first
nonzero one, see the honesty note in :mod:`omnibias.dynamics.focal`) and its
zero set is exactly the (truncated) center variety: a parameter point makes
*every* focal value vanish -- and hence, by the classical Poincare-Lyapunov
theorem plus (for the quadratic family) Bautin's finiteness theorem, is a
genuine center -- iff it lies in this variety.

This module computes the ideal's :func:`bautin_basis` with the exact-``Q``
Buchberger engine in :mod:`omnibias.holonomic._core.groebner` and answers
:func:`center_membership` queries against it, both with exact cofactor
witnesses. **What this module does not do:** it does not re-derive or assert
Bautin's theorem that three focal values already generate the full ideal for
the quadratic family -- ``bautin_basis`` reports whatever the Groebner basis
of the *supplied, truncated* generator list happens to be, and
``cyclicity_bound = basis_length - 1`` is always reported alongside
``bautin_ideal_stabilization_proved = False``. Confirming that supplying a
4th, 5th, ... generator never enlarges the ideal is exactly the
un-formalized mathematical content of Bautin's theorem; this module gives you
the machinery to *check* finite-order stabilization on any concrete instance,
not a proof that it holds in general.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from fractions import Fraction

from omnibias.core.proof.certificate import Cert, make_certificate, verify_certificate_digest
from omnibias.core.proof.realization_replay import source_digest
from omnibias.dynamics.focal import LyapunovQuantities
from omnibias.holonomic._core.groebner import (
    DEFAULT_GROEBNER_BUDGET,
    GroebnerBudget,
    IdealMembership,
    MonomialOrderName,
    ideal_member,
    radical_member,
    reduced_groebner_basis,
    verify_ideal_membership,
)
from omnibias.holonomic._core.poly_n import PolyN

__all__ = [
    "BautinBasis",
    "BautinMembershipCertificate",
    "bautin_basis",
    "bautin_quadratic_family",
    "certify_bautin_membership",
    "center_membership",
    "hamiltonian_center_example",
    "nonzero_focus_example",
    "verify_bautin_membership",
    "verify_bautin_stabilization",
]


@dataclass(frozen=True)
class BautinBasis:
    """A Groebner basis of the ideal generated by a truncated focal-value list.

    ``cyclicity_bound = basis_length - 1`` is a **conditional** headline
    number: it equals the true cyclicity bound only if the supplied
    generators already span the full Bautin ideal (``stabilization``, not
    re-derived here -- see the module docstring).
    """

    generators: tuple[PolyN, ...]
    monomial_order: MonomialOrderName
    basis: tuple[PolyN, ...]
    basis_length: int
    cyclicity_bound: int
    bautin_ideal_stabilization_proved: bool = False
    finite_order_stabilization_verified: bool = False
    bautin_stabilization_verified_to_order: int = 0


def bautin_basis(
    quantities: LyapunovQuantities,
    *,
    monomial_order: MonomialOrderName = "degrevlex",
    budget: GroebnerBudget = DEFAULT_GROEBNER_BUDGET,
) -> BautinBasis:
    """Reduced Groebner basis of the ideal generated by every computed focal value.

    ``quantities`` must carry at least one symbolic parameter
    (``quantities.param_nvars >= 1``) -- a purely numeric field's focal
    values are elements of ``Q``, not polynomials, and generate either the
    zero ideal or all of ``Q[]``, which is not an interesting Bautin
    computation.
    """
    if quantities.param_nvars < 1:
        raise ValueError("bautin_basis requires at least one symbolic parameter (param_nvars >= 1)")
    generators = tuple(value for _, value in quantities.quantities)
    basis = reduced_groebner_basis(list(generators), monomial_order, budget=budget)
    return BautinBasis(generators, monomial_order, basis, len(basis), len(basis) - 1)


def verify_bautin_stabilization(
    quantities: LyapunovQuantities,
    *,
    reference_count: int = 3,
    monomial_order: MonomialOrderName = "degrevlex",
    budget: GroebnerBudget = DEFAULT_GROEBNER_BUDGET,
) -> BautinBasis:
    """Check that focal values beyond the first ``reference_count`` lie in their ideal.

    This verifies Bautin's stabilization to the supplied truncation order only.
    It is not Bautin's all-orders theorem, so
    ``bautin_ideal_stabilization_proved`` remains false even after every
    supplied higher value has passed. A finite ideal chain can plateau for
    arbitrarily many steps and enlarge later unless an independent recurrence
    or termination theorem controls every uncomputed focal value.
    """
    if reference_count < 1:
        raise ValueError("reference_count must be positive")
    if len(quantities.quantities) < reference_count:
        raise ValueError("not enough focal values were computed")
    basis = bautin_basis(quantities, monomial_order=monomial_order, budget=budget)
    references = tuple(value for _, value in quantities.quantities[:reference_count])
    reference_degrees = [degree for degree, _ in quantities.quantities[:reference_count]]
    verified_order = max(reference_degrees)
    stabilized = True
    if len(quantities.quantities) <= reference_count:
        return BautinBasis(
            basis.generators,
            basis.monomial_order,
            basis.basis,
            basis.basis_length,
            basis.cyclicity_bound,
            bautin_ideal_stabilization_proved=False,
            finite_order_stabilization_verified=False,
            bautin_stabilization_verified_to_order=verified_order,
        )
    for degree, value in quantities.quantities[reference_count:]:
        membership = center_membership(value, references, monomial_order, radical=False, budget=budget)
        if not membership.is_member:
            stabilized = False
            break
        verified_order = degree
    return BautinBasis(
        basis.generators,
        basis.monomial_order,
        basis.basis,
        basis.basis_length,
        basis.cyclicity_bound,
        bautin_ideal_stabilization_proved=False,
        finite_order_stabilization_verified=stabilized,
        bautin_stabilization_verified_to_order=verified_order,
    )


@dataclass(frozen=True)
class BautinMembershipCertificate:
    """A kernel-checkable exact-Q ideal-membership witness."""

    candidate: PolyN
    generators: tuple[PolyN, ...]
    membership: IdealMembership
    source_digest: str
    seal: Cert


def _poly_rows(poly: PolyN) -> list[dict[str, object]]:
    return [
        {
            "monomial": list(mon),
            "terms": [[coeff.numerator, coeff.denominator]],
            "rhs": 0,
        }
        for mon, coeff in sorted(poly.terms.items())
    ]


def _replay_bautin_membership(
    candidate: PolyN,
    generators: Sequence[PolyN],
    membership: IdealMembership,
    *,
    radical: bool,
) -> bool:
    if not radical:
        return verify_ideal_membership(candidate, generators, membership)
    nvars = candidate.nvars
    embedded_generators = [
        PolyN(nvars + 1, {(*mon, 0): coeff for mon, coeff in generator.terms.items()})
        for generator in generators
    ]
    embedded_candidate = PolyN(
        nvars + 1, {(*mon, 0): coeff for mon, coeff in candidate.terms.items()}
    )
    t = PolyN.var(nvars + 1, nvars)
    rabinowitsch = PolyN.const(nvars + 1, 1) - t * embedded_candidate
    system = [*embedded_generators, rabinowitsch]
    one = PolyN.const(nvars + 1, 1)
    return verify_ideal_membership(one, system, membership)


def certify_bautin_membership(
    candidate: PolyN,
    generators: Sequence[PolyN],
    *,
    monomial_order: MonomialOrderName = "degrevlex",
    radical: bool = True,
    budget: GroebnerBudget = DEFAULT_GROEBNER_BUDGET,
) -> BautinMembershipCertificate:
    """Seal an exact-Q Bautin ideal-membership witness with cofactors."""
    membership = center_membership(
        candidate, generators, monomial_order, radical=radical, budget=budget
    )
    if not membership.is_member:
        raise ValueError("candidate is not in the declared ideal")
    if not _replay_bautin_membership(candidate, generators, membership, radical=radical):
        raise ValueError("ideal membership witness failed replay")
    payload = {
        "type": "bautin_ideal_membership_q",
        "candidate": _poly_rows(candidate),
        "generators": [_poly_rows(generator) for generator in generators],
        "cofactors": [_poly_rows(cofactor) for cofactor in membership.cofactors],
        "remainder": _poly_rows(membership.remainder),
        "radical": radical,
    }
    digest = source_digest(payload)
    seal = make_certificate(
        claim="Exact-Q Bautin ideal membership with replayable cofactor witness.",
        payload=payload,
        honesty={
            "bautin_ideal_membership_proved": True,
            "full_hilbert16_solved": False,
        },
        meta={"transcend_backend": "not_used"},
    )
    return BautinMembershipCertificate(candidate, tuple(generators), membership, digest, seal)


def verify_bautin_membership(certificate: BautinMembershipCertificate) -> bool:
    if not verify_certificate_digest(certificate.seal):
        return False
    payload = certificate.seal["payload"]
    if payload.get("type") != "bautin_ideal_membership_q":
        return False
    if source_digest(payload) != certificate.source_digest:
        return False
    radical = bool(payload.get("radical", True))
    return _replay_bautin_membership(
        certificate.candidate,
        certificate.generators,
        certificate.membership,
        radical=radical,
    )


def center_membership(
    candidate: PolyN,
    generators: Sequence[PolyN],
    monomial_order: MonomialOrderName = "degrevlex",
    *,
    radical: bool = True,
    budget: GroebnerBudget = DEFAULT_GROEBNER_BUDGET,
) -> IdealMembership:
    """Exact membership of ``candidate`` in the ideal ``(generators)``.

    Defaults to **radical** membership (``radical=True``), i.e. Rabinowitsch
    ``1 in (generators, 1 - t*candidate)``: because the center variety is a
    zero set, a parameter substitution can vanish on that variety without
    ``candidate`` (e.g. a would-be next focal value ``V_{N+1}``) lying in the
    ideal itself. Pass ``radical=False`` for plain ideal membership with a
    polynomial cofactor witness. Either way the returned
    :class:`~omnibias.holonomic._core.groebner.IdealMembership` carries a
    witness :func:`~omnibias.holonomic._core.groebner.verify_ideal_membership`
    can replay without rerunning Buchberger.
    """
    if radical:
        return radical_member(candidate, generators, monomial_order, budget=budget)
    return ideal_member(candidate, generators, monomial_order, budget=budget)


def bautin_quadratic_family() -> tuple[PolyN, PolyN]:
    """Bautin's normalized quadratic weak-focus family, 5 free parameters.

    Variables ``0, 1`` are ``x, y``; variables ``2..6`` are the parameters
    ``a2, a3, a4, a5, a6`` in that order, matching the normal form used
    throughout the quadratic center-focus literature (weak focus at the
    origin, linear part the standard rotation, quadratic part
    ``P = -a3 x^2 + (2a2+a5) xy + a6 y^2``, ``Q = a2 x^2 + (2a3+a4) xy - a2
    y^2``; see e.g. Bautin (1954) or the survey by Artes, Llibre & Vulpe on
    the quadratic center-focus problem). This module does **not** assert or
    reproduce Bautin's published closed-form ``V_1, V_2, V_3`` from memory:
    :func:`~omnibias.dynamics.focal.lyapunov_quantities` computes them fresh
    and mechanically from this normal form, and the regression suite
    cross-checks the resulting :func:`bautin_basis` against an independent
    sympy Groebner computation of the *same three polynomials* -- never
    against a hand-recalled literature formula.
    """
    nvars = 7
    x, y = PolyN.var(nvars, 0), PolyN.var(nvars, 1)
    a2, a3, a4, a5, a6 = (PolyN.var(nvars, i) for i in range(2, 7))
    p = -a3 * x * x + (a2 * 2 + a5) * x * y + a6 * y * y
    q = a2 * x * x + (a3 * 2 + a4) * x * y - a2 * y * y
    return p, q


def hamiltonian_center_example(h_pert: PolyN | None = None) -> tuple[PolyN, PolyN]:
    """A structurally guaranteed formal center: ``P = -dH/dy``, ``Q = dH/dx``.

    For ``H = (x^2+y^2)/2 + h_pert`` this vector field satisfies
    ``X(H) = H_x*(-H_y) + H_y*H_x = 0`` identically, by the antisymmetry of
    that expression, for **any** ``h_pert`` -- a pure algebraic fact, not a
    literature lookup or a numerically-observed coincidence. Every computed
    focal value through any truncation order must therefore come out exactly
    zero; the regression suite exercises this as a hard equality, not merely
    asserts it in a docstring. ``h_pert`` defaults to a fixed cubic
    (``x^3/3 - x*y^2``) when omitted; it must be bivariate and start at total
    degree ``>= 3``.
    """
    if h_pert is None:
        x2, y2 = PolyN.var(2, 0), PolyN.var(2, 1)
        h_pert = x2 * x2 * x2 * Fraction(1, 3) - x2 * y2 * y2
    if h_pert.nvars != 2:
        raise ValueError("h_pert must be a bivariate polynomial (nvars == 2)")
    low = min((mon[0] + mon[1] for mon in h_pert.terms), default=99)
    if h_pert.terms and low < 3:
        raise ValueError("h_pert must start at total degree >= 3")
    p = -h_pert.partial(1)
    q = h_pert.partial(0)
    return p, q


def nonzero_focus_example() -> tuple[PolyN, PolyN]:
    """A numeric weak focus of order 1: ``P = xy + x^3``, ``Q = y^3``.

    The first (and, in this numeric instance, only meaningful) focal value
    is exactly ``3/4`` at degree ``4`` -- cross-checked against an
    independent sympy re-derivation in the regression suite, not asserted
    from memory.
    """
    x, y = PolyN.var(2, 0), PolyN.var(2, 1)
    p = x * y + x * x * x
    q = y * y * y
    return p, q
