# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-omnibias-Commercial
# Copyright (C) 2026 Derivon
r"""Exact-Q Poincare-Lyapunov focal values via the rotation operator ``L``.

Given a monodromic linear part normalized to ``x' = -y + P(x,y)``,
``y' = x + Q(x,y)`` (:func:`normalize_monodromic`), the classical
successive-approximation construction builds a formal first integral
``F = (x^2+y^2)/2 + F_3 + F_4 + ...`` degree by degree. The operator
``L(f) = -y*df/dx + x*df/dy`` is bijective on homogeneous polynomials of odd
degree and has a one-dimensional cokernel spanned by ``(x^2+y^2)^j`` on
homogeneous degree ``2j``; the obstruction there is the focal (Poincare-
Lyapunov) value at that degree. :func:`lyapunov_quantities` solves this
degree-by-degree homological equation exactly over ``Q`` (or over
``Q[params]`` when ``p, q`` carry extra symbolic-parameter variables), using
plain exact rational linear algebra -- no floating point, no truncated
series.

**Honesty, read before quoting a single ``V_k``:** the one-dimensional kernel
of ``L`` at each even degree is a genuine gauge freedom. This module fixes it
by requiring the new term to be orthogonal (under the standard monomial
pairing) to a fixed left-null covector, a specific, declared, reproducible
choice -- not *the* literature convention. The **first** nonvanishing focal
value in a run is a bona fide gauge-independent dynamical invariant (a weak
focus of that order, by the classical Poincare-Lyapunov theorem); values
computed **after** it are gauge-dependent numbers (this is cross-checked
against an independent sympy re-derivation in the test suite: the same
system, re-normalized with a *different* gauge, reproduces a *different*
value beyond the first nonzero one, and the *same* value up to and including
it). What **is** gauge-invariant regardless is the **ideal** generated by all
computed quantities -- its variety is exactly Bautin's center variety -- which
is why :mod:`omnibias.dynamics.bautin` works with the ideal, not with any one
``V_k`` read off in isolation.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from math import comb, isqrt, lcm

from omnibias.core.proof.certificate import Cert, make_certificate, verify_certificate_digest
from omnibias.core.proof.lean_check import LeanCheckResult, check_certificate
from omnibias.core.proof.lift import integer_null_space
from omnibias.core.proof.realization_replay import source_digest
from omnibias.core.realization.polynomial import SparsePolynomial
from omnibias.dynamics.compactify import PlanarPolynomialField
from omnibias.holonomic._core.poly_n import PolyN


def _q(value: Fraction) -> list[int]:
    return [value.numerator, value.denominator]


def _sparse_to_polyn(poly: SparsePolynomial) -> PolyN:
    return PolyN(poly.nvars, dict(poly.terms))


def _rational_sqrt(value: Fraction) -> Fraction:
    """Exact rational square root; ``ValueError`` if ``value`` is not a square."""
    if value <= 0:
        raise ValueError("a strictly positive rational is required")
    num, den = value.numerator, value.denominator
    sqrt_num, sqrt_den = isqrt(num), isqrt(den)
    if sqrt_num * sqrt_num != num or sqrt_den * sqrt_den != den:
        raise ValueError("value is not an exact rational square")
    return Fraction(sqrt_num, sqrt_den)


@dataclass(frozen=True)
class NormalizedMonodromicField:
    """Linear normalization of a planar field to ``x'=-y+P``, ``y'=x+Q``.

    ``p``, ``q`` are the exact degree>=2 remainder over ``Q[x,y]``. ``frequency``
    is the exact linear rotation rate before the time rescale that folds it to
    one (``w = sqrt(det)``).
    """

    source: PlanarPolynomialField
    frequency: Fraction
    p: PolyN
    q: PolyN

    @property
    def digest(self) -> str:
        return source_digest(self.to_payload())

    def to_payload(self) -> dict[str, object]:
        return {
            "source": self.source.to_payload(),
            "frequency": _q(self.frequency),
            "p": sorted([list(m), _q(c)] for m, c in self.p.terms.items()),
            "q": sorted([list(m), _q(c)] for m, c in self.q.terms.items()),
        }


def _compose_linear(poly: SparsePolynomial, x_sub: SparsePolynomial, y_sub: SparsePolynomial) -> SparsePolynomial:
    out = SparsePolynomial.constant(2, 0)
    for (i, j), coeff in poly.terms:
        term = SparsePolynomial.constant(2, coeff)
        if i:
            term = term * (x_sub**i)
        if j:
            term = term * (y_sub**j)
        out = out + term
    return out


def normalize_monodromic(field: PlanarPolynomialField) -> NormalizedMonodromicField:
    """Exact linear change of variables + time rescale to ``x'=-y+P``, ``y'=x+Q``.

    Requires an equilibrium at the origin with zero trace and a strictly
    positive, exact rational-square determinant (a nondegenerate monodromic /
    center-type linear part). Raises :class:`ValueError` otherwise; this
    function never drifts into an approximate or algebraic-number linear
    part, and never silently accepts a hyperbolic or degenerate origin.
    """
    p, q = field.p, field.q
    if p.evaluate((0, 0)) != 0 or q.evaluate((0, 0)) != 0:
        raise ValueError("normalize_monodromic requires an equilibrium at the origin")
    a = p.derivative(0).evaluate((0, 0))
    b = p.derivative(1).evaluate((0, 0))
    c = q.derivative(0).evaluate((0, 0))
    d = q.derivative(1).evaluate((0, 0))
    if a + d != 0:
        raise ValueError("normalize_monodromic requires zero trace at the origin")
    det = a * d - b * c
    if det <= 0:
        raise ValueError("normalize_monodromic requires a strictly positive determinant")
    w = _rational_sqrt(det)
    if b == 0:
        raise ArithmeticError(
            "zero trace with a strictly positive determinant forces a nonzero "
            "off-diagonal entry; this should be unreachable"
        )
    u_var = SparsePolynomial.variable(2, 0)
    v_var = SparsePolynomial.variable(2, 1)
    x_sub = SparsePolynomial.constant(2, b) * v_var
    y_sub = SparsePolynomial.constant(2, w) * u_var - SparsePolynomial.constant(2, a) * v_var
    p_uv = _compose_linear(p, x_sub, y_sub)
    q_uv = _compose_linear(q, x_sub, y_sub)
    inv_w = Fraction(1) / w
    du_dtau = SparsePolynomial.constant(2, a * inv_w * inv_w / b) * p_uv + SparsePolynomial.constant(
        2, inv_w * inv_w
    ) * q_uv
    dv_dtau = SparsePolynomial.constant(2, inv_w / b) * p_uv
    linear_u = {idx: c for idx, c in du_dtau.terms if sum(idx) == 1}
    linear_v = {idx: c for idx, c in dv_dtau.terms if sum(idx) == 1}
    if linear_u != {(0, 1): Fraction(-1)} or linear_v != {(1, 0): Fraction(1)}:
        raise ArithmeticError(
            "the derived linear part is not exactly the standard rotation; "
            "the normalization algebra has a bug"
        )
    p_nonlinear = du_dtau + SparsePolynomial.variable(2, 1)
    q_nonlinear = dv_dtau - SparsePolynomial.variable(2, 0)
    return NormalizedMonodromicField(field, w, _sparse_to_polyn(p_nonlinear), _sparse_to_polyn(q_nonlinear))


def _coeff_at(poly: PolyN, i: int, j: int, param_nvars: int) -> PolyN:
    terms = {mon[2:]: c for mon, c in poly.terms.items() if mon[0] == i and mon[1] == j}
    return PolyN(param_nvars, terms)


def _inject(coeff: PolyN, i: int, j: int, nvars: int) -> PolyN:
    return PolyN(nvars, {(i, j, *rest): c for rest, c in coeff.terms.items()})


def _assemble_xy_vector(vec: list[PolyN], nvars: int, k: int) -> PolyN:
    total = PolyN.zero(nvars)
    for i, coeff in enumerate(vec):
        if not coeff.is_zero():
            total = total + _inject(coeff, i, k - i, nvars)
    return total


def _l0_matrix(k: int) -> list[list[int]]:
    """Integer matrix of ``L = -y d/dx + x d/dy`` on homogeneous degree-``k``
    terms, basis ``e_i = x^i y^(k-i)``, ``i=0..k``. Column ``i`` is ``L(e_i)``."""
    size = k + 1
    m = [[0] * size for _ in range(size)]
    for i in range(size):
        if i - 1 >= 0:
            m[i - 1][i] += -i
        if i + 1 < size:
            m[i + 1][i] += k - i
    return m


def _invert_rational_matrix(matrix: list[list[int | Fraction]]) -> list[list[Fraction]]:
    n = len(matrix)
    aug = [
        [Fraction(matrix[r][c]) for c in range(n)]
        + [Fraction(1) if c == r else Fraction(0) for c in range(n)]
        for r in range(n)
    ]
    for col in range(n):
        pivot = next((r for r in range(col, n) if aug[r][col] != 0), None)
        if pivot is None:
            raise ArithmeticError("the L operator matrix was expected to be invertible here")
        aug[col], aug[pivot] = aug[pivot], aug[col]
        factor = aug[col][col]
        aug[col] = [v / factor for v in aug[col]]
        for r in range(n):
            if r != col and aug[r][col] != 0:
                f = aug[r][col]
                aug[r] = [a - f * b for a, b in zip(aug[r], aug[col], strict=True)]
    return [row[n:] for row in aug]


def _apply_matrix(matrix: list[list[Fraction | int]], vec: list[PolyN], param_nvars: int) -> list[PolyN]:
    out = []
    for row in matrix:
        acc = PolyN.zero(param_nvars)
        for coeff, v in zip(row, vec, strict=True):
            if coeff != 0:
                acc = acc + v * coeff
        out.append(acc)
    return out


def _dot_int(coeffs: list[int], vec: list[PolyN], param_nvars: int) -> PolyN:
    acc = PolyN.zero(param_nvars)
    for c, v in zip(coeffs, vec, strict=True):
        if c != 0:
            acc = acc + v * c
    return acc


@dataclass(frozen=True)
class LyapunovQuantities:
    """Exact Poincare-Lyapunov focal values of a normalized center-type field.

    ``quantities`` is a list of ``(degree, value)`` pairs in increasing degree
    order (only even degrees produce a value); ``normal_form`` is the full
    list of ``(degree, F_degree)`` pairs of the constructed formal first
    integral, degree ``2`` through ``order``. See the module docstring for
    the gauge caveat on any value after the first nonzero one.
    """

    param_nvars: int
    order: int
    quantities: tuple[tuple[int, PolyN], ...]
    normal_form: tuple[tuple[int, PolyN], ...]


def focal_order(quantities: LyapunovQuantities) -> int | None:
    """The smallest degree with a nonzero focal value, or ``None`` (a formal
    center through ``quantities.order``)."""
    for degree, value in quantities.quantities:
        if not value.is_zero():
            return degree
    return None


def lyapunov_quantities(p: PolyN, q: PolyN, *, order: int) -> LyapunovQuantities:
    """Solve the homological equation degree by degree, exactly over ``Q``.

    ``p``, ``q`` share a ring with ``x`` as variable ``0``, ``y`` as variable
    ``1``, and any remaining variables treated as symbolic parameters (their
    powers are carried along, never solved for). Both must vanish to total
    ``(x,y)``-degree ``< 2`` (no linear or constant part -- that belongs in
    the already-normalized linear system).
    """
    if p.nvars != q.nvars or p.nvars < 2:
        raise ValueError("p and q must share a ring with at least (x, y)")
    if type(order) is not int or order < 3:
        raise ValueError("order must be an integer >= 3")
    nvars = p.nvars
    param_nvars = nvars - 2
    for name, poly in (("p", p), ("q", q)):
        low = min((mon[0] + mon[1] for mon in poly.terms), default=99)
        if poly.terms and low < 2:
            raise ValueError(f"{name} must start at total (x, y) degree >= 2")
    zero_tail = (0,) * param_nvars
    f_total = PolyN(nvars, {(2, 0, *zero_tail): Fraction(1, 2), (0, 2, *zero_tail): Fraction(1, 2)})
    quantities: list[tuple[int, PolyN]] = []
    normal_form: list[tuple[int, PolyN]] = [(2, f_total)]
    fx = f_total.partial(0)
    fy = f_total.partial(1)
    for k in range(3, order + 1):
        obstruction = p * fx + q * fy
        rhs_vec = [_coeff_at(obstruction, i, k - i, param_nvars) * (-1) for i in range(k + 1)]
        m = _l0_matrix(k)
        if k % 2 == 1:
            minv = _invert_rational_matrix(m)
            f_vec = _apply_matrix(minv, rhs_vec, param_nvars)
        else:
            j = k // 2
            n_vec = [comb(j, i // 2) if i % 2 == 0 else 0 for i in range(k + 1)]
            if any(sum(m[r][c] * n_vec[c] for c in range(k + 1)) != 0 for r in range(k + 1)):
                raise ArithmeticError("the radial vector failed the kernel check")
            right_null = integer_null_space(m)
            transpose = [[m[c][r] for c in range(k + 1)] for r in range(k + 1)]
            left_null = integer_null_space(transpose)
            if len(right_null) != 1 or len(left_null) != 1:
                raise ArithmeticError("expected a one-dimensional focal obstruction at this degree")
            c_vec = left_null[0]
            cn = sum(Fraction(ci) * ni for ci, ni in zip(c_vec, n_vec, strict=True))
            if cn == 0:
                raise ArithmeticError("the radial vector is orthogonal to the cokernel")
            cr = _dot_int(c_vec, rhs_vec, param_nvars)
            eta = cr * (Fraction(1) / cn)
            corrected = [rhs_vec[i] - eta * n_vec[i] for i in range(k + 1)]
            check = _dot_int(c_vec, corrected, param_nvars)
            if not check.is_zero():
                raise ArithmeticError("solvability check failed after removing the focal obstruction")
            p_idx = next(i for i, v in enumerate(c_vec) if v != 0)
            m_prime = [row[:] for row in m]
            m_prime[p_idx] = list(n_vec)
            minv = _invert_rational_matrix(m_prime)
            rhs_prime = list(corrected)
            rhs_prime[p_idx] = PolyN.zero(param_nvars)
            f_vec = _apply_matrix(minv, rhs_prime, param_nvars)
            replay = _apply_matrix([[Fraction(v) for v in row] for row in m], f_vec, param_nvars)
            for got, want in zip(replay, corrected, strict=True):
                if not (got - want).is_zero():
                    raise ArithmeticError("the even-degree homological equation failed to close exactly")
            quantities.append((k, eta * Fraction(-1)))
        f_k = _assemble_xy_vector(f_vec, nvars, k)
        f_total = f_total + f_k
        normal_form.append((k, f_k))
        fx = fx + f_k.partial(0)
        fy = fy + f_k.partial(1)
    return LyapunovQuantities(param_nvars, order, tuple(quantities), tuple(normal_form))


def _identity_rows(field: NormalizedMonodromicField, quantities: LyapunovQuantities) -> list[dict[str, object]]:
    """Flat rational rows replaying ``L(F_k) + N(F_<k) - target == 0`` per slot."""
    values_by_degree = dict(quantities.quantities)
    normal_form = dict(quantities.normal_form)
    rows: list[dict[str, object]] = []
    fx = normal_form[2].partial(0)
    fy = normal_form[2].partial(1)
    for k in range(3, quantities.order + 1):
        obstruction = field.p * fx + field.q * fy
        n_vals = [_coeff_at(obstruction, i, k - i, 0).terms.get((), Fraction(0)) for i in range(k + 1)]
        f_k = normal_form[k]
        f_vals = [_coeff_at(f_k, i, k - i, 0).terms.get((), Fraction(0)) for i in range(k + 1)]
        m = _l0_matrix(k)
        radial = [comb(k // 2, i // 2) if (k % 2 == 0 and i % 2 == 0) else 0 for i in range(k + 1)]
        value_poly = values_by_degree.get(k) if k % 2 == 0 else None
        value = value_poly.terms.get((), Fraction(0)) if value_poly is not None else None
        for i in range(k + 1):
            contributions = [Fraction(m[i][c]) * f_vals[c] for c in range(k + 1) if m[i][c] != 0]
            contributions.append(n_vals[i])
            if value is not None and radial[i]:
                contributions.append(-Fraction(radial[i]) * value)
            denom = lcm(*(v.denominator for v in contributions)) if contributions else 1
            rows.append(
                {
                    "terms": [[v.numerator, denom // v.denominator] for v in contributions] or [[0, 1]],
                    "rhs": 0,
                }
            )
        fx = fx + f_k.partial(0)
        fy = fy + f_k.partial(1)
    return rows or [{"terms": [[0, 1]], "rhs": 0}]


@dataclass(frozen=True)
class FocalCertificate:
    """Exact-Q replay of the focal-value homological identities on one field."""

    field: NormalizedMonodromicField
    quantities: LyapunovQuantities
    order: int
    source_digest: str
    formal_seal: Cert


def certify_focal_values(field: PlanarPolynomialField, *, order: int) -> FocalCertificate:
    """Normalize ``field`` and seal the exact focal-value derivation to ``order``."""
    normalized = normalize_monodromic(field)
    quantities = lyapunov_quantities(normalized.p, normalized.q, order=order)
    seal = make_certificate(
        claim="Exact-Q homological-equation replay for Poincare-Lyapunov focal values.",
        payload={
            "type": "polynomial_identity_q",
            "source_digest": normalized.digest,
            "equations": _identity_rows(normalized, quantities),
            "positive": [],
            "formal_scope": (
                "finite rational homological-equation identities per degree; "
                "gauge-dependence of quantities after the first nonzero one, "
                "and center-variety membership beyond this truncation, remain external"
            ),
        },
        honesty={
            "focal_normal_form_identity_verified": True,
            "bautin_ideal_stabilization_proved": False,
            "physical_return_membership_proved": False,
        },
    )
    return FocalCertificate(normalized, quantities, order, normalized.digest, seal)


def verify_focal_values(certificate: FocalCertificate) -> bool:
    """Replay the source digest, the certificate seal, and the homological rows."""
    if certificate.source_digest != certificate.field.digest:
        return False
    if not verify_certificate_digest(certificate.formal_seal):
        return False
    recomputed = lyapunov_quantities(certificate.field.p, certificate.field.q, order=certificate.order)
    return recomputed.quantities == certificate.quantities.quantities


@dataclass(frozen=True)
class FocalFormalVerification:
    result: LeanCheckResult
    theorem_prover_verified: bool


def verify_focal_values_formally(certificate: FocalCertificate) -> FocalFormalVerification:
    """Run the Mathlib-free kernel on the exact homological-equation rows."""
    result = check_certificate(certificate.formal_seal)
    return FocalFormalVerification(result, result.verified)


__all__ = [
    "FocalCertificate",
    "FocalFormalVerification",
    "LyapunovQuantities",
    "NormalizedMonodromicField",
    "certify_focal_values",
    "focal_order",
    "lyapunov_quantities",
    "normalize_monodromic",
    "verify_focal_values",
    "verify_focal_values_formally",
]
