# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
r"""Hard Dirichlet / Neumann / Robin / initial conditions for the torch backend.

:class:`ConstrainedExpressionField` wraps a base field ``g`` so that a finite
set of linear conditions holds **identically**, for every parameter value:

.. math:: u = g + \sum_k \varphi_k \,\bigl(t_k - C_k[g]\bigr)

with switching functions :math:`\varphi_k` satisfying
:math:`C_m[\varphi_k] = \delta_{mk}` (see
:mod:`omnibias.pinn._core.constrained` for the algebra and the certificate
that the underlying support matrix is invertible). Applying that form once per
axis embeds conditions on several axes at once; the cross terms that make the
corners come out right are generated by the recursion rather than special-cased.

How this differs from :class:`~omnibias.pinn.torch.cage.HardBoundaryField`, the
other hard-condition cage:

* ``HardBoundaryField`` uses the *multiplicative* ansatz ``u = g + d * f`` with a
  user-supplied distance function. That handles arbitrary geometry, but only
  Dirichlet data, and it does not compose -- wrapping it around a derivative
  condition breaks whichever constraint ends up inside.
* This cage uses the *additive* switching form, which composes exactly across
  axes and across condition kinds, and covers value, normal-derivative and
  Robin combinations uniformly. The price is a box (axis-aligned) domain.

Both are exact; pick by geometry. On a box this one is also better behaved at
corners: the switching functions are polynomials, so nothing blows up where two
faces meet, which is the known failure mode of distance-function ansaetze under
second-order operators.

The constraint machinery is **closed form** in the network: every value and
derivative of ``g`` it needs, including at the projected face points, comes from
the ``sigma``-tower via ``ops.value`` / ``ops.derivative`` / ``ops.mixed_partial``.
Autodiff appears only if a *user-supplied target callable* has to be
differentiated along another axis; constant targets need none at all.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import torch
from omnibias.pinn._core.constrained import (
    AxisPlan,
    HardCondition,
    apply_constraint,
    certify_support_matrix,
    group_hard_conditions,
    switching_derivative_coeffs,
)
from omnibias.pinn._core.state import FieldState
from omnibias.pinn.torch.cage.incompressible import _CageFieldBase
from omnibias.pinn.torch.fields.base import FieldBase
from torch import Tensor

#: Key under which the per-evaluation projection / recursion cache is stashed.
_CACHE_KEY = "_constrained_cache"

#: Pins identify a projected coordinate tensor: ``((axis, value), ...)`` sorted
#: by axis. The empty tuple is the collocation batch itself.
Pins = tuple[tuple[int, float], ...]


class ConstrainedExpressionField(_CageFieldBase):
    r"""Cage enforcing linear boundary / initial conditions by construction.

    Parameters
    ----------
    base
        The field supplying the free function ``g``.
    conditions
        The :class:`~omnibias.pinn._core.constrained.HardCondition` set. Several
        conditions on one axis are embedded together; conditions on several axes
        are embedded by recursion, in ascending axis order.
    bounds
        Per-axis ``(lo, hi)``. Defaults to ``base.coordinate_spec.domain``, which
        is where the solver already records them.
    passthrough_names
        Components forwarded from the base untouched.
    certify
        Seal a support-matrix certificate per constrained axis (default). This
        is the gate that makes the ansatz exact rather than merely plausible, so
        turning it off is only for a caller who has already certified the same
        condition set.
    compatibility_tol
        Tolerance for the cross-axis data-compatibility check
        (:meth:`compatibility_residual`). Incompatible data leaves an order-one
        error, so this separates cleanly from round-off.

    Notes
    -----
    Cost is one base evaluation per *distinct projection point* plus one for the
    collocation batch. Conditions sharing a face -- a value and a slope at the
    same end, say -- share that evaluation.
    """

    def __init__(
        self,
        *,
        base: FieldBase,
        conditions: Sequence[HardCondition],
        bounds: Sequence[tuple[float, float]] | None = None,
        passthrough_names: tuple[str, ...] = (),
        groups: dict[str, tuple[str, ...]] | None = None,
        certify: bool = True,
        compatibility_tol: float = 1e-8,
    ) -> None:
        if not conditions:
            raise ValueError(
                "ConstrainedExpressionField needs at least one condition; an "
                "unconstrained field should be used directly"
            )
        resolved = bounds if bounds is not None else base.coordinate_spec.domain
        if resolved is None:
            raise ValueError(
                "hard conditions need per-axis (lo, hi) bounds: pass `bounds=` or "
                "build the base field with a CoordinateSpec carrying `domain=`"
            )
        plans = group_hard_conditions(conditions, tuple(resolved))
        constrained = tuple(plans)
        overlap = set(constrained) & set(passthrough_names)
        if overlap:
            raise ValueError(
                f"components {sorted(overlap)!r} are both constrained and passthrough"
            )
        super().__init__(
            base=base,
            velocity_names=constrained,
            passthrough_names=passthrough_names,
            groups=groups if groups is not None else {"constrained": constrained},
        )
        self._plans = plans
        self._bounds = tuple(resolved)
        self.compatibility_tol = float(compatibility_tol)
        self.certified = bool(certify)
        if certify:
            self.support_certificates()

    def support_certificates(self) -> dict[str, tuple[dict[str, Any], ...]]:
        """Sealed certificates that every constrained axis admits an exact ansatz.

        Recomputed rather than stored: the obligation is a handful of small
        matrices, and computing it on demand keeps the cage's static metadata
        hashable so the jax twin can carry the identical structure.
        """
        return {
            name: tuple(
                certify_support_matrix(
                    step.constraints,
                    claim=(
                        f"hard conditions on component {name!r}, axis "
                        f"{step.constraints.axis}, admit an exact constrained "
                        "expression"
                    ),
                )
                for step in steps
            )
            for name, steps in self._plans.items()
        }

    # ----- readout passthrough ----------------------------------------
    #
    # The constrained expression is *affine* in the base readout, so every
    # caller that treats the readout as the linear unknown keeps working when a
    # cage is wrapped around the ansatz. Forwarding the parameter handles is
    # what lets the frozen-feature linear solve stay a linear solve.

    @property
    def W(self) -> Any:
        """The base field's hidden layer."""
        return self.base.W

    @property
    def c(self) -> Any:
        """The base field's readout layer."""
        return self.base.c

    # ----- per-evaluation caching ------------------------------------

    def evaluate(self, coords: Tensor) -> FieldState[Tensor]:
        state = super().evaluate(coords)
        inner = state.extra["_cage_inner_state"]
        inner.extra.setdefault(_CACHE_KEY, {})
        return state

    def _pinned_state(self, inner_state: FieldState, pins: Pins) -> FieldState:
        """The base field evaluated with the given axes pinned to face values.

        Cached on the state, because a projected :class:`FieldState` caches only
        ``sigma^(n)(z)`` -- which depends on the coords and the hidden layer, not
        on the readout. That is what makes it safe to reuse while the linear
        driver sweeps the readout, and it is why a face carrying several
        conditions costs one base evaluation rather than one per condition.
        """
        if not pins:
            return inner_state
        states = inner_state.extra.setdefault(_CACHE_KEY, {})
        hit = states.get(pins)
        if hit is None:
            coords = inner_state.coords.clone()
            for axis, value in pins:
                coords[:, axis] = value
            hit = self.base.evaluate(coords)
            states[pins] = hit
        return hit  # type: ignore[return-value]

    # ----- the free function and its closed-form partials -------------

    def _base_partial(
        self, inner_state: FieldState, pins: Pins, name: str, orders: tuple[int, ...]
    ) -> Tensor:
        """``D^orders g`` at the pinned coords, from the closed-form sigma tower."""
        state = self._pinned_state(inner_state, pins)
        axes = tuple(a for a, o in enumerate(orders) if o)
        active = tuple(o for o in orders if o)
        if not axes:
            return state.ops.value(state, name)
        if len(axes) == 1:
            return state.ops.derivative(state, name, axis=axes[0], order=active[0])
        return state.ops.mixed_partial(state, name, axes, active)

    # ----- targets ----------------------------------------------------

    def _target_partial(
        self,
        inner_state: FieldState,
        target: Any,
        pins: Pins,
        orders: tuple[int, ...],
    ) -> Tensor:
        """``D^orders`` of a condition target, evaluated on its face.

        A constant target differentiates to zero exactly. A callable is
        differentiated by autograd along the remaining axes -- the one place the
        cage is not closed form, and only because the target is the user's own
        function rather than the network.
        """
        coords = inner_state.coords
        zeros = torch.zeros(coords.shape[0], dtype=coords.dtype, device=coords.device)
        if not callable(target):
            if any(orders):
                return zeros
            return zeros + float(target)

        # `clone` rather than `detach().clone()`: on the face the target is still
        # a function of the *other* coordinates, so severing that link here would
        # make the cage's own output disagree with autodiff through it.
        pinned = coords.clone()
        for axis, value in pins:
            pinned[:, axis] = value
        if not any(orders):
            out = target(pinned)
            return torch.as_tensor(out, dtype=coords.dtype, device=coords.device) + zeros

        # Differentiating the target is a *value* computation about the user's
        # own function, not a parameter gradient, so it has to work whatever the
        # ambient grad mode is -- the linear driver assembles under `no_grad`.
        with torch.enable_grad():
            work = pinned if pinned.requires_grad else pinned.detach().requires_grad_(True)
            cur = (
                torch.as_tensor(target(work), dtype=coords.dtype, device=coords.device)
                + zeros
            )
            for axis, order in enumerate(orders):
                for _ in range(order):
                    if not cur.requires_grad:
                        return zeros
                    (grad,) = torch.autograd.grad(
                        cur.sum(), work, create_graph=True, retain_graph=True
                    )
                    cur = grad[..., axis]
        return cur if torch.is_grad_enabled() else cur.detach()

    # ----- the recursion ----------------------------------------------

    def _level(
        self,
        inner_state: FieldState,
        name: str,
        depth: int,
        pins: Pins,
        orders: tuple[int, ...],
        memo: dict[Any, Tensor],
    ) -> Tensor:
        """``D^orders`` of the expression after the first ``depth`` axis steps.

        ``memo`` is scoped to one op call rather than to the state: the recursion
        revisits the same ``(depth, pins, orders)`` several times within a single
        derivative, but the values depend on the readout, and the linear driver
        reuses one state across many readouts.
        """
        if depth == 0:
            return self._base_partial(inner_state, pins, name, orders)
        key = (name, depth, pins, orders)
        hit = memo.get(key)
        if hit is not None:
            return hit

        step: AxisPlan = self._plans[name][depth - 1]
        axis = step.constraints.axis
        out = self._level(inner_state, name, depth - 1, pins, orders, memo)
        # rho depends on every coordinate except this axis, so its own
        # derivative index drops that slot; the switching function carries it.
        rest = tuple(0 if a == axis else o for a, o in enumerate(orders))
        xi = self._normalized(inner_state, step, pins)

        for i, constraint in enumerate(step.constraints.constraints):
            phi = self._switching(step, i, orders[axis], xi)
            if phi is None:
                continue
            face: Pins = _with_pin(pins, axis, constraint.points[0])
            rho = self._target_partial(inner_state, step.targets[i], face, rest)
            rho = rho - apply_constraint(
                constraint,
                lambda point, order, _rest=rest: self._level(  # type: ignore[misc]
                    inner_state,
                    name,
                    depth - 1,
                    _with_pin(pins, axis, point),
                    tuple(order if a == axis else o for a, o in enumerate(_rest)),
                    memo,
                ),
            )
            out = out + phi * rho

        memo[key] = out
        return out

    def _normalized(
        self, inner_state: FieldState, step: AxisPlan, pins: Pins
    ) -> Tensor:
        """The axis coordinate mapped into ``[0, 1]``, honouring any active pin."""
        axis = step.constraints.axis
        coords = inner_state.coords
        pinned = dict(pins).get(axis)
        if pinned is not None:
            base = torch.full(
                (coords.shape[0],), pinned, dtype=coords.dtype, device=coords.device
            )
        else:
            base = coords[:, axis]
        c = step.constraints
        return (base - c.lo) / c.length

    def _switching(
        self, step: AxisPlan, index: int, order: int, xi: Tensor
    ) -> Tensor | None:
        """``d^order phi_index / dx^order`` on the batch, or ``None`` if identically zero."""
        coeffs = switching_derivative_coeffs(
            step.constraints.switching[index], order, step.constraints.length
        )
        if not coeffs:
            return None
        out = torch.zeros_like(xi) + coeffs[0]
        power = torch.ones_like(xi)
        for c in coeffs[1:]:
            power = power * xi
            out = out + c * power
        return out

    # ----- _CageFieldBase hooks ---------------------------------------

    def _velocity_value(self, inner_state: FieldState, name: str) -> Tensor:
        zero = (0,) * self.coordinate_spec.ndim
        return self._level(inner_state, name, len(self._plans[name]), (), zero, {})

    def _velocity_derivative(
        self, inner_state: FieldState, name: str, *, axis: int, order: int
    ) -> Tensor:
        orders = tuple(
            order if a == axis else 0 for a in range(self.coordinate_spec.ndim)
        )
        return self._level(inner_state, name, len(self._plans[name]), (), orders, {})

    def _velocity_mixed(
        self,
        inner_state: FieldState,
        name: str,
        axes: tuple[int, ...],
        orders: tuple[int, ...],
    ) -> Tensor:
        folded = [0] * self.coordinate_spec.ndim
        for a, o in zip(axes, orders, strict=False):
            folded[a] += int(o)
        return self._level(
            inner_state, name, len(self._plans[name]), (), tuple(folded), {}
        )

    # ----- the cross-axis data gate -----------------------------------

    def compatibility_residual(self, coords: Tensor) -> float:
        r"""How badly the condition data disagrees where two axes meet.

        For every pair of constrained axes the data must satisfy
        :math:`C^a_k[t^b_l] = C^b_l[t^a_k]` -- physically, the initial state must
        already satisfy the boundary condition at ``t = t0``. The construction
        cannot repair inconsistent data, and does not pretend to: this returns
        the size of the disagreement, which is order one when it is real and
        round-off when it is not.
        """
        worst = 0.0
        state = self.base.evaluate(coords)
        memo: dict[Any, Tensor] = {}
        ndim = self.coordinate_spec.ndim
        for name, steps in self._plans.items():
            depth = len(steps)
            for step in steps:
                axis = step.constraints.axis
                for i, constraint in enumerate(step.constraints.constraints):
                    got = apply_constraint(
                        constraint,
                        lambda point, order, _a=axis, _n=name, _d=depth: self._level(  # type: ignore[misc]
                            state,
                            _n,
                            _d,
                            ((_a, point),),
                            tuple(order if a == _a else 0 for a in range(ndim)),
                            memo,
                        ),
                    )
                    want = self._target_partial(
                        state,
                        step.targets[i],
                        ((axis, constraint.points[0]),),
                        (0,) * ndim,
                    )
                    worst = max(worst, float((got - want).abs().max().detach()))
        return worst

    def check_compatibility(self, coords: Tensor) -> None:
        """Raise when the condition data is inconsistent across axes."""
        residual = self.compatibility_residual(coords)
        if residual > self.compatibility_tol:
            raise ValueError(
                f"hard conditions are mutually inconsistent: residual {residual:.3e} "
                f"exceeds {self.compatibility_tol:.3e}. The conditions on different "
                "axes disagree where those axes meet (typically the initial state "
                "does not satisfy the boundary condition at t0); no ansatz can "
                "satisfy both, so the data must be reconciled first"
            )


def _with_pin(pins: Pins, axis: int, value: float) -> Pins:
    """``pins`` with ``axis`` pinned to ``value``, kept sorted for cache hits."""
    merged = {a: v for a, v in pins}
    merged[axis] = value
    return tuple(sorted(merged.items()))


def make_constrained_expression_field(
    base: FieldBase,
    conditions: Sequence[HardCondition],
    **kwargs: Any,
) -> ConstrainedExpressionField:
    """Positional-friendly constructor mirroring the other cage factories."""
    return ConstrainedExpressionField(base=base, conditions=conditions, **kwargs)


__all__ = [
    "ConstrainedExpressionField",
    "make_constrained_expression_field",
]
