# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Functional operator surface for the torch backend (Option 2 kernel).

The :class:`ComponentView` / :class:`VectorView` attribute DSL forwards
into these functions; users may also import them directly when writing
programmatic / extension code:

    from omnibias.fields.torch import ops
    adv = ops.advection(state, velocity=("u", "v", "w"))

All ops consume a :class:`FieldState` (never raw ``(u, coords)``
tensors) so the closed-form path stays closed-form: the state's
:class:`SigmaCache` is filled lazily and reused across orders.
"""

from __future__ import annotations

from omnibias.fields.torch.ops.basic import (
    derivative,
    divergence,
    gradient,
    laplacian,
    mixed_partial,
    stack_components,
    value,
    vector_derivative,
)
from omnibias.fields.torch.ops.chemistry import (
    darcy_flux,
    fickian_flux,
    nernst_planck_flux,
    nernst_planck_residual,
    poisson_residual,
    reaction_diffusion_residual,
)
from omnibias.fields.torch.ops.complex import dz, dzbar
from omnibias.fields.torch.ops.conservation import (
    advection_diffusion_residual,
    conservation_residual,
    dalembertian,
    diffusive_flux,
    flux_divergence,
    grad_squared_norm,
    gradient_of_composition,
    laplacian_of_composition,
    variable_coefficient_diffusion,
    wave_operator,
)
from omnibias.fields.torch.ops.electromagnetism import (
    ampere_residual,
    electric_field_from_potentials,
    faraday_residual,
    gauss_magnetic_residual,
    gauss_residual,
    lorenz_gauge_residual,
    magnetic_field_from_potential,
    poynting_vector,
    vector_dalembertian,
)
from omnibias.fields.torch.ops.finite_strain import (
    cauchy_stress,
    deformation_gradient_finite,
    elastodynamic_residual,
    finite_strain_residual,
    green_lagrange_strain,
    hooke_stress_general,
    isotropic_stiffness,
    jacobian_det,
    left_cauchy_green,
    mooney_rivlin_energy,
    neo_hookean_energy,
    neo_hookean_pk2,
    pk1_stress,
    pk2_stress,
    right_cauchy_green,
    st_venant_kirchhoff_energy,
    st_venant_kirchhoff_pk2,
)
from omnibias.fields.torch.ops.high_order import (
    biharmonic,
    gradient_of_derivative,
    hessian,
    jacobian,
    polylaplacian,
    spatial_hessian,
    vector_biharmonic,
    vector_hessian,
    vector_laplacian,
    vector_polylaplacian,
)
from omnibias.fields.torch.ops.integral import (
    integrate,
    line_integral,
    quadrature_nodes,
)
from omnibias.fields.torch.ops.kinetic import (
    bgk_collision,
    bgk_vlasov_residual,
    kinetic_energy_density,
    maxwellian,
    momentum_density,
    number_density,
    vlasov_residual,
)
from omnibias.fields.torch.ops.mechanics import (
    linear_elastic_stress,
    navier_cauchy_residual,
    newtonian_stress,
    stokes_residual,
    stress_divergence,
    velocity_from_streamfunction,
    viscous_dissipation,
    vorticity_from_streamfunction,
)
from omnibias.fields.torch.ops.mhd import (
    current_density,
    ideal_mhd_momentum_residual,
    induction_residual,
    lorentz_force,
    magnetic_divergence,
    magnetic_pressure,
    maxwell_stress_tensor,
)
from omnibias.fields.torch.ops.nonlinear import (
    advection,
    directional_derivative,
    material_derivative,
    p_laplacian,
    skew_symmetric_advection,
)
from omnibias.fields.torch.ops.norms import inner_product, l2_norm, sobolev_norm
from omnibias.fields.torch.ops.registry import register
from omnibias.fields.torch.ops.tensor import (
    tensor_cofactor,
    tensor_determinant,
    tensor_divergence,
    tensor_double_dot,
    tensor_inverse,
    tensor_matmul,
    tensor_trace,
    tensor_transpose,
)
from omnibias.fields.torch.ops.vector import (
    curl,
    curl_of_curl,
    deformation_gradient,
    gradient_of_divergence,
    rate_of_rotation_tensor,
    spatial_jacobian,
    strain_rate,
    vorticity,
)

__all__ = [
    "advection",
    "advection_diffusion_residual",
    "ampere_residual",
    "bgk_collision",
    "bgk_vlasov_residual",
    "biharmonic",
    "cauchy_stress",
    "conservation_residual",
    "curl",
    "curl_of_curl",
    "current_density",
    "dalembertian",
    "darcy_flux",
    "deformation_gradient",
    "deformation_gradient_finite",
    "derivative",
    "diffusive_flux",
    "directional_derivative",
    "divergence",
    "dz",
    "dzbar",
    "elastodynamic_residual",
    "electric_field_from_potentials",
    "faraday_residual",
    "fickian_flux",
    "finite_strain_residual",
    "flux_divergence",
    "gauss_magnetic_residual",
    "gauss_residual",
    "grad_squared_norm",
    "gradient",
    "gradient_of_composition",
    "gradient_of_derivative",
    "gradient_of_divergence",
    "green_lagrange_strain",
    "hessian",
    "hooke_stress_general",
    "ideal_mhd_momentum_residual",
    "induction_residual",
    "inner_product",
    "integrate",
    "isotropic_stiffness",
    "jacobian",
    "jacobian_det",
    "kinetic_energy_density",
    "l2_norm",
    "laplacian",
    "laplacian_of_composition",
    "left_cauchy_green",
    "line_integral",
    "linear_elastic_stress",
    "lorentz_force",
    "lorenz_gauge_residual",
    "magnetic_divergence",
    "magnetic_field_from_potential",
    "magnetic_pressure",
    "material_derivative",
    "maxwell_stress_tensor",
    "maxwellian",
    "mixed_partial",
    "momentum_density",
    "mooney_rivlin_energy",
    "navier_cauchy_residual",
    "neo_hookean_energy",
    "neo_hookean_pk2",
    "nernst_planck_flux",
    "nernst_planck_residual",
    "newtonian_stress",
    "number_density",
    "p_laplacian",
    "pk1_stress",
    "pk2_stress",
    "poisson_residual",
    "polylaplacian",
    "poynting_vector",
    "quadrature_nodes",
    "rate_of_rotation_tensor",
    "reaction_diffusion_residual",
    "register",
    "right_cauchy_green",
    "skew_symmetric_advection",
    "sobolev_norm",
    "spatial_hessian",
    "spatial_jacobian",
    "st_venant_kirchhoff_energy",
    "st_venant_kirchhoff_pk2",
    "stack_components",
    "stokes_residual",
    "strain_rate",
    "stress_divergence",
    "tensor_cofactor",
    "tensor_determinant",
    "tensor_divergence",
    "tensor_double_dot",
    "tensor_inverse",
    "tensor_matmul",
    "tensor_trace",
    "tensor_transpose",
    "value",
    "variable_coefficient_diffusion",
    "vector_biharmonic",
    "vector_dalembertian",
    "vector_derivative",
    "vector_hessian",
    "vector_laplacian",
    "vector_polylaplacian",
    "velocity_from_streamfunction",
    "viscous_dissipation",
    "vlasov_residual",
    "vorticity",
    "vorticity_from_streamfunction",
]
