# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-omnibias-Commercial
# Copyright (C) 2026 Derivon
"""Pure-Python verifier core: network description + rigorous propagation.

No torch / jax imports -- this layer depends only on
:mod:`omnibias.core.verified`.
"""

from __future__ import annotations

from omnibias.verify._core.activations import (
    compose_gelu,
    compose_sigma,
    compose_smooth,
    gauss_cdf_iv,
    gelu_enclosure,
    max_enclosure,
    relu_taylor,
)
from omnibias.verify._core.bab import (
    RangeResult,
    hull_of_boxes,
    output_range,
    scalar_readout_range,
)
from omnibias.verify._core.certificates import (
    IntervalMatrix,
    MonotonicityCertificate,
    RobustnessCertificate,
    certify_robustness,
    interval_jacobian,
    lipschitz_bound,
    monotonicity,
    reachable_box,
)
from omnibias.verify._core.global_opt import (
    GlobalMinResult,
    certified_minimize,
    certify_strict_local_min,
)
from omnibias.verify._core.gradient_check import (
    GradientCheckCertificate,
    certified_gradient_check,
    gradient_residual_certificate,
    mlp_axis_oracles,
    network_axis_oracles,
)
from omnibias.verify._core.jet_ingest import (
    SUPPORTED_ACTIVATIONS,
    CertifiedPDEPipelineResult,
    VerifiedLayer,
    VerifiedLayerBundle,
    certify_pinn_aposteriori,
    verified_layer_bundle,
    verified_layers,
)
from omnibias.verify._core.net_global_opt import (
    NetworkCertificate,
    certified_network_critical_points,
    certified_network_flatness,
    certified_network_minimize,
    certify_network_strict_local_min,
    certify_trained_network,
)
from omnibias.verify._core.network import (
    GELULayer,
    Layer,
    LinearLayer,
    MaxPoolLayer,
    Network,
    ReLULayer,
    SigmoidLayer,
    TanhLayer,
    affine_layer,
)
from omnibias.verify._core.norms import (
    LpNormCertificate,
    NormMethod,
    SobolevNormCertificate,
    certified_layer_cake_integral,
    certified_lp_norm,
    certified_sobolev_norm,
)
from omnibias.verify._core.param_global import (
    GlobalTrainingCertificate,
    certify_trained_global_min,
)
from omnibias.verify._core.param_jet import (
    ParamJet,
    param_jet,
)
from omnibias.verify._core.param_loss import (
    MLPArchitecture,
    ParamSpaceLoss,
    TrainingCertificate,
    certify_trained_min,
    flat_params_from_layers,
)
from omnibias.verify._core.pde_stencil import (
    LaplacianTruncationCertificate,
    StencilTruncationCertificate,
    certified_laplacian_truncation,
    certified_stencil_truncation,
    measured_consistency_order,
)
from omnibias.verify._core.propagate import (
    BoundResult,
    interval_propagate,
    relu_enclosure,
)
from omnibias.verify._core.quadrature import (
    Box,
    DomainIntegralCertificate,
    IntegralCertificate,
    IntegrandModel,
    QuadMethod,
    certified_domain_integral,
    certified_integral,
    certified_network_integral,
    network_integrand_model,
)
from omnibias.verify._core.stationary import (
    CriticalPoint,
    FlatnessResult,
    certified_critical_points,
    certified_flatness,
)
from omnibias.verify._core.stochastic import (
    StochasticResidualCertificate,
    certified_fokker_planck_residual,
    certified_ito_generator_residual,
    certify_fokker_planck_residual,
    certify_ito_generator_residual,
    replay_stochastic_residual_certificate,
    stochastic_residual_schema_errors,
)
from omnibias.verify._core.subspace_step import (
    SubspaceModel,
    SubspaceStepCertificate,
    cauchy_step,
    certify_subspace_step,
    certify_trajectory,
    enclose_subspace_model,
    krylov_basis,
)
from omnibias.verify._core.surrogate_bounds import (
    KERNELS,
    CertifiedBound,
    agreement_margin_iv,
    certify_agreement_margin,
    certify_no_dead_unit,
    jet_remainder_iv,
    mollification_bias_iv,
    mollified_lipschitz_iv,
    surrogate_kernel_iv,
    tail_gradient_iv,
)
from omnibias.verify._core.taylor import (
    input_models,
    linear_image,
    taylor_output_bounds,
    taylor_propagate,
)

__all__ = [
    "BoundResult",
    "Box",
    "CertifiedBound",
    "CertifiedPDEPipelineResult",
    "CriticalPoint",
    "DomainIntegralCertificate",
    "FlatnessResult",
    "GELULayer",
    "GlobalMinResult",
    "GlobalTrainingCertificate",
    "GradientCheckCertificate",
    "IntegralCertificate",
    "IntegrandModel",
    "IntervalMatrix",
    "KERNELS",
    "LaplacianTruncationCertificate",
    "Layer",
    "LinearLayer",
    "LpNormCertificate",
    "MLPArchitecture",
    "MaxPoolLayer",
    "MonotonicityCertificate",
    "Network",
    "NetworkCertificate",
    "NormMethod",
    "ParamJet",
    "ParamSpaceLoss",
    "QuadMethod",
    "RangeResult",
    "ReLULayer",
    "RobustnessCertificate",
    "SUPPORTED_ACTIVATIONS",
    "SigmoidLayer",
    "SobolevNormCertificate",
    "StencilTruncationCertificate",
    "StochasticResidualCertificate",
    "SubspaceModel",
    "SubspaceStepCertificate",
    "TanhLayer",
    "TrainingCertificate",
    "VerifiedLayer",
    "VerifiedLayerBundle",
    "affine_layer",
    "agreement_margin_iv",
    "cauchy_step",
    "certified_critical_points",
    "certified_domain_integral",
    "certified_flatness",
    "certified_fokker_planck_residual",
    "certified_gradient_check",
    "certified_integral",
    "certified_ito_generator_residual",
    "certified_laplacian_truncation",
    "certified_layer_cake_integral",
    "certified_lp_norm",
    "certified_minimize",
    "certified_network_critical_points",
    "certified_network_flatness",
    "certified_network_integral",
    "certified_network_minimize",
    "certified_sobolev_norm",
    "certified_stencil_truncation",
    "certify_agreement_margin",
    "certify_fokker_planck_residual",
    "certify_ito_generator_residual",
    "certify_network_strict_local_min",
    "certify_no_dead_unit",
    "certify_pinn_aposteriori",
    "certify_robustness",
    "certify_strict_local_min",
    "certify_subspace_step",
    "certify_trained_global_min",
    "certify_trained_min",
    "certify_trained_network",
    "certify_trajectory",
    "compose_gelu",
    "compose_sigma",
    "compose_smooth",
    "enclose_subspace_model",
    "flat_params_from_layers",
    "gauss_cdf_iv",
    "gelu_enclosure",
    "gradient_residual_certificate",
    "hull_of_boxes",
    "input_models",
    "interval_jacobian",
    "interval_propagate",
    "jet_remainder_iv",
    "krylov_basis",
    "linear_image",
    "lipschitz_bound",
    "max_enclosure",
    "measured_consistency_order",
    "mlp_axis_oracles",
    "mollification_bias_iv",
    "mollified_lipschitz_iv",
    "monotonicity",
    "network_axis_oracles",
    "network_integrand_model",
    "output_range",
    "param_jet",
    "reachable_box",
    "relu_enclosure",
    "relu_taylor",
    "replay_stochastic_residual_certificate",
    "scalar_readout_range",
    "stochastic_residual_schema_errors",
    "surrogate_kernel_iv",
    "tail_gradient_iv",
    "taylor_output_bounds",
    "taylor_propagate",
    "verified_layer_bundle",
    "verified_layers",
]
