# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Pure-Python core of :mod:`omnibias.difference` (imports only ``omnibias.core.*``).

The founding ``delta -> 0`` bias-collapse math: backend-neutral finite-difference
stencils, certified finite-difference -> derivative extraction, the special-number
readers (Stirling / Bernoulli / Euler off the closed-form towers), umbral / Sheffer
calculus, and the leading asymptotics.
"""

from __future__ import annotations

from omnibias.difference._core.asymptotics import (
    bell_number_asymptotic,
    bernoulli_asymptotic,
    euler_asymptotic,
    log_bell_number_asymptotic,
    stirling_second_asymptotic,
)
from omnibias.difference._core.bernoulli import (
    bernoulli_number,
    bernoulli_polynomial,
    power_sum_coeffs,
)
from omnibias.difference._core.certify import (
    DerivativeProofVerdict,
    check_derivative_certificate,
    derivative_sign_certificate,
)
from omnibias.difference._core.euler import (
    euler_number,
    euler_polynomial,
    eulerian_number,
)
from omnibias.difference._core.extraction import (
    DerivativeEnclosure,
    DerivBound,
    DifferenceEstimate,
    FiniteDifferenceCertificate,
    certified_derivative_enclosure,
    certified_fd_error,
    certified_fd_error_general,
    finite_difference_estimate,
    sigma_deriv_bound,
)
from omnibias.difference._core.generating import (
    TransferEstimate,
    bell_asymptotic_relative_error,
    bell_dobinski_enclosure,
    bell_number_asymptotic_refined,
    bernoulli_enclosure,
    catalan_asymptotic,
    cauchy_product,
    dirichlet_beta_odd_enclosure,
    dominant_pole_coefficient_asymptotic,
    euler_enclosure,
    exponential_generating_coeffs,
    log_bell_number_asymptotic_refined,
    ordinary_from_exponential,
    rational_ogf_coefficients,
    rational_ogf_growth_base,
    recommended_bell_fallback_n,
    singular_template_coefficient,
    transfer_theorem,
    zeta_int_enclosure,
)
from omnibias.difference._core.identities import (
    RationalIdentityVerdict,
    bernoulli_recurrence_identity,
    bernoulli_sign_certificate,
    check_identity_certificate,
    euler_recurrence_identity,
    rational_value_identity,
    zeta_negative_odd_identity,
)
from omnibias.difference._core.pade import (
    pade_approximant,
    pade_certified_remainder,
    pade_evaluate,
    pade_evaluate_interval,
    rational_series,
    thiele_evaluate,
    thiele_interpolation,
)
from omnibias.difference._core.sheffer import (
    associated_sequence,
    delta_operator_apply,
    pincherle_derivative,
    sheffer_sequence,
    shift_polynomial,
    umbral_composition,
    umbral_functional,
)
from omnibias.difference._core.stencil import (
    accuracy_order,
    offsets_exact,
    signs_exact,
    stencil_offsets,
    stencil_signs,
)
from omnibias.difference._core.stirling import (
    bell_number,
    falling_factorial_coeffs,
    rising_factorial_coeffs,
    stirling_first_signed,
    stirling_first_signed_row,
    stirling_first_unsigned,
    stirling_second,
    stirling_second_row,
)
from omnibias.difference._core.umbral import (
    ShefferClass,
    appell_sequence,
    binomial_coefficient,
    binomial_transform,
    compose_series,
    compositional_inverse,
    connection_constants,
    falling_to_monomial,
    forward_difference,
    inverse_binomial_transform,
    monomial_to_falling,
    newton_forward_coeffs,
    newton_forward_value,
    riordan_array,
    riordan_inverse,
    riordan_product,
    series_reciprocal,
    sheffer_classify,
)

__all__ = [
    "DerivBound",
    "DerivativeEnclosure",
    "DerivativeProofVerdict",
    "DifferenceEstimate",
    "FiniteDifferenceCertificate",
    "RationalIdentityVerdict",
    "ShefferClass",
    "TransferEstimate",
    "accuracy_order",
    "appell_sequence",
    "associated_sequence",
    "bell_asymptotic_relative_error",
    "bell_dobinski_enclosure",
    "bell_number",
    "bell_number_asymptotic",
    "bell_number_asymptotic_refined",
    "bernoulli_asymptotic",
    "bernoulli_enclosure",
    "bernoulli_number",
    "bernoulli_polynomial",
    "bernoulli_recurrence_identity",
    "bernoulli_sign_certificate",
    "binomial_coefficient",
    "binomial_transform",
    "catalan_asymptotic",
    "cauchy_product",
    "certified_derivative_enclosure",
    "certified_fd_error",
    "certified_fd_error_general",
    "check_derivative_certificate",
    "check_identity_certificate",
    "compose_series",
    "compositional_inverse",
    "connection_constants",
    "delta_operator_apply",
    "derivative_sign_certificate",
    "dirichlet_beta_odd_enclosure",
    "dominant_pole_coefficient_asymptotic",
    "euler_asymptotic",
    "euler_enclosure",
    "euler_number",
    "euler_polynomial",
    "euler_recurrence_identity",
    "eulerian_number",
    "exponential_generating_coeffs",
    "falling_factorial_coeffs",
    "falling_to_monomial",
    "finite_difference_estimate",
    "forward_difference",
    "inverse_binomial_transform",
    "log_bell_number_asymptotic",
    "log_bell_number_asymptotic_refined",
    "monomial_to_falling",
    "newton_forward_coeffs",
    "newton_forward_value",
    "offsets_exact",
    "ordinary_from_exponential",
    "pade_approximant",
    "pade_certified_remainder",
    "pade_evaluate",
    "pade_evaluate_interval",
    "pincherle_derivative",
    "power_sum_coeffs",
    "rational_ogf_coefficients",
    "rational_ogf_growth_base",
    "rational_series",
    "rational_value_identity",
    "recommended_bell_fallback_n",
    "riordan_array",
    "riordan_inverse",
    "riordan_product",
    "rising_factorial_coeffs",
    "series_reciprocal",
    "sheffer_classify",
    "sheffer_sequence",
    "shift_polynomial",
    "sigma_deriv_bound",
    "signs_exact",
    "singular_template_coefficient",
    "stencil_offsets",
    "stencil_signs",
    "stirling_first_signed",
    "stirling_first_signed_row",
    "stirling_first_unsigned",
    "stirling_second",
    "stirling_second_asymptotic",
    "stirling_second_row",
    "thiele_evaluate",
    "thiele_interpolation",
    "transfer_theorem",
    "umbral_composition",
    "umbral_functional",
    "zeta_int_enclosure",
    "zeta_negative_odd_identity",
]
