# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
r"""omnibias-holonomic: a D-finite computer-algebra engine with Lean-certified identities.

Exact, dependency-free machinery for holonomic (D-finite / P-recursive) sequences and
functions:

* **Ore algebra** (:class:`OreAlgebra`, :class:`OrePolynomial`) -- the skew polynomial
  rings ``R[S; sigma]`` (shift) and ``R[D; delta]`` (differential) with non-commutative
  multiplication, a genuine right-Euclidean domain (:func:`ore_divmod`, :func:`gcrd`,
  :func:`lclm`, :func:`symmetric_product`), and the :class:`DFinite` / :class:`PRecursive`
  objects they annihilate -- closed under sum / Hadamard product **symbolically for all
  ``n``** (via ``lclm`` / ``symmetric_product``), with the verified-ansatz path as a
  labelled fallback;
* **Gosper's algorithm** (:func:`gosper_sum`, :func:`gosper_definite_sum`) -- unconditional,
  closed-form indefinite / definite hypergeometric summation with an exact certificate;
* **true Zeilberger + WZ** (:func:`zeilberger`, :class:`ZeilbergerCertificate`,
  :func:`wz_pair`, :func:`wz_certificate`) -- exact creative telescoping (a telescoper ``L``
  plus a rational cofactor ``R(n, k)``) solved by an exact null space, needing no guesser
  and handling degenerate sums natively; the guessed-then-range-verified
  :func:`creative_telescoping` is kept as the fast path;
* **Petkovsek's Hyper** (:func:`hyper`) -- all hypergeometric-term solutions of a shift
  recurrence, on the scoped rational-root / linear :mod:`~omnibias.holonomic._core.factor`
  substrate (:func:`rational_roots`, :func:`square_free`);
* **q-holonomic** (:func:`q_shift_algebra`, :func:`q_gosper`, :func:`q_zeilberger`) --
  the q-analogues on :mod:`omnibias.qcalculus` primitives, with exact q-rational
  certificates and the ``q -> 1`` distinct-limit framing;
* **transforms & closures** (:func:`dfinite_to_precursive`, :func:`precursive_to_dfinite`,
  :func:`dfinite_derivative`, :func:`dfinite_integral`, :func:`dfinite_compose_poly`) --
  the exact ODE <-> coefficient-recurrence bridge and the D-finite closure operations;
* **guessing** (:func:`guess_recurrence`, :func:`guess_dfinite`, :func:`guess_algebraic`) --
  minimal P-recursive / differential / algebraic annihilators, guessed by exact null space
  and verified on held-out terms;
* **asymptotics** (:func:`precursive_asymptotics`, :func:`certified_asymptotic`) -- the
  Poincare-Perron leading rate / exponent (numerical), bridged to
  :func:`omnibias.difference.transfer_theorem` for a certified coefficient where the
  singularity is known;
* **Lean-certified identities** (:func:`prove_hypergeometric_identity`,
  :func:`prove_identity_zeilberger`) -- classic binomial identities discharged, per
  coefficient, as ``rational_identity`` obligations the omnibias Lean kernel checks; the
  Zeilberger path emits ``P(n, k) == 0`` obligations that hold for **all** ``n``, so
  ``theorem_prover_verified`` is earned **only** on a genuine ``lake`` pass and never
  forged.

Honesty: operator algebra, Gosper / Zeilberger sums, transforms, and the certificate
payloads are exact / ``closed-form``; the *guessing* step (which annihilator fits) is
heuristic and labelled, the verification and the Lean obligations are rigorous;
:mod:`~omnibias.holonomic._core.factor` is scoped to the rational-root / linear regime and
:mod:`~omnibias.holonomic._core.asymptotics` returns a ``numerical`` leading term. It builds
on :mod:`omnibias.difference` (probe harness + transfer theorem), :mod:`omnibias.qcalculus`
(q-primitives), :mod:`omnibias.symbolic` (recurrence guessing), and the
:mod:`omnibias.core.proof` Lean loop.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError as _PkgNotFound
from importlib.metadata import version as _pkg_version

from omnibias.holonomic._core import (
    DEFAULT_GROEBNER_BUDGET,
    AsymptoticEstimate,
    DFinite,
    GosperResult,
    GroebnerBudget,
    GroebnerBudgetExceeded,
    HolonomicProof,
    HyperellipticPicardFuchsCertificate,
    IdealMembership,
    MonomialOrder,
    OreAlgebra,
    OreDivision,
    OrePolynomial,
    PicardFuchsCertificate,
    Poly,
    PolyN,
    PRecursive,
    ProperTerm,
    QGosperResult,
    QRecurrence,
    Summand,
    Telescoper,
    ZeilbergerCertificate,
    binomial_nk,
    buchberger,
    certified_asymptotic,
    certify_hyperelliptic_picard_fuchs,
    certify_picard_fuchs,
    creative_telescoping,
    dfinite_add,
    dfinite_cauchy,
    dfinite_compose_poly,
    dfinite_derivative,
    dfinite_hadamard,
    dfinite_integral,
    dfinite_to_precursive,
    diff_algebra,
    dispersion_set,
    empirical_rate,
    gcrd,
    geometric_k,
    gosper_definite_sum,
    gosper_normal_form,
    gosper_sum,
    guess_algebraic,
    guess_dfinite,
    guess_recurrence,
    hyper,
    ideal_member,
    jacobian_det,
    lclm,
    ore_divmod,
    peval,
    pgcd,
    precursive_asymptotics,
    precursive_to_dfinite,
    prove_hypergeometric_identity,
    prove_identity_zeilberger,
    q_from_p,
    q_gosper,
    q_gosper_definite_sum,
    q_gosper_normal_form,
    q_shift_algebra,
    q_zeilberger,
    radical_member,
    rational_roots,
    recurrence_to_operator,
    reduced_groebner_basis,
    roots_with_multiplicity,
    shift_algebra,
    square_free,
    summand_sum,
    sylvester_resultant,
    symmetric_product,
    term_ratio_annihilates,
    to_poly,
    verify_hyperelliptic_picard_fuchs,
    verify_ideal_membership,
    verify_picard_fuchs,
    wz_certificate,
    wz_pair,
    zeilberger,
)
from omnibias.holonomic._core.export import AnnihilatorExport, export_annihilator
from omnibias.holonomic._core.layer import HolonomicLayerSpec, fit_holonomic_layer, holonomic_jet
from omnibias.holonomic.jacobian_n2 import (
    JACOBIAN_CONJECTURE_PROOF_CLAIM_ALLOWED,
    JacobianN2DegreeFamily,
    JacobianN2HomogeneousFamily,
    escalate_n2_result,
    jacobian_n2_box_statement,
    jacobian_n2_homog_statement,
    jacobian_n2_honesty,
    reject_jacobian_proof_claim,
    seal_jacobian_honesty,
)
from omnibias.holonomic.jacobian_n2_case_a import (
    CASE_A_B31_KIND,
    case_a_b31_statement,
    replay_case_a_b31,
    seal_case_a_b31,
)
from omnibias.holonomic.jacobian_n2_case_a_b02 import (
    CASE_A_B02_KIND,
    case_a_b02_statement,
    replay_case_a_b02,
    seal_case_a_b02,
)
from omnibias.holonomic.jacobian_n2_inverse import gabber_n2_test
from omnibias.holonomic.jacobian_n2_normalize import (
    classify_leftover_chart,
    o1_normalize,
    replay_leftover_certificate,
    seal_leftover_certificate,
)
from omnibias.holonomic.keller import (
    alpoge_map,
    fiber_report,
    gallagher_map,
    search_tangent_sweep,
    verify_alpoge_map,
    verify_gallagher_map,
)
from omnibias.holonomic.proofmachine import build_holonomic_machine
from omnibias.holonomic.rank_syzygy import (
    HOLONOMIC_SYZYGY,
    certify_holonomic_syzygy,
    integerize_matrix,
)
from omnibias.holonomic.swirl_heat import (
    SWIRL_HEAT_KIND,
    named_swirl_heat_generators,
    prove_swirl_heat_identity,
    replay_swirl_heat_identity,
    swirl_heat_identity_payload,
)
from omnibias.holonomic.twin_prime import (
    ASYMPTOTIC_SIEVE_EXTERNAL_PREMISES,
    ASYMPTOTIC_SIEVE_KIND,
    BOUNDED_GAP_QUADRATIC_KIND,
    FI_COMBINATORIAL_EXTERNAL_PREMISES,
    FI_TERMINAL_ATLAS_EXTERNAL_PREMISES,
    FIXED_SHIFT_DETERMINANT_EXTERNAL_PREMISES,
    FIXED_SHIFT_DETERMINANT_KIND,
    FIXED_SHIFT_KERNEL_SAVING_FLOOR,
    FIXED_SHIFT_TARGET_SAVING,
    H1_182_EXTERNAL_PREMISES,
    H1_182_SHIFTS,
    H1_186_PUBLISHED_MARGIN,
    H1_186_REQUIRED_MARGIN,
    H1_186_RHO_STAR,
    H1_186_SHIFTS,
    HEATH_BROWN_SMALL_FACTOR_ROOM,
    MATRIX_CLOSE_PAIR_KIND,
    TWIN_PRIME_EXTERNAL_PREMISES,
    AdmissibilityReport,
    BoundedGapBaseline,
    BoundedGapQuadraticCertificate,
    BoundedGapTargetSpec,
    FIAnalyticUse,
    FIAtlasParameters,
    FICombinatorialReplayCertificate,
    FiniteStatus,
    FITerminalAtlasCertificate,
    FITermLedgerReport,
    FixedShiftDeterminantCase,
    FixedShiftDeterminantCertificate,
    FixedShiftKernelCellCertificate,
    FormalLogVector,
    KnownEstimate,
    KnownEstimateKind,
    LocalFactorIdentity,
    LocalProductCertificate,
    LogAffineBound,
    LogPolyhedralCell,
    MatrixClosePairCertificate,
    MatrixVariationalCertificate,
    MobiusCellReductionCertificate,
    OpenClosedInterval,
    PSDReport,
    RationalCell,
    RationalInput,
    RationalMatrix,
    RhoInsertionCertificate,
    VaughanCoefficientCase,
    WrightRangeReport,
    admissibility_report,
    asymptotic_sieve_honesty,
    asymptotic_sieve_local_factor,
    bounded_gap_quadratic_honesty,
    canonical_fi_term_ledger,
    certify_asymptotic_sieve_local_product,
    certify_bounded_gap_quadratic_witness,
    certify_fi_combinatorial_replay,
    certify_fi_terminal_atlas,
    certify_fixed_shift_determinant_replay,
    certify_fixed_shift_kernel_cell,
    certify_matrix_close_pair,
    certify_matrix_variational_witness,
    certify_mobius_cell_reduction,
    certify_rho_insertion,
    fi_atlas_obligation_certificates,
    fi_combinatorial_honesty,
    fi_combinatorial_obligation_certificates,
    fi_rational_terminal_family,
    fi_terminal_atlas_honesty,
    fi_vaughan_coefficient_case,
    fixed_shift_determinant_case,
    fixed_shift_determinant_honesty,
    gamma_truncation,
    h1_182_target,
    h1_186_baseline,
    integer_log_vector,
    local_factor_obligation_certificates,
    matrix_trace_product,
    maximal_far_sets,
    mobius_integer,
    oriented_lambda_log_vector,
    prime_gap_honesty,
    psd_report,
    seal_asymptotic_sieve_local_product,
    seal_bounded_gap_quadratic_witness,
    seal_fi_combinatorial_replay,
    seal_fi_terminal_atlas,
    seal_fixed_shift_determinant_replay,
    seal_matrix_variational_certificate,
    seal_mobius_cell_reduction,
    select_fi_dyadic_s,
    unsigned_oriented_lambda_log_vector,
    validate_fi_term_ledger,
    verify_dyadic_membership,
    verify_gamma_mobius_identity,
    von_mangoldt_log_vector,
    wright_fixed_shift_range,
)
from omnibias.holonomic.twin_prime_bounded_gap import (
    PRIME_GAP_COEFFICIENT_SIGNATURES,
    PRIME_GAP_QUADRATIC_MATRIX_NAMES,
    PRIME_GAPS_186_COMMIT,
    PRIME_GAPS_186_SOURCE_SHA256,
    PRIME_GAPS_186_SOURCE_URL,
    PRIME_GAPS_INPUT_MANIFEST_KIND,
    PRIME_GAPS_NUMERICAL_RECEIPT_KIND,
    PRIME_GAPS_QUADRATIC_RECEIPT_KIND,
    ExactCoefficientInterval,
    ExactSymmetricIntervalMatrix,
    PrimeGapCell,
    PrimeGapCoefficientDescriptor,
    PrimeGapEngineLayout,
    PrimeGapInputManifest,
    PrimeGapLadderRow,
    PrimeGapNumericalReceiptCertificate,
    PrimeGapQuadraticCandidateCertificate,
    PrimeGapQuadraticKernelSpec,
    PrimeGapQuadraticReceiptCertificate,
    PrimeGapRoundingReserveCertificate,
    PrimeGapShell,
    PrimeGapSourceGroup,
    PrimeGapSourceTask,
    SignedConvolutionSplitCertificate,
    build_prime_gap_input_manifest,
    certify_prime_gap_numerical_receipt,
    certify_prime_gap_quadratic_candidate,
    certify_prime_gap_quadratic_receipt,
    certify_prime_gap_rounding_reserve,
    certify_signed_convolution_split,
    parameterize_prime_gap_evaluator_source,
    prime_gap_coefficient_descriptors,
    prime_gap_engine_layout,
    prime_gap_quadratic_kernel_spec,
    seal_prime_gap_input_manifest,
    seal_prime_gap_numerical_receipt,
    seal_prime_gap_quadratic_receipt,
)

try:
    __version__ = _pkg_version("omnibias-holonomic")
except _PkgNotFound:  # pragma: no cover - bare source checkout
    __version__ = "0.0.0+unknown"

# Founding-idea lineage (see docs/theory.md "Two senses of collapse").
__lineage__ = "exempt: D-finite Ore algebra"

__all__ = [
    "ASYMPTOTIC_SIEVE_EXTERNAL_PREMISES",
    "ASYMPTOTIC_SIEVE_KIND",
    "AdmissibilityReport",
    "AnnihilatorExport",
    "AsymptoticEstimate",
    "BOUNDED_GAP_QUADRATIC_KIND",
    "BoundedGapBaseline",
    "BoundedGapQuadraticCertificate",
    "BoundedGapTargetSpec",
    "CASE_A_B02_KIND",
    "CASE_A_B31_KIND",
    "DEFAULT_GROEBNER_BUDGET",
    "DFinite",
    "ExactCoefficientInterval",
    "ExactSymmetricIntervalMatrix",
    "FIAnalyticUse",
    "FIAtlasParameters",
    "FICombinatorialReplayCertificate",
    "FITermLedgerReport",
    "FITerminalAtlasCertificate",
    "FIXED_SHIFT_DETERMINANT_EXTERNAL_PREMISES",
    "FIXED_SHIFT_DETERMINANT_KIND",
    "FIXED_SHIFT_KERNEL_SAVING_FLOOR",
    "FIXED_SHIFT_TARGET_SAVING",
    "FI_COMBINATORIAL_EXTERNAL_PREMISES",
    "FI_TERMINAL_ATLAS_EXTERNAL_PREMISES",
    "FiniteStatus",
    "FixedShiftDeterminantCase",
    "FixedShiftDeterminantCertificate",
    "FixedShiftKernelCellCertificate",
    "FormalLogVector",
    "GosperResult",
    "GroebnerBudget",
    "GroebnerBudgetExceeded",
    "H1_182_EXTERNAL_PREMISES",
    "H1_182_SHIFTS",
    "H1_186_PUBLISHED_MARGIN",
    "H1_186_REQUIRED_MARGIN",
    "H1_186_RHO_STAR",
    "H1_186_SHIFTS",
    "HEATH_BROWN_SMALL_FACTOR_ROOM",
    "HOLONOMIC_SYZYGY",
    "HolonomicLayerSpec",
    "HolonomicProof",
    "HyperellipticPicardFuchsCertificate",
    "IdealMembership",
    "JACOBIAN_CONJECTURE_PROOF_CLAIM_ALLOWED",
    "JacobianN2DegreeFamily",
    "JacobianN2HomogeneousFamily",
    "KnownEstimate",
    "KnownEstimateKind",
    "LocalFactorIdentity",
    "LocalProductCertificate",
    "LogAffineBound",
    "LogPolyhedralCell",
    "MATRIX_CLOSE_PAIR_KIND",
    "MatrixClosePairCertificate",
    "MatrixVariationalCertificate",
    "MobiusCellReductionCertificate",
    "MonomialOrder",
    "OpenClosedInterval",
    "OreAlgebra",
    "OreDivision",
    "OrePolynomial",
    "PRIME_GAPS_186_COMMIT",
    "PRIME_GAPS_186_SOURCE_SHA256",
    "PRIME_GAPS_186_SOURCE_URL",
    "PRIME_GAPS_INPUT_MANIFEST_KIND",
    "PRIME_GAPS_NUMERICAL_RECEIPT_KIND",
    "PRIME_GAPS_QUADRATIC_RECEIPT_KIND",
    "PRIME_GAP_COEFFICIENT_SIGNATURES",
    "PRIME_GAP_QUADRATIC_MATRIX_NAMES",
    "PRecursive",
    "PSDReport",
    "PicardFuchsCertificate",
    "Poly",
    "PolyN",
    "PrimeGapCell",
    "PrimeGapCoefficientDescriptor",
    "PrimeGapEngineLayout",
    "PrimeGapInputManifest",
    "PrimeGapLadderRow",
    "PrimeGapNumericalReceiptCertificate",
    "PrimeGapQuadraticCandidateCertificate",
    "PrimeGapQuadraticKernelSpec",
    "PrimeGapQuadraticReceiptCertificate",
    "PrimeGapRoundingReserveCertificate",
    "PrimeGapShell",
    "PrimeGapSourceGroup",
    "PrimeGapSourceTask",
    "ProperTerm",
    "QGosperResult",
    "QRecurrence",
    "RationalCell",
    "RationalInput",
    "RationalMatrix",
    "RhoInsertionCertificate",
    "SWIRL_HEAT_KIND",
    "SignedConvolutionSplitCertificate",
    "Summand",
    "TWIN_PRIME_EXTERNAL_PREMISES",
    "Telescoper",
    "VaughanCoefficientCase",
    "WrightRangeReport",
    "ZeilbergerCertificate",
    "__lineage__",
    "__version__",
    "admissibility_report",
    "alpoge_map",
    "asymptotic_sieve_honesty",
    "asymptotic_sieve_local_factor",
    "binomial_nk",
    "bounded_gap_quadratic_honesty",
    "buchberger",
    "build_holonomic_machine",
    "build_prime_gap_input_manifest",
    "canonical_fi_term_ledger",
    "case_a_b02_statement",
    "case_a_b31_statement",
    "certified_asymptotic",
    "certify_asymptotic_sieve_local_product",
    "certify_bounded_gap_quadratic_witness",
    "certify_fi_combinatorial_replay",
    "certify_fi_terminal_atlas",
    "certify_fixed_shift_determinant_replay",
    "certify_fixed_shift_kernel_cell",
    "certify_holonomic_syzygy",
    "certify_hyperelliptic_picard_fuchs",
    "certify_matrix_close_pair",
    "certify_matrix_variational_witness",
    "certify_mobius_cell_reduction",
    "certify_picard_fuchs",
    "certify_prime_gap_numerical_receipt",
    "certify_prime_gap_quadratic_candidate",
    "certify_prime_gap_quadratic_receipt",
    "certify_prime_gap_rounding_reserve",
    "certify_rho_insertion",
    "certify_signed_convolution_split",
    "classify_leftover_chart",
    "creative_telescoping",
    "dfinite_add",
    "dfinite_cauchy",
    "dfinite_compose_poly",
    "dfinite_derivative",
    "dfinite_hadamard",
    "dfinite_integral",
    "dfinite_to_precursive",
    "diff_algebra",
    "dispersion_set",
    "empirical_rate",
    "escalate_n2_result",
    "export_annihilator",
    "fi_atlas_obligation_certificates",
    "fi_combinatorial_honesty",
    "fi_combinatorial_obligation_certificates",
    "fi_rational_terminal_family",
    "fi_terminal_atlas_honesty",
    "fi_vaughan_coefficient_case",
    "fiber_report",
    "fit_holonomic_layer",
    "fixed_shift_determinant_case",
    "fixed_shift_determinant_honesty",
    "gabber_n2_test",
    "gallagher_map",
    "gamma_truncation",
    "gcrd",
    "geometric_k",
    "gosper_definite_sum",
    "gosper_normal_form",
    "gosper_sum",
    "guess_algebraic",
    "guess_dfinite",
    "guess_recurrence",
    "h1_182_target",
    "h1_186_baseline",
    "holonomic_jet",
    "hyper",
    "ideal_member",
    "integer_log_vector",
    "integerize_matrix",
    "jacobian_det",
    "jacobian_n2_box_statement",
    "jacobian_n2_homog_statement",
    "jacobian_n2_honesty",
    "lclm",
    "local_factor_obligation_certificates",
    "matrix_trace_product",
    "maximal_far_sets",
    "mobius_integer",
    "named_swirl_heat_generators",
    "o1_normalize",
    "ore_divmod",
    "oriented_lambda_log_vector",
    "parameterize_prime_gap_evaluator_source",
    "peval",
    "pgcd",
    "precursive_asymptotics",
    "precursive_to_dfinite",
    "prime_gap_coefficient_descriptors",
    "prime_gap_engine_layout",
    "prime_gap_honesty",
    "prime_gap_quadratic_kernel_spec",
    "prove_hypergeometric_identity",
    "prove_identity_zeilberger",
    "prove_swirl_heat_identity",
    "psd_report",
    "q_from_p",
    "q_gosper",
    "q_gosper_definite_sum",
    "q_gosper_normal_form",
    "q_shift_algebra",
    "q_zeilberger",
    "radical_member",
    "rational_roots",
    "recurrence_to_operator",
    "reduced_groebner_basis",
    "reject_jacobian_proof_claim",
    "replay_case_a_b02",
    "replay_case_a_b31",
    "replay_leftover_certificate",
    "replay_swirl_heat_identity",
    "roots_with_multiplicity",
    "seal_asymptotic_sieve_local_product",
    "seal_bounded_gap_quadratic_witness",
    "seal_case_a_b02",
    "seal_case_a_b31",
    "seal_fi_combinatorial_replay",
    "seal_fi_terminal_atlas",
    "seal_fixed_shift_determinant_replay",
    "seal_jacobian_honesty",
    "seal_leftover_certificate",
    "seal_matrix_variational_certificate",
    "seal_mobius_cell_reduction",
    "seal_prime_gap_input_manifest",
    "seal_prime_gap_numerical_receipt",
    "seal_prime_gap_quadratic_receipt",
    "search_tangent_sweep",
    "select_fi_dyadic_s",
    "shift_algebra",
    "square_free",
    "summand_sum",
    "swirl_heat_identity_payload",
    "sylvester_resultant",
    "symmetric_product",
    "term_ratio_annihilates",
    "to_poly",
    "unsigned_oriented_lambda_log_vector",
    "validate_fi_term_ledger",
    "verify_alpoge_map",
    "verify_dyadic_membership",
    "verify_gallagher_map",
    "verify_gamma_mobius_identity",
    "verify_hyperelliptic_picard_fuchs",
    "verify_ideal_membership",
    "verify_picard_fuchs",
    "von_mangoldt_log_vector",
    "wright_fixed_shift_range",
    "wz_certificate",
    "wz_pair",
    "zeilberger",
]
