/- AUTO-GENERATED by omnibias.core.proof.lean_check. DO NOT EDIT.

   At rest this file is a trivially-true placeholder: it carries no active
   obligation.  The certificate -> Lean bridge overwrites it transiently with a
   concrete `obligation` theorem, runs `lake build`, and restores this content. -/
import Omnibias.Certificate

namespace Omnibias.Generated

/-- Placeholder: no active obligation. -/
theorem obligation : True := trivial

end Omnibias.Generated
