/- AUTO-GENERATED by omnibias.core.proof.lean_check. DO NOT EDIT. -/
import Omnibias.Certificate

namespace Omnibias.Generated

/-- The reported winding number is the unique integer in the exact
dyadic lift of the outward binary64 enclosure. The analytic argument-
principle enclosure is a trusted certificate input, not re-derived. -/
def windingIsolated (lo hi denominator integer : Int) : Bool :=
  decide (0 < denominator ∧
    (integer - 1) * denominator < lo ∧
    lo ≤ integer * denominator ∧
    integer * denominator ≤ hi ∧
    hi < (integer + 1) * denominator)

theorem obligation :
    windingIsolated (7613480230931111) (11000290970157834) (4503599627370496) (2) = true := by
  decide

end Omnibias.Generated
