# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Backend-agnostic (numpy / pure-Python) internals of the soft-DP substrate."""

from __future__ import annotations

from omnibias.struct._core.align import (
    AlignmentLattice,
    brute_force_align,
    brute_force_gotoh,
    brute_force_local_align,
    brute_force_soft_align,
    brute_force_soft_gotoh,
    brute_force_soft_local_align,
    build_gotoh_dag,
    build_local_dag,
    hard_align,
    hard_gotoh,
    hard_local_align,
)
from omnibias.struct._core.certificate import DPGapCertificate, certify_soft_dp
from omnibias.struct._core.dtw import (
    DTWLattice,
    brute_force_dtw,
    brute_force_soft_dtw,
    hard_dtw,
)
from omnibias.struct._core.eisner import (
    best_projective_tree,
    brute_force_eisner,
    brute_force_projective,
    count_projective_trees,
    eisner_hypergraph,
    hard_eisner,
    iter_projective_trees,
    soft_eisner,
)
from omnibias.struct._core.gap import logsumexp_gap_bound, stepwise_gap_bound
from omnibias.struct._core.hard_dp import (
    brute_force_ctc,
    brute_force_partition,
    brute_force_shortest_path,
    brute_force_viterbi,
    ctc_best,
    ctc_best_alignment,
    shortest_path,
    viterbi,
)
from omnibias.struct._core.monotonic import (
    brute_force_mas,
    brute_force_soft_mas,
    count_alignments,
    hard_mas,
)
from omnibias.struct._core.mtt import (
    brute_force_arborescence,
    count_arborescences,
    hard_matrix_tree,
    iter_arborescences,
    matrix_tree_marginals,
    matrix_tree_partition,
    max_arborescence,
)
from omnibias.struct._core.operators import (
    brute_force_entropy,
    brute_force_kbest,
    kbest_derivations,
    sample_derivations,
)
from omnibias.struct._core.parse import (
    BinaryGrammar,
    best_parse_tree,
    brute_force_cky,
    build_chart,
    count_parse_trees,
    hard_cky,
    soft_cky,
)
from omnibias.struct._core.paths import log_num_paths
from omnibias.struct._core.plan import (
    AcyclicMDP,
    brute_force_optimal_return,
    hard_value_iteration,
)
from omnibias.struct._core.select import (
    SelectionCertificate,
    argmax_stability_margin,
    beta_for_confidence,
    certify_argmax,
    mass_concentration_bound,
    seal_selection_certificate,
)
from omnibias.struct._core.semiring import (
    CountingSemiring,
    HyperEdge,
    Hypergraph,
    LogSemiring,
    LSEBeta,
    MaxPlusSemiring,
    Semiring,
    best_derivation,
    brute_force_value,
    count_derivations,
    derivation_weight,
    enumerate_derivations,
    from_dag,
    hard_value,
    semiring_value,
    soft_value,
)
from omnibias.struct._core.trellis import DAG, ChainTrellis, CTCLattice, count_paths
from omnibias.struct._core.tropical import (
    TropicalGapCertificate,
    TropicalLinear,
    certify_tropical_gap,
    dual_subdivision,
    homotopy_gap_bound,
    newton_polytope,
    relaxed_value,
    relaxed_weights,
    tropical_value,
)

__all__ = [
    "AcyclicMDP",
    "AlignmentLattice",
    "BinaryGrammar",
    "CTCLattice",
    "ChainTrellis",
    "CountingSemiring",
    "DAG",
    "DPGapCertificate",
    "DTWLattice",
    "HyperEdge",
    "Hypergraph",
    "LSEBeta",
    "LogSemiring",
    "MaxPlusSemiring",
    "SelectionCertificate",
    "Semiring",
    "TropicalGapCertificate",
    "TropicalLinear",
    "argmax_stability_margin",
    "best_derivation",
    "best_parse_tree",
    "best_projective_tree",
    "beta_for_confidence",
    "brute_force_align",
    "brute_force_arborescence",
    "brute_force_cky",
    "brute_force_ctc",
    "brute_force_dtw",
    "brute_force_eisner",
    "brute_force_entropy",
    "brute_force_gotoh",
    "brute_force_kbest",
    "brute_force_local_align",
    "brute_force_mas",
    "brute_force_optimal_return",
    "brute_force_partition",
    "brute_force_projective",
    "brute_force_shortest_path",
    "brute_force_soft_align",
    "brute_force_soft_dtw",
    "brute_force_soft_gotoh",
    "brute_force_soft_local_align",
    "brute_force_soft_mas",
    "brute_force_value",
    "brute_force_viterbi",
    "build_chart",
    "build_gotoh_dag",
    "build_local_dag",
    "certify_argmax",
    "certify_soft_dp",
    "certify_tropical_gap",
    "count_alignments",
    "count_arborescences",
    "count_derivations",
    "count_parse_trees",
    "count_paths",
    "count_projective_trees",
    "ctc_best",
    "ctc_best_alignment",
    "derivation_weight",
    "dual_subdivision",
    "eisner_hypergraph",
    "enumerate_derivations",
    "from_dag",
    "hard_align",
    "hard_cky",
    "hard_dtw",
    "hard_eisner",
    "hard_gotoh",
    "hard_local_align",
    "hard_mas",
    "hard_matrix_tree",
    "hard_value",
    "hard_value_iteration",
    "homotopy_gap_bound",
    "iter_arborescences",
    "iter_projective_trees",
    "kbest_derivations",
    "log_num_paths",
    "logsumexp_gap_bound",
    "mass_concentration_bound",
    "matrix_tree_marginals",
    "matrix_tree_partition",
    "max_arborescence",
    "newton_polytope",
    "relaxed_value",
    "relaxed_weights",
    "sample_derivations",
    "seal_selection_certificate",
    "semiring_value",
    "shortest_path",
    "soft_cky",
    "soft_eisner",
    "soft_value",
    "stepwise_gap_bound",
    "tropical_value",
    "viterbi",
]
