# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Derivon
"""Shared activation specifications, derivative coefficients, and jet algebra.

Numerical implementations live in explicit submodules; this package has no
tensor-framework dependency.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError as _PkgNotFound
from importlib.metadata import version as _pkg_version

from omnibias.core.bell import (
    bell_complete,
    bell_number,
    bell_partial,
    faa_di_bruno_terms,
)
from omnibias.core.block_search import (
    BlockKind,
    BlockSpec,
    apply_block_step,
    arrangement_w_block,
    default_block_config,
    last_linear_block,
    ombu_bias_block,
    resolve_block_mask,
    unit_direction_from_mask,
)
from omnibias.core.composed_curvature import (
    ComposedCurvatureConfig,
    ComposedCurvatureReport,
    chain_rule_mse_blocks,
    eigh_symmetric,
    eval_tanh_derivative,
    reject_full_parameter_jacobian,
    scalar_nest_hessian,
    select_composed_step,
    solve_dense,
    symmetrize,
)
from omnibias.core.cubature import (
    MomentSystem,
    QuadratureRule,
    apply_rule,
    certified_error,
    design_rule,
    pack_moment,
    peano_kernel,
    solve_rule,
    target_moments,
)
from omnibias.core.frames import (
    FrameSpec,
    admissibility_constant,
    compile_bank,
    dilated_sigma_n,
    vanishing_moments,
)
from omnibias.core.implicit import (
    DEQConfig,
    DEQNotContractive,
    DEQSolverUnknown,
    honesty_payload,
    reject_anderson,
    reject_deq_contraction,
    spectral_radius_inf_bound,
)
from omnibias.core.jets import contact_residual, is_holonomic
from omnibias.core.line_search import (
    GradientSecant,
    JetLineSearchConfig,
    LineSearchResult,
    certified_truncation_radius,
    polynomial_wolfe,
    run_model_line_search,
    select_model_step,
    taylor_coeffs_from_derivatives,
)
from omnibias.core.locus import (
    AffineSet,
    EqualitySystem,
    NewtonResult,
    UnitTerm,
    affine_locus,
    certify_locus_point,
)
from omnibias.core.mollifier import (
    MollifierSpec,
    design_order,
    is_admissible,
    moments,
    tail_bound,
)
from omnibias.core.multi_index import (
    index_position,
    multi_index_factorial,
    multi_indices,
    multiply_table,
    num_multi_indices,
)
from omnibias.core.multipack import (
    MultiPackSpec,
    PackSpec,
    central_stencil_weights,
    incidence_matrix,
    is_poised,
    polya_condition,
)
from omnibias.core.polynomials import (
    hermite_coeffs,
    mish_inner_coeffs,
    sigmoid_polynomial_coeffs,
    tanh_polynomial_coeffs,
)
from omnibias.core.refine import (
    Indicator,
    RefinedPack,
    RefinePolicy,
    RefineReport,
    assert_zero_perturbation,
    hp_decision,
    local_scale_from_derivatives,
    refine_bank,
)
from omnibias.core.scale import (
    EffectiveOperator,
    FlowSystem,
    ScaleBand,
    ScaledPack,
    coarse_grain_linear,
    eval_gaussian_derivative,
    flow_coefficients,
    gram_matrix,
    overlap,
    report_exponents,
    rescale_pack,
    stiffness_matrix,
)
from omnibias.core.scan import BankSpec
from omnibias.core.spec import (
    ActivationSpec,
    NthDerivativeFn,
    TensorFn,
    TensorT,
    TransformKernels,
    make_tempered_fastpath,
    make_tempered_transforms,
    tempered,
)
from omnibias.core.spectral_design import (
    BandPlan,
    alpha_for_peak,
    design_band_plan,
    peak_frequency,
    relative_bandwidth,
    response_profile,
)
from omnibias.core.tanh_method import TravellingWaveAnsatz, verify_exact
from omnibias.core.transfer import Layer, certified_band_gap
from omnibias.core.transforms_pde import (
    LinearizingTransform,
    cole_hopf_jet,
    cole_hopf_u,
    factorial_jet_multiply,
    factorial_jet_reciprocal,
    verify_cole_hopf_burgers_jet,
    verify_transform,
)
from omnibias.core.weight_loss_jet import (
    WeightLossJetSpec,
    eval_sigma_derivative,
    one_layer_loss,
    one_layer_loss_grad,
    one_layer_loss_hessian,
    one_layer_loss_jet,
    one_layer_newton_direction,
    one_layer_output_jet,
    one_layer_param_count,
    pack_one_layer_params,
    unpack_one_layer_params,
)

try:
    __version__ = _pkg_version("omnibias-core")
except _PkgNotFound:  # pragma: no cover - bare source checkout
    __version__ = "0.0.0+unknown"

# Limit family exposed as package metadata.
__lineage__ = "bias collapse"

__all__ = [
    'ActivationSpec',
    'AffineSet',
    'BandPlan',
    'BankSpec',
    'BlockKind',
    'BlockSpec',
    'ComposedCurvatureConfig',
    'ComposedCurvatureReport',
    'DEQConfig',
    'DEQNotContractive',
    'DEQSolverUnknown',
    'EffectiveOperator',
    'EqualitySystem',
    'FlowSystem',
    'FrameSpec',
    'GradientSecant',
    'Indicator',
    'JetLineSearchConfig',
    'Layer',
    'LineSearchResult',
    'LinearizingTransform',
    'MollifierSpec',
    'MomentSystem',
    'MultiPackSpec',
    'NewtonResult',
    'NthDerivativeFn',
    'PackSpec',
    'QuadratureRule',
    'RefinePolicy',
    'RefineReport',
    'RefinedPack',
    'ScaleBand',
    'ScaledPack',
    'TensorFn',
    'TensorT',
    'TransformKernels',
    'TravellingWaveAnsatz',
    'UnitTerm',
    'WeightLossJetSpec',
    '__lineage__',
    '__version__',
    'admissibility_constant',
    'affine_locus',
    'alpha_for_peak',
    'apply_block_step',
    'apply_rule',
    'arrangement_w_block',
    'assert_zero_perturbation',
    'bell_complete',
    'bell_number',
    'bell_partial',
    'central_stencil_weights',
    'certified_band_gap',
    'certified_error',
    'certified_truncation_radius',
    'certify_locus_point',
    'chain_rule_mse_blocks',
    'coarse_grain_linear',
    'cole_hopf_jet',
    'cole_hopf_u',
    'compile_bank',
    'contact_residual',
    'default_block_config',
    'design_band_plan',
    'design_order',
    'design_rule',
    'dilated_sigma_n',
    'eigh_symmetric',
    'eval_gaussian_derivative',
    'eval_sigma_derivative',
    'eval_tanh_derivative',
    'factorial_jet_multiply',
    'factorial_jet_reciprocal',
    'flow_coefficients',
    'gram_matrix',
    'hermite_coeffs',
    'honesty_payload',
    'hp_decision',
    'incidence_matrix',
    'index_position',
    'is_admissible',
    'is_holonomic',
    'is_poised',
    'last_linear_block',
    'local_scale_from_derivatives',
    'make_tempered_fastpath',
    'make_tempered_transforms',
    'mish_inner_coeffs',
    'moments',
    'multi_index_factorial',
    'multi_indices',
    'multiply_table',
    'num_multi_indices',
    'ombu_bias_block',
    'one_layer_loss',
    'one_layer_loss_grad',
    'one_layer_loss_hessian',
    'one_layer_loss_jet',
    'one_layer_newton_direction',
    'one_layer_output_jet',
    'one_layer_param_count',
    'overlap',
    'pack_moment',
    'pack_one_layer_params',
    'peak_frequency',
    'peano_kernel',
    'polya_condition',
    'polynomial_wolfe',
    'refine_bank',
    'reject_anderson',
    'reject_deq_contraction',
    'reject_full_parameter_jacobian',
    'relative_bandwidth',
    'report_exponents',
    'rescale_pack',
    'resolve_block_mask',
    'response_profile',
    'run_model_line_search',
    'scalar_nest_hessian',
    'select_composed_step',
    'select_model_step',
    'sigmoid_polynomial_coeffs',
    'solve_dense',
    'solve_rule',
    'spectral_radius_inf_bound',
    'stiffness_matrix',
    'symmetrize',
    'tail_bound',
    'tanh_polynomial_coeffs',
    'target_moments',
    'taylor_coeffs_from_derivatives',
    'tempered',
    'unit_direction_from_mask',
    'unpack_one_layer_params',
    'vanishing_moments',
    'verify_cole_hopf_burgers_jet',
    'verify_exact',
    'verify_transform',
]
